import type { DraftTemplate } from "@/types";

/** 동물 도안 */
export const ANIMAL_DRAFTS: DraftTemplate[] = [
  {
    id: "cat",
    name: "고양이",
    aliases: ["냥이", "야옹이", "cat", "kitty"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      o: "#f6a04d",
      p: "#ff9eb1",
      d: "#e08a3a",
    },
    rows: [
      "................",
      ".k............k.",
      ".kk..........kk.",
      ".kok........kok.",
      ".kookkkkkkkkook.",
      ".kooooooooooook.",
      "kooooooooooooook",
      "kooooooooooooook",
      "kookooooooookook",
      "kookooooooookook",
      "kpoooooooooooopk",
      "kooooooppooooook",
      "kooooookkooooook",
      ".kooooooooooook.",
      "..kkkkkkkkkkkk..",
      "................",
    ],
    rows32: [
      "................................",
      "...kk......................kk...",
      "..kookk..................kkook..",
      "..kooook................kooook..",
      "..koooookk............kkoooook..",
      "..koopooookk........kkoooopook..",
      "..koopppooook......koooopppook..",
      "..kooppppokkkkkkkkkkkkoppppook..",
      "..koopppppoooooddooooopppppook..",
      "..koopppoooodooddoodoooopppook..",
      "..koopkooooodooddoodoooookpook..",
      "..kookoooooodooddoodooooookook..",
      "..kokooooooooooooooooooooookok..",
      "..kkooooooooooooooooooooooookk..",
      "..kooooooooooooooooooooooooook..",
      "..kooooooooooooooooooooooooook..",
      "..koooooowkoooooooooowkooooook..",
      "..kooooookkooooooooookkooooook..",
      ".koooooookkooooooooookkoooooook.",
      "kkkooooooooooooooooooooooooookkk",
      "..kkkooooooooooppooooooooookkk..",
      "..kooopppoookookkookooopppoook..",
      "..kkkpppppoookkookkooopppppkkk..",
      "kk.koopppoooooooooooooopppook.kk",
      "....kooooooooooooooooooooook....",
      ".....kooooooooooooooooooook.....",
      "......kooooooooooooooooook......",
      ".......kooooooooooooooook.......",
      "........kkooooooooooookk........",
      "..........kkkkkkkkkkkk..........",
      "................................",
      "................................",
    ],
  },
  {
    id: "bear",
    name: "곰",
    aliases: ["곰돌이", "bear", "테디베어"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#a0673c",
      t: "#e8c39e",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      ".kkk........kkk.",
      "kbbbk......kbbbk",
      "kbtbkkkkkkkkbtbk",
      "kbbbbbbbbbbbbbbk",
      "kbbbbbbbbbbbbbbk",
      "kbbbbbbbbbbbbbbk",
      "kbbkbbbbbbbbkbbk",
      "kbbkbbbbbbbbkbbk",
      "kbbbbttttttbbbbk",
      "kbpbtttkktttbpbk",
      "kbbbttttttttbbbk",
      ".kbbbttttttbbbk.",
      "..kbbbbbbbbbbk..",
      "...kkkkkkkkkk...",
      "................",
    ],
    rows32: [
      "................................",
      "......k..................k......",
      "...kkkbkkk............kkkbkkk...",
      "..kbbbbbbbk..........kbbbbbbbk..",
      ".kbbbbbbbbbk........kbbbbbbbbbk.",
      ".kbbbtttbbbkkkkkkkkkkbbbtttbbbk.",
      ".kbbtttttkkkbbbbbbbbkkktttttbbk.",
      "kbbbtttkkbbbbbbbbbbbbbbkktttbbbk",
      ".kbbttkbbbbbbbbbbbbbbbbbbkttbbk.",
      ".kbbbkbbbbbbbbbbbbbbbbbbbbkbbbk.",
      ".kbbkbbbbbbbbbbbbbbbbbbbbbbkbbk.",
      "..kkbbbbbbbbbbbbbbbbbbbbbbbbkk..",
      "...kbbbbbbbbbbbbbbbbbbbbbbbbk...",
      "..kbbbbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbbbbbbbbbbbbbbbbbbbbbbbbbk..",
      ".kbbbbbbbwkbbbbbbbbbbwkbbbbbbbk.",
      ".kbbbbbbbkkbbbbbbbbbbkkbbbbbbbk.",
      ".kbbbbbbbkkbbbbbbbbbbkkbbbbbbbk.",
      ".kbbbbbbbbbbbbttttbbbbbbbbbbbbk.",
      ".kbbbbbbbbbbtttkktttbbbbbbbbbbk.",
      ".kbbbbbbbbttttkwkkttttbbbbbbbbk.",
      "..kbbpppbbttttkkkkttttbbpppbbk..",
      "..kbbpppbbtttttkktttttbbpppbbk..",
      "...kbbbbbbtttttkktttttbbbbbbk...",
      "...kbbbbbbtttkkttkktttbbbbbbk...",
      "....kbbbbbttttttttttttbbbbbk....",
      ".....kbbbbbbttttttttbbbbbbk.....",
      "......kbbbbbbbttttbbbbbbbk......",
      ".......kkbbbbbbbbbbbbbbkk.......",
      ".........kkkbbbbbbbbkkk.........",
      "............kkkkkkkk............",
      "................................",
    ],
  },
  {
    id: "rabbit",
    name: "토끼",
    aliases: ["토깽이", "rabbit", "bunny"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#ff9eb1",
    },
    rows: [
      "..kk........kk..",
      ".kwwk......kwwk.",
      ".kwpk......kpwk.",
      ".kwpk......kpwk.",
      ".kwpk......kpwk.",
      ".kwwk......kwwk.",
      ".kwwkkkkkkkkwwk.",
      "kwwwwwwwwwwwwwwk",
      "kwwwwwwwwwwwwwwk",
      "kwwkwwwwwwwwkwwk",
      "kwwkwwwwwwwwkwwk",
      "kppwwwwppwwwwppk",
      "kwwwwwwkkwwwwwwk",
      ".kwwwwwwwwwwwwk.",
      "..kkkkkkkkkkkk..",
      "................",
    ],
    rows32: [
      "........kwwwk......kwwwk........",
      ".......kwwwwwk....kwwwwwk.......",
      ".......kwwwwwk....kwwwwwk.......",
      "......kwwwpwwwk..kwwwpwwwk......",
      "......kwwwpwwwk..kwwwpwwwk......",
      "......kwwpppwwk..kwwpppwwk......",
      "......kwwpppwwk..kwwpppwwk......",
      "......kwwpppwwk..kwwpppwwk......",
      "......kwwpppwwk..kwwpppwwk......",
      "......kwwpppwwk..kwwpppwwk......",
      "......kwwpppwkkkkkkwpppwwk......",
      "......kwwkkkkwwwwwwkkkkwwk......",
      "......kkkwwwwwwwwwwwwwwkkk......",
      "......kwwwwwwwwwwwwwwwwwwk......",
      ".....kwwwwwwwwwwwwwwwwwwwwk.....",
      "....kwwwwwwwwwwwwwwwwwwwwwwk....",
      "...kwwwwwwwwwwwwwwwwwwwwwwwwk...",
      "..kwwwwwwwwwwwwwwwwwwwwwwwwwwk..",
      "..kwwwwwwwkwwwwwwwwwwwkwwwwwwk..",
      "..kwwwwwwkkwwwwwwwwwwkkwwwwwwk..",
      "..kwwwwwwkkwwwwwwwwwwkkwwwwwwk..",
      "..kwwwwwwwwwwwwwwwwwwwwwwwwwwk..",
      "..kwwwwwwwwwwwwppwwwwwwwwwwwwk..",
      "..kwpppppwwwkwwkkwwkwwwpppppwk..",
      "..kwpppppwwwwkkwwkkwwwwpppppwk..",
      "...kwwwwwwwwwwwwwwwwwwwwwwwwk...",
      "....kwwwwwwwwwwwwwwwwwwwwwwk....",
      ".....kwwwwwwwwwwwwwwwwwwwwk.....",
      "......kwwwwwwwwwwwwwwwwwwk......",
      ".......kkwwwwwwwwwwwwwwkk.......",
      ".........kkkkwwwwwwkkkk.........",
      ".............kkkkkk.............",
    ],
  },
  {
    id: "dog",
    name: "강아지",
    aliases: ["멍멍이", "개", "puppy", "dog"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      d: "#e2a86a",
      e: "#9c6334",
      l: "#f8e3c4",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      "...kkkkkkkkkk...",
      "..kddddddddddk..",
      "kkkddddddddddkkk",
      "keekddddddddkeek",
      "keekddddddddkeek",
      "keekdkddddkdkeek",
      "keekdkddddkdkeek",
      "keekdlllllldkeek",
      "keekdllkklldkeek",
      ".kkkdlllllldkkk.",
      "...kdllkklldk...",
      "...kddddddddk...",
      "....kddddddk....",
      ".....kkkkkk.....",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "................................",
      "...........kkkkkkkkkk...........",
      ".........kkddddddddddkk.........",
      ".....kkkkkddddddddddddkkkkk.....",
      "....keeeeekddddddddddkeeeeek....",
      "...keeeeeekddddddddddkeeeeeek...",
      "..keeeeeeekddddddddddkeeeeeeek..",
      "..keeeeeeekddddddddddkeeeeeeek..",
      ".keeeeeeeekddddddddddkeeeeeeeek.",
      ".keeeeeeeekddddddddddkeeeeeeeek.",
      ".keeeeeeeekddddddddddkeeeeeeeek.",
      ".keeeeeeeekddddddddddkeeeeeeeek.",
      ".keeeeeeeewkddddddddwkeeeeeeeek.",
      ".keeeeeeeekkddddddddkkeeeeeeeek.",
      ".keeeeeeeekkddddddddkkeeeeeeeek.",
      ".keeeeeeeekddllllllddkeeeeeeeek.",
      ".keeeeeeekdlllkkkkllldkeeeeeeek.",
      ".keeeeeekdlllkkwkkkllldkeeeeeek.",
      "..kkeeepppplllkkkklllppppeeekk..",
      "....kekppppllllkkllllppppkek....",
      "....kkdddlllkllkkllkllldddkk....",
      ".....kdddllllkkllkklllldddk.....",
      "......kdddlllllllllllldddk......",
      ".......kdddlllllllllldddk.......",
      "........kddddllllllddddk........",
      ".........kkddddddddddkk.........",
      "...........kkkkkkkkkk...........",
      "................................",
      "................................",
    ],
  },
  {
    id: "chick",
    name: "병아리",
    aliases: ["삐약이", "chick", "새", "아기새"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
      o: "#ff9f1c",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      ".......kk.......",
      ".....kkkkkk.....",
      "....kyyyyyyk....",
      "...kyyyyyyyyk...",
      "..kyyyyyyyyyyk..",
      "..kyykyyyykyyk..",
      ".kyyykyyyykyyyk.",
      ".kyyyyooooyyyyk.",
      ".kpyyyyooyyyypk.",
      ".kyyyyyyyyyyyyk.",
      ".kyyyyyyyyyyyyk.",
      "..kyyyyyyyyyyk..",
      "...kkkkkkkkkk...",
      ".....o....o.....",
      "....oo....oo....",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "...............k..k.............",
      "................kk..............",
      "...........kkkkkkkkkk...........",
      ".........kkyyyyyyyyyykk.........",
      "........kyyyyyyyyyyyyyyk........",
      ".......kyyyyyyyyyyyyyyyyk.......",
      "......kyyyyyyyyyyyyyyyyyyk......",
      ".....kyyyyyyyyyyyyyyyyyyyyk.....",
      ".....kyyyyyyyyyyyyyyyyyyyyk.....",
      "....kyyyyyyyyyyyyyyyyyyyyyyk....",
      "....kyyyyyyyyyyyyyyyyyyyyyyk....",
      "...kyyyyyywkyyyyyyyywkyyyyyyk...",
      "...kyyyyyykkyyyyyyyykkyyyyyyk...",
      "...kyyyyyykkyyyyyyyykkyyyyyyk...",
      "...kyyyyyyyyykkkkkkyyyyyyyyyk...",
      "...kyyyyyyyykooooookyyyyyyyyk...",
      "..kkyyypppyyykooookyyypppyyykk..",
      ".kykyypppppyyykookyyypppppyykyk.",
      ".kyykyypppyyyyykkyyyyypppyykyyk.",
      "..kykyyyyyyyyyyyyyyyyyyyyyykyk..",
      "...kykyyyyyyyyyyyyyyyyyyyykyk...",
      "....kkyyyyyyyyyyyyyyyyyyyykk....",
      "......kyyyyyyyyyyyyyyyyyyk......",
      ".......kyyyyyyyyyyyyyyyyk.......",
      "........kyyyyyyyyyyyyyyk........",
      ".........kkyyyyyyyyyykk.........",
      "...........kkkkkkkkkk...........",
      "...........oo......oo...........",
      "..........oooo....oooo..........",
    ],
  },
  {
    id: "pig",
    name: "돼지",
    aliases: ["꿀꿀이", "pig", "돼지코"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#ffb3c6",
      d: "#ff8fab",
    },
    rows: [
      "................",
      ".kk..........kk.",
      ".kpk........kpk.",
      ".kppkkkkkkkkppk.",
      ".kppppppppppppk.",
      "kppppppppppppppk",
      "kppkppppppppkppk",
      "kppkppppppppkppk",
      "kpppkkkkkkkkpppk",
      "kpppkdkddkdkpppk",
      "kpppkkkkkkkkpppk",
      "kppppppppppppppk",
      ".kppppppppppppk.",
      "..kppppppppppk..",
      "...kkkkkkkkkk...",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "....k......................k....",
      "...kpkk..................kkpk...",
      "...kpppk................kpppk...",
      "...kppppk..............kppppk...",
      "...kppdppkk.kkkkkkkk.kkppdppk...",
      "...kppddpkkkppppppppkkkpddppk...",
      "...kppdkkppppppppppppppkkdppk...",
      "...kppkppppppppppppppppppkppk...",
      "...kpkppppppppppppppppppppkpk...",
      "...kkppppppppppppppppppppppkk...",
      "...kppppppppppppppppppppppppk...",
      "..kppppppppppppppppppppppppppk..",
      "..kppppppwkppppppppppwkppppppk..",
      ".kpppppppkkppppppppppkkpppppppk.",
      ".kpppppppkkppppppppppkkpppppppk.",
      ".kppppppppppppkkkkppppppppppppk.",
      ".kppppppppppkkddddkkppppppppppk.",
      ".kpppppppppkddddddddkpppppppppk.",
      ".kpppdddppkddddddddddkppdddpppk.",
      ".kppdddddpkddkddddkddkpdddddppk.",
      "..kppdddppkddkddddkddkppdddppk..",
      "..kpppppppkddddddddddkpppppppk..",
      "...kpppppppkddddddddkpppppppk...",
      "....kpppppppkkddddkkpppppppk....",
      ".....kppppppppkkkkppppppppk.....",
      "......kppppppppppppppppppk......",
      ".......kkppppppppppppppkk.......",
      ".........kkkppppppppkkk.........",
      "............kkkkkkkk............",
      "................................",
    ],
  },
  {
    id: "frog",
    name: "개구리",
    aliases: ["frog", "개굴"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      g: "#6bcb77",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      ".kkkk......kkkk.",
      "kwwwwk....kwwwwk",
      "kwkkwk....kwkkwk",
      "kwkkwkkkkkkwkkwk",
      "kggggggggggggggk",
      "kggggggggggggggk",
      "kpggggggggggggpk",
      "kgkggggggggggkgk",
      "kggkkkkkkkkkkggk",
      "kggggggggggggggk",
      ".kggggggggggggk.",
      "..kkkkkkkkkkkk..",
      "................",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      ".......kkkk..........kkkk.......",
      ".....kkggggkk......kkggggkk.....",
      "....kggggggggk....kggggggggk....",
      "...kggggwwggggk..kggggwwggggk...",
      "...kggwwwwwwggk..kggwwwwwwggk...",
      "...kggwwwwwwggk..kggwwwwwwggk...",
      "..kgggwwwwkwgggkkgggwkwwwwgggk..",
      "...kggwwwkkwggggggggwkkwwwggk...",
      "...kggwwwkkwggggggggwkkwwwggk...",
      "...kggggwwggggggggggggwwggggk...",
      "....kggggggggggggggggggggggk....",
      "...kggggggggggggggggggggggggk...",
      "..kggggggggggggggggggggggggggk..",
      ".kggggggggggggggggggggggggggggk.",
      ".kgggggggggggkkggkkgggggggggggk.",
      ".kggggggggggggggggggggggggggggk.",
      ".kggpppggggggggggggggggggpppggk.",
      ".kggpppggggggggggggggggggpppggk.",
      ".kggggggggggggggggggggggggggggk.",
      ".kggggggkggggggggggggggkggggggk.",
      ".kgggggggkkggggggggggkkgggggggk.",
      "..kggggggggkkkggggkkkggggggggk..",
      "...kggggggggggkkkkggggggggggk...",
      "....kggggggggggggggggggggggk....",
      ".....kggggggggggggggggggggk.....",
      "......kkggggggggggggggggkk......",
      "........kkkggggggggggkkk........",
      "...........kkkkkkkkkk...........",
      "................................",
    ],
  },
  {
    id: "penguin",
    name: "펭귄",
    aliases: ["penguin", "펭수"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      n: "#3b4a5e",
      o: "#ff9f1c",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      "....kkkkkkkk....",
      "...knnnnnnnnk...",
      "..knnnnnnnnnnk..",
      "..knwwwwwwwwnk..",
      ".knwkwwwwwwkwnk.",
      ".knwwwoooowwwnk.",
      ".knwwwwoowwwwnk.",
      "knnwwwwwwwwwwnnk",
      "knnwwwwwwwwwwnnk",
      "knnwwwwwwwwwwnnk",
      "knnwwwwwwwwwwnnk",
      ".knnwwwwwwwwnnk.",
      "..knnnnnnnnnnk..",
      "..kookkkkkkook..",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      ".............kkkkkk.............",
      "...........kknnnnnnkk...........",
      ".........kknnnnnnnnnnkk.........",
      "........knnnnnnnnnnnnnnk........",
      ".......knnnnnnnnnnnnnnnnk.......",
      "......knnnnnnnnnnnnnnnnnnk......",
      ".....knnnwwwwwwnnwwwwwwnnnk.....",
      ".....knnwwwwwwwwwwwwwwwwnnk.....",
      "....knnwwwwwwwwwwwwwwwwwwnnk....",
      "....knnwwwwwkwwwwwwwkwwwwnnk....",
      "....knnwwwwkkwwwwwwkkwwwwnnk....",
      "...knnnwwwwkkwwwwwwkkwwwwnnnk...",
      "...knnnwwwwwwwwwwwwwwwwwwnnnk...",
      "...knnnwwwwwwwkkkkwwwwwwwnnnk...",
      "...knnnpppwwwkooookwwwpppnnnk...",
      "..kknnnpppwwwwkookwwwwpppnnnkk..",
      "..kknnnwwwwwwwwkkwwwwwwwwnnnkk..",
      ".knknnnwwwwwwwwwwwwwwwwwwnnnknk.",
      ".knnknnwwwwwwwwwwwwwwwwwwnnknnk.",
      "knnnknnwwwwwwwwwwwwwwwwwwnnknnnk",
      "knnnknnwwwwwwwwwwwwwwwwwwnnknnnk",
      ".knk.knwwwwwwwwwwwwwwwwwwnk.knk.",
      "..k..knnwwwwwwwwwwwwwwwwnnk..k..",
      "......knnwwwwwwwwwwwwwwnnk......",
      ".......knwwwwwwwwwwwwwwnk.......",
      "........knnwwwwwwwwwwnnk........",
      "........kkkkkkwwwwkkkkkk........",
      ".......kooooooknnkooooook.......",
      ".......kooooookkkkooooook.......",
      "........kkkkkk....kkkkkk........",
    ],
  },
  {
    id: "panda",
    name: "판다",
    aliases: ["panda", "푸바오"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      ".kkk........kkk.",
      "kkkkk......kkkkk",
      "kkkkkkkkkkkkkkkk",
      "kwwwwwwwwwwwwwwk",
      "kwwwwwwwwwwwwwwk",
      "kwwkkwwwwwwkkwwk",
      "kwkwkwwwwwwkwkwk",
      "kwkkkwwwwwwkkkwk",
      "kwwwwwwkkwwwwwwk",
      "kpwwwwwwwwwwwwpk",
      ".kwwwwwwwwwwwwk.",
      "..kwwwwwwwwwwk..",
      "...kkkkkkkkkk...",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      ".....kkk................kkk.....",
      "...kkkkkkk............kkkkkkk...",
      "..kkkkkkkkk..........kkkkkkkkk..",
      ".kkkkkkkkkkk........kkkkkkkkkkk.",
      ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
      ".kkkkkkkkkkkwwwwwwwwkkkkkkkkkkk.",
      ".kkkkkkkkwwwwwwwwwwwwwwkkkkkkkk.",
      ".kkkkkkwwwwwwwwwwwwwwwwwwkkkkkk.",
      ".kkkkkwwwwwwwwwwwwwwwwwwwwkkkkk.",
      "..kkkwwwwwwwwwwwwwwwwwwwwwwkkk..",
      "...kwwwwwwwwwwwwwwwwwwwwwwwwk...",
      "...kwwwwwwwwwwwwwwwwwwwwwwwwk...",
      "..kwwwwwwkkkwwwwwwwwkkkwwwwwwk..",
      "..kwwwwkkkkkkwwwwwwkkkkkkwwwwk..",
      ".kwwwwkkkwwkkwwwwwwkkwwkkkwwwwk.",
      ".kwwwwkkkkkkkwwwwwwkkkkkkkwwwwk.",
      ".kwwwwkkkkkkkwwwwwwkkkkkkkwwwwk.",
      ".kwwwwwkkkkkwwwwwwwwkkkkkwwwwwk.",
      ".kwwwwwkkkkkwwwwwwwwkkkkkwwwwwk.",
      ".kwwwwwkkkkwwwkkkkwwwkkkkwwwwwk.",
      "..kwwwwwwwwwwwkkkkwwwwwwwwwwwk..",
      "..kwwppwwwwwwwwkkwwwwwwwwppwwk..",
      "...kppppwwwwwwwkkwwwwwwwppppk...",
      "...kwppwwwwwwkkwwkkwwwwwwppwk...",
      "....kwwwwwwwwwwwwwwwwwwwwwwk....",
      ".....kwwwwwwwwwwwwwwwwwwwwk.....",
      "......kwwwwwwwwwwwwwwwwwwk......",
      ".......kkwwwwwwwwwwwwwwkk.......",
      ".........kkkwwwwwwwwkkk.........",
      "............kkkkkkkk............",
      "................................",
    ],
  },
  {
    id: "hamster",
    name: "햄스터",
    aliases: ["hamster", "햄찌", "다람쥐"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      h: "#f2c08a",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      "................",
      "..kk........kk..",
      ".khhk......khhk.",
      ".khpkkkkkkkkphk.",
      ".khhhhhhhhhhhhk.",
      "khhhhhhhhhhhhhhk",
      "khhkhhhhhhhhkhhk",
      "kwwkhhhhhhhhkwwk",
      "kwpwwwwppwwwwpwk",
      "kwwwwwwkkwwwwwwk",
      ".kwwwwwwwwwwwwk.",
      "..khhwwwwwwhhk..",
      "...kkkkkkkkkk...",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      ".....kkkk..............kkkk.....",
      "....khhhhk............khhhhk....",
      "...khhhhhhk.kkkkkkkk.khhhhhhk...",
      "..khhhpphkkkhhhhhhhhkkkhpphhhk..",
      "..khhppkkhhhhhhhhhhhhhhkkpphhk..",
      "..khhhkhhhhhhhhhhhhhhhhhhkhhhk..",
      "...khkhhhhhhhhhwwhhhhhhhhhkhk...",
      "....khhhhhhhhhhwwhhhhhhhhhhk....",
      "...khhhhhhhhhhhwwhhhhhhhhhhhk...",
      "...khhhhhhhhhhhwwhhhhhhhhhhhk...",
      "..khhhhhhhhhhhhwwhhhhhhhhhhhhk..",
      "..khhhhhhhhhhhhwwhhhhhhhhhhhhk..",
      ".khhhhhhhwkhhhhwwhhhhwkhhhhhhhk.",
      ".khhhhhwwkkhhhhhhhhhhkkwwhhhhhk.",
      ".khhhwwwwkkwwhhhhhhwwkkwwwwhhhk.",
      ".khhwwwwwwwwwwwwwwwwwwwwwwwwhhk.",
      ".khhwwwwwwwwwwwwwwwwwwwwwwwwhhk.",
      ".khhpppwwwwwwwwppwwwwwwwwppphhk.",
      "..khpppwwwwwkwwkkwwkwwwwwppphk..",
      "..khhwwwwwwwwkkwwkkwwwwwwwwhhk..",
      "...khhwwwwwwwwwwwwwwwwwwwwhhk...",
      "...khhwwwwwwwwwwwwwwwwwwwwhhk...",
      "....khwwwwwwwwwwwwwwwwwwwwhk....",
      ".....kwwwwwwwwwwwwwwwwwwwwk.....",
      "......kwwwwwwwwwwwwwwwwwwk......",
      ".......kwwwwwwwwwwwwwwwwk.......",
      ".........kwwwwwwwwwwwwk.........",
      "............kkkkkkkk............",
      "................................",
    ],
  },
  {
    id: "fox",
    name: "여우",
    aliases: ["fox", "여우비"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      o: "#f28c38",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      "k..............k",
      "kk............kk",
      "kok..........kok",
      "kowk........kwok",
      "kowokkkkkkkkowok",
      "kooooooooooooook",
      "kookooooooookook",
      "kookooooooookook",
      "kwwwoooooooowwwk",
      ".kwwwwoooowwwwk.",
      "..kwwwwwwwwwwk..",
      "...kwwwwwwwwk...",
      "....kwwkkwwk....",
      ".....kkkkkk.....",
      "................",
    ],
    rows32: [
      "...k........................k...",
      "..kok......................kok..",
      "..kookk..................kkook..",
      "..kooook................kooook..",
      "..koooook..............koooook..",
      "..kookoookk..........kkoookook..",
      "..kookkooookkkkkkkkkkooookkook..",
      "..kookkkkkkooooooooookkkkkkook..",
      "..kookkkooooooooooooooookkkook..",
      "..kookooooooooooooooooooookook..",
      "..kokooooooooooooooooooooookok..",
      "..kkooooooooooooooooooooooookk..",
      "..kooooooooooooooooooooooooook..",
      ".kooooooooooooooooooooooooooook.",
      ".kooooooowkoooooooooowkoooooook.",
      ".koooooookkooooooooookkoooooook.",
      "kwoooooookkooooooooookkooooooowk",
      ".kwwwoooooooooooooooooooooowwwk.",
      ".kwwwwwwoooooooooooooooowwwwwwk.",
      ".kwwpppwwoooooooooooooowwpppwwk.",
      "..kwpppwwwoooooooooooowwwpppwk..",
      "...kwwwwwwwoooooooooowwwwwwwk...",
      "....kwwwwwwwoooooooowwwwwwwk....",
      ".....kwwwwwwwoooooowwwwwwwk.....",
      "......kkwwwwwwoooowwwwwwkk......",
      "........kkkwwwwoowwwwkkk........",
      "...........kwwwkkwwwk...........",
      "............kwkkkkwk............",
      ".............kwkkwk.............",
      "..............kwwk..............",
      "...............kk...............",
      "................................",
    ],
  },
  {
    id: "lion",
    name: "사자",
    aliases: ["lion", "라이언"],
    palette: {
      k: "#2b2b2b",
      w: "#fff1d0",
      m: "#c8702a",
      f: "#ffc94d",
      p: "#ff9eb1",
      b: "#8b5a2b",
    },
    rows: [
      "...kk.kkkk.kk...",
      "..kmmkmmmmkmmk..",
      ".kmmmmmmmmmmmmk.",
      "kmmmmmmmmmmmmmmk",
      "kmmmffffffffmmmk",
      "kmmffffffffffmmk",
      "kmmfkffffffkfmmk",
      "kmmfkffffffkfmmk",
      "kmmpffffffffpmmk",
      "kmmffwwkkwwffmmk",
      "kmmfwwkwwkwwfmmk",
      "kmmffwwwwwwffmmk",
      ".kmmffffffffmmk.",
      "..kmmmmmmmmmmk..",
      "...kmmkmmkmmk...",
      "....kk.kk.kk....",
    ],
    rows32: [
      "...........kkkk..kkkk...........",
      "..........kmmmmkkmmmmk..........",
      ".........kmmmmmmmmmmmmk.........",
      "......kkkmmmmmmmmmmmmmmkkk......",
      ".....kmmmmmmmmmmmmmmmmmmmmk.....",
      "....kmmkkkkmmmmmmmmmmkkkkmmk....",
      "...kmmkffffkmmmmmmmmkffffkmmk...",
      "...kmkffffffkkkkkkkkffffffkmk...",
      "...kmkfffffkkffffffkkfffffkmk...",
      "..kmmkfffkkffffffffffkkfffkmmk..",
      ".kmmmmkfkffffffffffffffkfkmmmmk.",
      "kmmmmmmkffffffffffffffffkmmmmmmk",
      "kmmmmmmkffffffffffffffffkmmmmmmk",
      "kmmmmmkffffffffffffffffffkmmmmmk",
      "kmmmmmkffffwkffffffwkffffkmmmmmk",
      ".kmmmmkffffkkffffffkkffffkmmmmk.",
      ".kmmmmkffffkkffffffkkffffkmmmmk.",
      "kmmmmmkffffffffffffffffffkmmmmmk",
      "kmmmmmkffffffffffffffffffkmmmmmk",
      "kmmmmmkfpppffwbbbbwffpppfkmmmmmk",
      "kmmmmmkfpppfwwwbbwwwfpppfkmmmmmk",
      ".kmmmmmkfffwwwwkkwwwwfffkmmmmmk.",
      "..kmmmmkffffwkkwwkkwffffkmmmmk..",
      "...kmmmmkffffwwffwwffffkmmmmk...",
      "...kmmmmmkkffffffffffkkmmmmmk...",
      "...kmmmmmmmkkffffffkkmmmmmmmk...",
      "....kmmmmmmmmkkkkkkmmmmmmmmk....",
      ".....kmmmmmmmmmmmmmmmmmmmmk.....",
      "......kkkmmmmmmmmmmmmmmkkk......",
      ".........kmmmmmmmmmmmmk.........",
      "..........kmmmmkkmmmmk..........",
      "...........kkkk..kkkk...........",
    ],
  },
  {
    id: "koala",
    name: "코알라",
    aliases: ["koala"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      g: "#a8b0b8",
      l: "#d7dde3",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      ".kkk........kkk.",
      "kgggk......kgggk",
      "kglgkkkkkkkkglgk",
      "kggggggggggggggk",
      ".kggggggggggggk.",
      ".kggkggggggkggk.",
      ".kggkggggggkggk.",
      ".kgggkkkkkkgggk.",
      ".kgggkkkkkkgggk.",
      ".kggggkkkkggggk.",
      ".kggggggggggggk.",
      "..kggggggggggk..",
      "...kkkkkkkkkk...",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      ".....k....................k.....",
      "..kkkgkkk..............kkkgkkk..",
      ".kgggggggk............kgggggggk.",
      "kgggggggggk.kkkkkkkk.kgggggggggk",
      "kgggglggggkkggggggggkkgggglggggk",
      "ggglllllkkggggggggggggkklllllggg",
      "gggllllkggggggggggggggggkllllggg",
      "ggllllkggggggggggggggggggkllllgg",
      "gggllkggggggggggggggggggggkllggg",
      "kgglkggggggggggggggggggggggklggk",
      "kgggkggggggggggggggggggggggkgggk",
      ".kgkggggggggggggggggggggggggkgk.",
      "..kkgggggwkggggggggggwkgggggkk..",
      "...kgggggkkggggggggggkkgggggk...",
      "...kgggggkkgggkkkkgggkkgggggk...",
      "..kggggggggggkkwkkkggggggggggk..",
      "...kgggggggggkkkkkkgggggggggk...",
      "...kgggggggggkkkkkkgggggggggk...",
      "...kgggggggggkkkkkkgggggggggk...",
      "...kgggppppggkkkkkkggppppgggk...",
      "....kggppppgggkkkkgggppppggk....",
      "....kggggggggggggggggggggggk....",
      ".....kggggggggggggggggggggk.....",
      "......kggggggggggggggggggk......",
      ".......kggggggggggggggggk.......",
      "........kkggggggggggggkk........",
      "..........kkggggggggkk..........",
      "............kkkkkkkk............",
      "................................",
    ],
  },
  {
    id: "owl",
    name: "부엉이",
    aliases: ["owl", "올빼미"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#8a5a2b",
      t: "#e8c39e",
      o: "#ff9f1c",
    },
    rows: [
      "................",
      "k..............k",
      "kk............kk",
      "kbkkkkkkkkkkkkbk",
      "kbbbbbbbbbbbbbbk",
      "kbkkkbbbbbbkkkbk",
      "kkwwwkbbbbkwwwkk",
      "kkwkwkboobkwkwkk",
      "kbkkkbboobbkkkbk",
      "kbbttttttttttbbk",
      "kbttttttttttttbk",
      "kbttttttttttttbk",
      ".kbttttttttttbk.",
      "..kkkkkkkkkkkk..",
      "...o..o..o..o...",
      "................",
    ],
    rows32: [
      "................................",
      "....k......................k....",
      "...kbk....................kbk...",
      "...kbbkk................kkbbk...",
      "...kbbbbk..kkkkkkkkkk..kbbbbk...",
      "...kbbbbbkkbbbbbbbbbbkkbbbbbk...",
      "...kbbbbkbbbbbbbbbbbbbbkbbbbk...",
      "...kbbbkbkkkkbbbbbbkkkkbkbbbk...",
      "...kbbkkkttttkkbbkkttttkkkbbk...",
      "...kbkkttttttttkkttttttttkkbk...",
      "...kkbktttkktttkktttkktttkbkk...",
      "...kbktttkkkkttttttkkkktttkbk...",
      "...kbkttkkwkkkttttkkwkkkttkbk...",
      "...kbkttkkkkkkttttkkkkkkttkbk...",
      "..kbbktttkkkkttttttkkkktttkbbk..",
      "..kbbbktttkktttkktttkktttkbbbk..",
      "..kbbbkttttttttkkttttttttkbbbk..",
      "..kbbbbkkttttkkookkttttkkbbbbk..",
      "..kbbbbbbkkkkbkookbkkkkbbbbbbk..",
      "..kbbbbbbbbbbbbkkbbbbbbbbbbbbk..",
      "..kbbbbbbbbbbttttttbbbbbbbbbbk..",
      "...kbbbbbbttttttttttttbbbbbbk...",
      "...kbbbbbttttttttttttttbbbbbk...",
      "...kbbbbbtttbtbttbtbtttbbbbbk...",
      "....kbbbtttttbttttbtttttbbbk....",
      ".....kbbbttttttttttttttbbbk.....",
      "......kbbttttttbtbtttttbbk......",
      ".......kbbttttttbtttttbbk.......",
      "........kbbbbttttttbbbbk........",
      ".........kkbbbbbbbbbbkk.........",
      "...........kkkkkkkkkk...........",
      "...........ooo....ooo...........",
    ],
  },
  {
    id: "fish",
    name: "물고기",
    aliases: ["fish", "생선", "금붕어", "바다"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#4d96ff",
      l: "#9ccaff",
    },
    rows: [
      "................",
      "................",
      "................",
      "................",
      ".....kkkkk......",
      "...kkbbblbkk..kk",
      "..kbbbbblbbbkkbk",
      ".kbwkbbblbbbbbbk",
      ".kbkkbbblbbbbbbk",
      ".kbbbbbblbbbbbbk",
      "..kbbbbblbbbkkbk",
      "...kkbbblbkk..kk",
      ".....kkkkk......",
      "................",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "................................",
      "..............k.................",
      "............kkbk................",
      "...........kbbbbk...............",
      "........kkkbbbbbbk...........k..",
      "......kkbbbbbbbbbbkk........kbk.",
      "....kkbbbbbbbbbbllbbkk.....kkbk.",
      "...kbbbbbbbbbbbbllbbbbk...kklkk.",
      "..kbbbbbbbbbbbbbllbbbbbk.kkllkk.",
      "..kbbbwwwbbbbbbbllbbbbbkkklllkk.",
      ".kbbbwwwwwbbbbbbllbbbbbbkllllkk.",
      ".kbbbwwkkwbbbbbbllbbbbbklllllkk.",
      ".kbbbwwkkwbbbbbbllbbbbkllllllkk.",
      ".kbbbbwwwbbbbbbbllbbbbkllllllkk.",
      ".kbbbbbbbbbbbbbbllbbbbbklllllkk.",
      ".kkkbbbbbbbbbbbbllbbbbbbkllllkk.",
      "..kbkkbbbbbbbbbbllbbbbbkkklllkk.",
      "..kbbbbbbbbbbbbbllbbbbbk.kkllkk.",
      "...kbbbbbbbbbbbbllbbbbk...kklkk.",
      "....kkbbbbbbbbbbllbbkk.....kkbk.",
      "......kkbbbbbbbbllkk........kbk.",
      "........kkkkkkkkkk...........k..",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "octopus",
    name: "문어",
    aliases: ["octopus", "오징어", "낙지"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#b388eb",
      r: "#ff9eb1",
    },
    rows: [
      "................",
      "....kkkkkkkk....",
      "..kkppppppppkk..",
      ".kppppppppppppk.",
      ".kppppppppppppk.",
      "kppppppppppppppk",
      "kppkppppppppkppk",
      "kppkppppppppkppk",
      "krpppppppppppprk",
      "kppppppkkppppppk",
      "kppppppppppppppk",
      "kpkpkpkppkpkpkpk",
      "kpkpkpkppkpkpkpk",
      "k.k.k.kkkk.k.k.k",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "...........kkkkkkkkkk...........",
      ".........kkppppppppppkk.........",
      "........kppppppppppppppk........",
      ".......kppppppppppppppppk.......",
      "......kppppppppppppppppppk......",
      ".....kppppppppppppppppppppk.....",
      "....kppppppppppppppppppppppk....",
      "...kppppppppppppppppppppppppk...",
      "...kppppppppppppppppppppppppk...",
      "...kppppppppppppppppppppppppk...",
      "...kppppppppppppppppppppppppk...",
      "...kppppppwkppppppppwkppppppk...",
      "...kppppppkkppppppppkkppppppk...",
      "...kppppppkkppppppppkkppppppk...",
      "...kprrrrpppppppppppppprrrrpk...",
      "...kprrrrppppkppppkpppprrrrpk...",
      "...kppppppppppkkkkppppppppppk...",
      "....kppppppppppppppppppppppk....",
      "...kppppppppppppppppppppppppk...",
      "...kppppppppppppppppppppppppk...",
      "...kppppppppppppppppppppppppk...",
      "..kpppppkppppppppppppppkpppppk..",
      "..kpppppkpppppkppkpppppkpppppk..",
      "..kpppppkpppppkkkkpppppkpppppk..",
      "..kpppppkpppppkkkkpppppkpppppk..",
      "...kppppkpppppkkkkpppppkppppk...",
      "...kppppkkppppk..kppppkkppppk...",
      "...kppppkkppppk..kppppkkppppk...",
      "....kppk.kppppk..kppppk.kppk....",
      ".....kk...kppk....kppk...kk.....",
      "...........kk......kk...........",
    ],
  },
  {
    id: "butterfly",
    name: "나비",
    aliases: ["butterfly", "나방"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#ff8fb1",
      l: "#b388eb",
      y: "#ffd93d",
    },
    rows: [
      "................",
      ".....k....k.....",
      ".kkk..k..k..kkk.",
      "kpppk..kk..kpppk",
      "kpyppk.kk.kppypk",
      "kpppppkkkkpppppk",
      "kppppppkkppppppk",
      ".kpppppkkpppppk.",
      "..kkkkkkkkkkkk..",
      ".kllllkkkkllllk.",
      "kllyllkkkkllyllk",
      "klllllkkkklllllk",
      ".kllllkkkkllllk.",
      "..kkkk.kk.kkkk..",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "............k......k............",
      ".............k....k.............",
      ".....kkkkkk..k....k..kkkkkk.....",
      "...kkppppppkk.k..k.kkppppppkk...",
      "..kppppppppppkkkkkkppppppppppk..",
      ".kppppppppppppkkkkppppppppppppk.",
      ".kppppppppppppkkkkppppppppppppk.",
      "kpppppyyyyppppkkkkppppyyyypppppk",
      "kpppppyyyypppkkkkkkpppyyyypppppk",
      "kpppppyyyypppkkkkkkpppyyyypppppk",
      "kpppppyyyypppkkkkkkpppyyyypppppk",
      "kppppppppppppkkkkkkppppppppppppk",
      "kppppppppppppkkkkkkppppppppppppk",
      ".kpppppppppppkkkkkkpppppppppppk.",
      ".kpppppppppppkkkkkkpppppppppppk.",
      "..kppppppppppkkkkkkppppppppppk..",
      "...kkpkkkkkkkkkkkkkkkkkkkkpkk...",
      ".....kllllllkkkkkkkkllllllk.....",
      "....kllllllllkkkkkkllllllllk....",
      "...klllllllllkkkkkklllllllllk...",
      "...kllllyylllkkkkkklllyyllllk...",
      "...klllyyyyllkkkkkkllyyyylllk...",
      "...klllyyyyllkkkkkkllyyyylllk...",
      "...kllllyylllkkkkkklllyyllllk...",
      "...kllllllllllkkkkllllllllllk...",
      "....kllllllllkkkkkkllllllllk....",
      ".....kllllllk.kkkk.kllllllk.....",
      "......kkkkkk...kk...kkkkkk......",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "ladybug",
    name: "무당벌레",
    aliases: ["ladybug", "벌레", "곤충"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff4d5e",
    },
    rows: [
      "................",
      ".....k....k.....",
      ".....kkkkkk.....",
      "....kwkkkkwk....",
      "..krrrkkkkrrrk..",
      ".krrrrrkkrrrrrk.",
      ".krkkrrkkrrkkrk.",
      "krrkkrrkkrrkkrrk",
      "krrrrrrkkrrrrrrk",
      "krrrkkrkkrkkrrrk",
      "krrrkkrkkrkkrrrk",
      ".krrrrrkkrrrrrk.",
      "..krrrrkkrrrrk..",
      "...kkkkkkkkkk...",
      "................",
      "................",
    ],
    rows32: [
      "..........k..........k..........",
      "...........k........k...........",
      "............kkkkkkkk............",
      "...........kkkkkkkkkk...........",
      "..........kkkkkkkkkkkk..........",
      ".........kkkkkkkkkkkkkk.........",
      "........kkkkrwrrrrwrkkkk........",
      "........kkrrrwrkkrwrrrkk........",
      ".......krrrrrrrkkrrrrrrrk.......",
      "......krrrrrrrrkkrrrrrrrrk......",
      ".....krrrrrrrrrkkrrrrrrrrrk.....",
      ".....krrrrrrrrrkkrrrrrrrrrk.....",
      "....krrrkkkrrrrkkrrrrkkkrrrk....",
      "....krrkkkkkrrrkkrrrkkkkkrrk....",
      "...krrrkkkkkrrrkkrrrkkkkkrrrk...",
      "...krrrrkkkrrrrkkrrrrkkkrrrrk...",
      "...krrrrrrrrrrrkkrrrrrrrrrrrk...",
      "...krrrrrrrrrrrkkrrrrrrrrrrrk...",
      "..krrrrrrrrrrrrkkrrrrrrrrrrrrk..",
      "...krrrrrrrrrrrkkrrrrrrrrrrrk...",
      "...krrrkkkkrrrrkkrrrrkkkkrrrk...",
      "...krrrkkkkrrrrkkrrrrkkkkrrrk...",
      "...krrrkkkkrrrrkkrrrrkkkkrrrk...",
      "....krrkkkkrrrrkkrrrrkkkkrrk....",
      "....krrrrrrrrrrkkrrrrrrrrrrk....",
      ".....krrrrrrkrrkkrrkrrrrrrk.....",
      ".....krrrrrkkkrkkrkkkrrrrrk.....",
      "......krrrrkkkrkkrkkkrrrrk......",
      ".......krrrrkrrkkrrkrrrrk.......",
      "........kkrrrrrkkrrrrrkk........",
      "..........kkrrrkkrrrkk..........",
      "............kkkkkkkk............",
    ],
  },
  {
    id: "dinosaur",
    name: "공룡",
    aliases: ["dinosaur", "티라노", "dino", "용"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      g: "#6bcb77",
      l: "#c8f0b0",
    },
    rows: [
      "................",
      ".......kkkkkk...",
      "......kggggggk..",
      "......kggkggggk.",
      "......kgggggggk.",
      "......kggggkkkk.",
      ".k....kggggk....",
      ".kk..kgggggkk...",
      ".kgkkgglllgkgk..",
      "..kgggglllgkk...",
      "..kggggllggk....",
      "...kgggggggk....",
      "....kggkkggk....",
      "....kgk..kgk....",
      "....kk...kk.....",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      ".................kkkkkkk........",
      "...............kkgggggggkk......",
      "..............kgggggggggggk.....",
      ".............kgggggggggggggk....",
      ".............kgggggggwkggggk....",
      "............kggggggggkkgggggk...",
      "............kggggggggkkgggggk...",
      "............kgggggggggggggggk...",
      ".............kgggggggggggggk....",
      ".............kgggggggggggggk....",
      "............kkggggggggkkkkkk....",
      "..........kkggggggggggggkk......",
      ".........kgggggggggggggk........",
      "........kggggggggggggggk........",
      ".......kggggggggggggggk.........",
      ".......kgggggggllllgggkkk.......",
      "......kgggggggllllllgggk.k......",
      "......kggggggllllllllggk........",
      ".....kgggggggllllllllggk........",
      "....kgggggggllllllllllgk........",
      "...kgggggggggllllllllgk.........",
      "..kggggggggggllllllllgk.........",
      "..kgggggggggggllllllgk..........",
      ".kggggkkkkgggggllllggk..........",
      "kgkkkk...kgggggggggggk..........",
      ".k.......kggggkkkggggk..........",
      ".........kggggk.kggggk..........",
      ".........kkggkk.kkggkk..........",
      "..........kkkk...kkkk...........",
      "................................",
    ],
  },
  {
    id: "turtle",
    name: "거북이",
    aliases: ["turtle", "거북"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      g: "#8fd694",
      d: "#3f8f4f",
      l: "#6bcb77",
    },
    rows: [
      "................",
      "......kkkk......",
      ".....kggggk.....",
      ".....kkggkk.....",
      "..k..kkkkkk..k..",
      ".kgkkddddddkkgk.",
      ".kgkdllddlldkgk.",
      "...kddddddddk...",
      "...kdllddlldk...",
      "...kdllddlldk...",
      ".kgkddddddddkgk.",
      ".kgkkkkkkkkkkgk.",
      "..k....kk....k..",
      "................",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      ".............kkkkkk.............",
      "............kllllllk............",
      "............kllllllk............",
      "...........kllkllkllk...........",
      "...........klkkkkkklk...........",
      "....kkkk...kkdddkddkk...kkkk....",
      "...kllllkkkdddddkddddkkkllllk...",
      "..klllllkdddddddkddddddklllllk..",
      "..kllllkddddddddkdddddddkllllk..",
      "..klllkddddddddkkddddddddklllk..",
      "..klllkddddddkkggkdddddddklllk..",
      "...klkdkkkddkgggggkkddkkkdklk...",
      "....kkddddkkggggggggkkddddkk....",
      "....kdddddkggggggggggkdddddk....",
      "....kdddddkggggggggggkdddddk....",
      "....kdddddkggggggggggkdddddk....",
      "....kdddddkggggggggggkdddddk....",
      "....kdddddkggggggggggkdddddk....",
      "....kdddddkggggggggggkdddddk....",
      "....kddddddkggggggggkddddddk....",
      ".....kddddkdkgggggkkdkddddk.....",
      "...kkkdkkkdddkkggkddddkkkdkkk...",
      "..klllkddddddddkkddddddddklllk..",
      "..klllkdddddddddkddddddddklllk..",
      "..kllllkddddddddkdddddddkllllk..",
      "..klllllkdddddddkddddddklllllk..",
      "...kklllkkkdddddkddddkkklllkk...",
      ".....kkk...kkdddkddkk...kkk.....",
      ".............kkkkkk.............",
      "...............k................",
      "................................",
    ],
  },
  {
    id: "whale",
    name: "고래",
    aliases: ["whale", "돌고래"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#5b9df0",
      c: "#9fd8ff",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      "...c..c.........",
      "....cc..........",
      ".....c.......kk.",
      "...kkkkkkk..kbbk",
      "..kbbbbbbbkkbbk.",
      ".kbbbbbbbbbbbbk.",
      "kbbbbbbbbbbbbk..",
      "kbbkbbbbbbbbbk..",
      "kbbbbbbbbbbbbk..",
      "kpbbwwwwwwbbk...",
      "kbwwwwwwwwwk....",
      ".kwwwwwwwwk.....",
      "..kkkkkkkk......",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      ".........c.....c................",
      "........c.c...c.c...............",
      "...........c.c..................",
      "............c...................",
      "............c...................",
      "............c...............kk..",
      "............c..............kbbk.",
      "..........................kbbbbk",
      "........kkkkkkkkkkkk......kbbbbk",
      "......kkbbbbbbbbbbbbkk...kbbbbk.",
      "....kkbbbbbbbbbbbbbbbbkkkbbbbbk.",
      "...kbbbbbbbbbbbbbbbbbbbbkbbbbbk.",
      "..kbbbbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbbbbbbbbbbbbbbbbbbbbbbbbbk..",
      ".kbbbbbwkbbbbbbbbbbbbbbbbbbbk...",
      ".kbbbbbkkbbbbbbbbbbbbbbbbbbbk...",
      ".kbbbbbkkbbbbbbbbbbbbbbbbbbbk...",
      ".kbbpppbbbbbbbbbbbbbbbbbbbbk....",
      ".kbbpppbbbbbbbbbbbbbbbbbbbk.....",
      ".kbbbbbbbbbbbbbbbbbbbbbbbbk.....",
      "..kwwwwwwwwwwwwwwwwwwwwwwk......",
      "..kkkwwwwwwwwwwwwwwwwwwwwk......",
      "...kwkkkwwwwwwwwwwwwwwwwk.......",
      "....kkwwwwwwwwwwwwwwwwkk........",
      "......kkwwwwwwwwwwwwkk..........",
      "........kkkkkkkkkkkk............",
      "................................",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "duck",
    name: "오리",
    aliases: ["duck", "러버덕", "고무오리", "꽥꽥이"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
      d: "#f2b82e",
      o: "#ff9a3c",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      "................",
      "....kkkk........",
      "...kyyyyk.......",
      "..kyyyyyyk......",
      "..kyykyyyk......",
      "kkkpyyyyyk....k.",
      "koooyyyyk....kyk",
      "kkkkyyyyykkkkyyk",
      ".kyyyyyyyyyyyyyk",
      ".kyyyyyddddyyyk.",
      ".kyyyyyyddyyyyk.",
      "..kyyyyyyyyyyk..",
      "...kkkkkkkkkk...",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "................................",
      "........kkkkkk..................",
      "......kkyyyyyykk................",
      ".....kyyyyyyyyyyk...............",
      ".....kyyyyyyyyyyk...............",
      "....kyyyyyyyyyyyyk..............",
      "....kyyyyywkyyyyyk..............",
      "..kkkkkyyykkyyyyyk..............",
      ".koooookyykkyyyyyk..............",
      "koooooookyyyyyyyyk...........k..",
      "koooooookyyyyyyyyk..........kyk.",
      ".kooooopppyyyyyykkkkkkk....kyyk.",
      "..kkkkkpppyyyyyyyyyyyyykk..kyyk.",
      "......kkyyyyyyyyyyyyyyyyykkyyyk.",
      "......kyyyyyyyyyykkkkyyyyyyyyyk.",
      ".....kyyyyyyyykkkddddkkkyyyyyk..",
      ".....kyyyyyyykddddddddddkyyyyk..",
      "....kyyyyyyykddddddddddddkyyyk..",
      "....kyyyyyyykddddddddddddkyyyk..",
      "....kyyyyyyykddddddddddddkyyyk..",
      "....kyyyyyyyykddddddddddkyyyyk..",
      ".....kyyyyyyyykkkddddkkkyyyyk...",
      ".....kyyyyyyyyyyykkkkyyyyyyyk...",
      "......kyyyyyyyyyyyyyyyyyyyyk....",
      ".......kkyyyyyyyyyyyyyyyykk.....",
      ".........kkyyyyyyyyyyyykk.......",
      "...........kkkkkkkkkkkk.........",
      "................................",
      "................................",
    ],
  },
  {
    id: "mouse",
    name: "쥐",
    aliases: ["생쥐", "mouse", "찍찍이"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      g: "#b8bcc6",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      ".kkkk......kkkk.",
      "kggggk....kggggk",
      "kgpppgk..kgpppgk",
      "kgpppgkkkkgpppgk",
      "kggpggggggggpggk",
      ".kggggggggggggk.",
      ".kggggggggggggk.",
      "kgggkggggggkgggk",
      "kgggkggggggkgggk",
      "kgpggggggggggpgk",
      "kggggggppggggggk",
      ".kggggggggggggk.",
      "..kggggggggggk..",
      "...kkkkkkkkkk...",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "....kkkkk..............kkkkk....",
      "..kkgggggkk..........kkgggggkk..",
      ".kgggggggggk........kgggggggggk.",
      ".kgggpppgggk........kgggpppgggk.",
      "kgggpppppgggk......kgggpppppgggk",
      "kggpppppppggk......kggpppppppggk",
      "kggpppppppggkkkkkkkkggpppppppggk",
      "kggpppppppkkggggggggkkpppppppggk",
      "kgggppppkkggggggggggggkkppppgggk",
      ".kgggppkggggggggggggggggkppgggk.",
      ".kggggkggggggggggggggggggkggggk.",
      "..kkgkggggggggggggggggggggkgkk..",
      "....kggggggggggggggggggggggk....",
      "...kggggggggggggggggggggggggk...",
      "...kggggggwkggggggggwkggggggk...",
      "...kggggggkkggggggggkkggggggk...",
      "...kggggggkkggggggggkkggggggk...",
      "..kggggggggggggggggggggggggggk..",
      "kkkkggggggggggggggggggggggggkkkk",
      "...kkkgggggggggppgggggggggkkk...",
      "...kggppppgggggppgggggppppggk...",
      "...kkkppppggggggggggggppppkkk...",
      "kkk.kggggggggggggggggggggggk.kkk",
      ".....kggggggggggggggggggggk.....",
      "......kggggggggggggggggggk......",
      ".......kggggggggggggggggk.......",
      "........kkggggggggggggkk........",
      "..........kkggggggggkk..........",
      "............kkkkkkkk............",
      "................................",
    ],
  },
  {
    id: "tiger",
    name: "호랑이",
    aliases: ["범", "tiger", "어흥"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      o: "#ff9a3c",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      ".kkk........kkk.",
      "kowok......kowok",
      "koookkkkkkkkoook",
      "kooookokkokooook",
      "kkoooookkoooookk",
      "kooooooooooooook",
      "kkookooooookookk",
      "koookooooookoook",
      "kkkowwwwwwwwokkk",
      "kkowwwwppwwwwokk",
      "koowwwkwwkwwwook",
      ".kkowwwkkwwwokk.",
      "..kooowwwwoook..",
      "...kkkkkkkkkk...",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "....kkkkkk............kkkkkk....",
      "...kooooook..........kooooook...",
      "..kooooooook........kooooooook..",
      "..kooowwoook........kooowwoook..",
      "..koowwwwookkkkkkkkkkoowwwwook..",
      "..koowwwwkkkooooooookkkwwwwook..",
      "..koowwkkooooookkooooookkwwook..",
      "..koookoooookookkookoooookoook..",
      "...kkkooooookookkookooooookkk...",
      "...koooooookoookkoookoooooook...",
      "...kooooooooooooooooooooooook...",
      "..kooooooooooooooooooooooooook..",
      ".kooooooooooooooooooooooooooook.",
      ".kooooooowkoooooooooowkoooooook.",
      ".kkkkkoookkooooooooookkoookkkkk.",
      ".koooooookkooooooooookkoooooook.",
      "kooooooooooooooooooooooooooooook",
      ".kkkkkkooooooooooooooooookkkkkk.",
      ".koooooooowwwwppppwwwwooooooook.",
      ".kooooooowwwwwwppwwwwwwoooooook.",
      ".kokkkoowwwwwwwwwwwwwwwwookkkok.",
      "..kooooowwwwkwwkkwwkwwwwoooook..",
      "...koooowwwwwkkwwkkwwwwwooook...",
      "...kooooowwwwwwwwwwwwwwoooook...",
      "....kkoooowwwwwwwwwwwwooookk....",
      "......kooooooooooooooooook......",
      ".......kkooooooooooooookk.......",
      ".........kkkooooooookkk.........",
      "............kkkkkkkk............",
      "................................",
    ],
  },
  {
    id: "monkey",
    name: "원숭이",
    aliases: ["monkey", "몽키", "우끼끼"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#a0673c",
      t: "#f0cfa8",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      ".....kkkkkk.....",
      "...kkbbbbbbkk...",
      "..kbbbbbbbbbbk..",
      ".kbbttbbbbttbbk.",
      "kkbttttbbttttbkk",
      "ktkttkttttkttktk",
      "ktkttkttttkttktk",
      "kkbttttttttttbkk",
      ".kbttttttttttbk.",
      ".kbtttkttktttbk.",
      ".kbpttttttttpbk.",
      "..kbttkkkkttbk..",
      "...kbttttttbk...",
      "....kkkkkkkk....",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "...........kkkkkkkkkk...........",
      ".........kkbbbbbbbbbbkk.........",
      "........kbbbbbbbbbbbbbbk........",
      ".......kbbbbbbbbbbbbbbbbk.......",
      "......kbbbbbbbbbbbbbbbbbbk......",
      ".....kbbbbbbbbbbbbbbbbbbbbk.....",
      "....kbbbbbbtttbbbbtttbbbbbbk....",
      "....kbbbbttttttttttttttbbbbk....",
      "...kbbbbttttttttttttttttbbbbk...",
      "..kkbbbbtttwkttttttwktttbbbbkk..",
      ".kbkbbbbtttkkttttttkktttbbbbkbk.",
      "kbbkbbbbtttkkttttttkktttbbbbkbbk",
      "bbbkbbbbttttttttttttttttbbbbkbbb",
      "bbtkbbbbttttttttttttttttbbbbktbb",
      "bbbkbbbbbttttttttttttttbbbbbkbbb",
      "kbbkbbpppttttttttttttttpppbbkbbk",
      ".kbkbbpppttttttkkttttttpppbbkbk.",
      "..kkbbbbttttttttttttttttbbbbkk..",
      "....kbbbttttttttttttttttbbbk....",
      "....kbbbttttkttttttkttttbbbk....",
      ".....kbbtttttkkkkkktttttbbk.....",
      "......kbbttttttttttttttbbk......",
      ".......kbbttttttttttttbbk.......",
      "........kbbbbttttttbbbbk........",
      ".........kkbbbbbbbbbbkk.........",
      "...........kkkkkkkkkk...........",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "sheep",
    name: "양",
    aliases: ["sheep", "어린양", "메에"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      f: "#f5d6b8",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      "...kk.kkkk.kk...",
      "..kwwkwwwwkwwk..",
      ".kwwwwwwwwwwwwk.",
      "kwwwwwwwwwwwwwwk",
      "kwwffffffffffwwk",
      "kwffffffffffffwk",
      "kwffkffffffkffwk",
      "kwffkffffffkffwk",
      ".kpffffffffffpk.",
      ".kfffffkkfffffk.",
      "..kffffffffffk..",
      "...kkkkkkkkkk...",
      "................",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      ".............kkkkkk.............",
      "............kwwwwwwk............",
      ".......kkkkkkwwwwwwkkkkkk.......",
      "......kwwwwwwwwwwwwwwwwwwk......",
      ".....kwwwwwwwwwwwwwwwwwwwwk.....",
      ".....kwwwwwwwwwwwwwwwwwwwwk.....",
      ".....kwwwwwwwwwwwwwwwwwwwwk.....",
      "....kkwwwwwwwwwwwwwwwwwwwwkk....",
      "...kwwwwwwwwkkkkkkkkwwwwwwwwk...",
      "..kwwwwwwwwkwwwwwwwwkwwwwwwwwk..",
      ".kwwwwwwwwwkwwwwwwwwkwwwwwwwwwk.",
      ".kwwwwwwwwwkwwwwwwwwkwwwwwwwwwk.",
      ".kwwwwwwwwkkwwwkkwwwkkwwwwwwwwk.",
      ".kwkkkkwwkffkkkffkkkffkwwkkkkwk.",
      "..kffffkwkffffffffffffkwkffffk..",
      ".kffffffkffffffffffffffkffffffk.",
      ".kffffffkfffwkffffwkfffkffffffk.",
      ".kkffffkkfffkkffffkkfffkkffffkk.",
      ".kwkkkkwkpppkkffffkkpppkwkkkkwk.",
      ".kwwwwwwkpppffffffffpppkwwwwwwk.",
      "..kwwwwwwkffffffffffffkwwwwwwk..",
      "...kwwwwwkffffkkkkffffkwwwwwk...",
      "....kkwwwwkffffffffffkwwwwkk....",
      ".....kwwwwwkffffffffkwwwwwk.....",
      ".....kwwwwwwkffffffkwwwwwwk.....",
      ".....kwwwwwwwkkkkkkwwwwwwwk.....",
      "......kwwwwwwwwwwwwwwwwwwk......",
      ".......kkkkkkwwwwwwkkkkkk.......",
      "............kwwwwwwk............",
      ".............kkkkkk.............",
      "................................",
    ],
  },
  {
    id: "cow",
    name: "소",
    aliases: ["젖소", "cow", "음메"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#f2d37a",
      p: "#ffc2cb",
      q: "#ffc2cb",
    },
    rows: [
      "................",
      ".kk..........kk.",
      ".kyk........kyk.",
      "..kkkkkkkkkkkk..",
      "kkkkkkwwwwwwwkkk",
      "kpkkkwwwwwwkkkpk",
      "kkkwwkwwwwkwwkkk",
      "..kwwkwwwwkwwk..",
      "..kwwwwwwwwwwk..",
      ".kppppppppppppk.",
      "kpppkppppppkpppk",
      "kppppppppppppppk",
      ".kppppppppppppk.",
      "..kkkkkkkkkkkk..",
      "................",
      "................",
    ],
    rows32: [
      ".....k....................k.....",
      "....kyk..................kyk....",
      ".....kyk................kyk.....",
      ".....kyykk............kkyyk.....",
      "......kyyykkkkkkkkkkkkyyyk......",
      "......kyyykkkkkwwwwwwkyyyk......",
      ".......kkkkkkkkwwwwwwwkkk.......",
      ".......kkkkkkkwwwwwwwwwwk.......",
      "......kwkkkkwwwwwwwwwwwwwk......",
      "..kkkkkwwwwwwwwwwwwwwwwwwkkkkk..",
      "kkwwwkwwwwwwwwwwwwwwwwwwwwkwwwkk",
      "wwwwwkwwwwwwwwwwwwwwwwwwwwkwwwww",
      "wwwwkwwwwwwwwwwwwwwwwwwwwwkkwwww",
      "wwwwkwwwwwwwkwwwwwwwwwwwwkkkwwww",
      "kkwwkwwwwwwkkwwwwwwkkwwwkkkkwwkk",
      "..kkkwwwwwwkkwwwwwwkkwwwkkkkkk..",
      "....kwwwwwwwkkkkkkkkwwwwkkkk....",
      "....kwwwwkkkqqqqqqqqkkkwkkkk....",
      ".....kwkkqqqqqqqqqqqqqqkkkk.....",
      ".....kkqqqqqqqqqqqqqqqqqqkk.....",
      ".....kqqqqqqqqqqqqqqqqqqqqk.....",
      ".....kqqqqqqqqqqqqqqqqqqqqk.....",
      "....kqqqqqqkkqqqqqqkkqqqqqqk....",
      "....kqqqqqkkkkqqqqkkkkqqqqqk....",
      "....kqqqqqqkkqqqqqqkkqqqqqqk....",
      ".....kqqqqqqqqqqqqqqqqqqqqk.....",
      ".....kqqqqqqqqqqqqqqqqqqqqk.....",
      "......kqqqqqqqqqqqqqqqqqqk......",
      ".......kkqqqqqqqqqqqqqqkk.......",
      ".........kkkqqqqqqqqkkk.........",
      "............kkkkkkkk............",
      "................................",
    ],
  },
  {
    id: "bee",
    name: "벌",
    aliases: ["꿀벌", "bee"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
      c: "#bfe6ff",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      ".kk..k....k..kk.",
      "kcck..k..k..kcck",
      "kccck.kkkk.kccck",
      "kcccckyyyykcccck",
      ".kcckyyyyyykcck.",
      "..kkyykyykyykk..",
      "..kyyykyykyyyk..",
      ".kypyyyyyyyypyk.",
      ".kkkkkkkkkkkkkk.",
      ".kyyyyyyyyyyyyk.",
      ".kkkkkkkkkkkkkk.",
      "..kyyyyyyyyyyk..",
      "...kkkkkkkkkk...",
      ".......kk.......",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "...........kk......kk...........",
      "....kkkkkk.kk......kk.kkkkkk....",
      "...kcccccck.k......k.kcccccck...",
      "..kcccccccck.k....k.kcccccccck..",
      ".kcccccccccckk....kkcccccccccck.",
      ".kcccccccccckkkkkkkkcccccccccck.",
      "kccccccccckkyykyykyykkccccccccck",
      ".kcccccckkyyyyyyyyyyyykkcccccck.",
      ".kccccckyyyyyyyyyyyyyyyykccccck.",
      "..kccckyyyyyyyyyyyyyyyyyykccck..",
      "...kckyyyyyyyyyyyyyyyyyyyykck...",
      "....kkyyyyywkyyyyyywkyyyyykk....",
      "....kyyyyyykkyyyyyykkyyyyyyk....",
      "....kyyyyyykkyyyyyykkyyyyyyk....",
      "...kyypppyyyyyyyyyyyyyypppyyk...",
      "...kyypppyyyyykyykyyyyypppyyk...",
      "...kyyyyyyyyyyykkyyyyyyyyyyyk...",
      "...kyyyyyyyyyyyyyyyyyyyyyyyyk...",
      "...kyyyyyyyyyyyyyyyyyyyyyyyyk...",
      "...kkkkkkkkkkkkkkkkkkkkkkkkkk...",
      "....kkkkkkkkkkkkkkkkkkkkkkkk....",
      "....kyyyyyyyyyyyyyyyyyyyyyyk....",
      ".....kyyyyyyyyyyyyyyyyyyyyk.....",
      ".....kyyyyyyyyyyyyyyyyyyyyk.....",
      "......kkkkkkkkkkkkkkkkkkkk......",
      ".......kkkkkkkkkkkkkkkkkk.......",
      "........kkyyyykkkyyyyykk........",
      "..........kkykkkkkyykk..........",
      "............kkkkkkkk............",
      "...............kk...............",
    ],
  },
];
