import type { DraftTemplate } from "@/types";

/** 사람·캐릭터 도안 */
export const CHARACTER_DRAFTS: DraftTemplate[] = [
  {
    id: "boy",
    name: "남자",
    aliases: ["남자아이", "소년", "boy", "사람", "친구", "아이", "나", "아빠"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      h: "#3b2a20",
      s: "#ffd7b5",
      p: "#ff9eb1",
      b: "#4d96ff",
    },
    rows: [
      "................",
      "...kkkkkkkkkk...",
      "..khhhhhhhhhhk..",
      ".khhhhhhhhhhhhk.",
      ".khhhhhhhhhhhhk.",
      "khhsssssssssshhk",
      "khsssssssssssshk",
      "khsskssssssksshk",
      "khsskssssssksshk",
      ".kspsssssssspsk.",
      ".kssssskksssssk.",
      "..kssssssssssk..",
      "...kkkkkkkkkk...",
      ".kkbbbbbbbbbbkk.",
      "kbbbbbbbbbbbbbbk",
      "kbbbbbbbbbbbbbbk",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "...........kkkkkkkkkk...........",
      ".........kkhhhhhhhhhhkk.........",
      "........khhhhhhhhhhhhhhk........",
      ".......khhhhhkkkkkkhhhhhk.......",
      "......khhhhkkhhhhhhkkhhhhk......",
      ".....khhhhkhhhhhhhhhhkhhhhk.....",
      ".....khhhkhhhhhhhhhhhhkhhhk.....",
      ".....khhkhhhhhhhhhhhhhhkhhk.....",
      "....khhkhhhhhhhhhhhhhhhhkhhk....",
      "....khhkhhsshhhhhhhhsshhkhhk....",
      "....khkshsssssssssssssshskhk....",
      "....khksssssssssssssssssskhk....",
      "....khksssssssssssssssssskhk....",
      "...kskksssswksssssswksssskksk...",
      "...kskksssskksssssskksssskksk...",
      "....kkksssskksssssskksssskkk....",
      ".....kkkpppsssssssssspppkkk.....",
      ".......kpppsssksskssspppk.......",
      "........ksssssskkssssssk........",
      ".........kssssssssssssk.........",
      "..........kssssssssssk..........",
      "...........kksssssskk...........",
      "..........kkkkkkkkkkkk..........",
      ".......kkkbbwwbbbbwwbbkkk.......",
      "......kbbbbbbbwbbwbbbbbbbk......",
      ".....kbbbbbbbbbwwbbbbbbbbbk.....",
      "....kbbbbbbbbbbbbbbbbbbbbbbk....",
      "...kbbbbbbbbbbbbbbbbbbbbbbbbk...",
      "...kbbbbbbbbbbbbbbbbbbbbbbbbk...",
    ],
  },
  {
    id: "girl",
    name: "여자",
    aliases: ["여자아이", "소녀", "girl", "엄마", "언니", "누나"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      h: "#6b3e1f",
      s: "#ffd7b5",
      p: "#ff9eb1",
      d: "#ff8fb1",
      r: "#ff4d5e",
    },
    rows: [
      "................",
      "..rkkkkkkkkkkr..",
      ".rrhhhhhhhhhhrr.",
      "..rhhhhhhhhhhr..",
      "khhhhhhhhhhhhhhk",
      "khhsssssssssshhk",
      "khsssssssssssshk",
      "khsskssssssksshk",
      "khsskssssssksshk",
      "khpssssssssssphk",
      "khssssskkssssshk",
      "khhsssssssssshhk",
      "khhkkkkkkkkkkhhk",
      "khkddddddddddkhk",
      "kkddddddddddddkk",
      "kddddddddddddddk",
    ],
    rows32: [
      "................................",
      "....k........k..................",
      "...krk.....kkrkkkkkk............",
      "...krrkkkkkrrrkhhhhhkk..........",
      "...krrrkrrkrrrkhhhhhhhkk........",
      "...krrrkrrkrrrkhhhhhhhhhk.......",
      "...krrkkkkkrrrkkkkkhhhhhhk......",
      "...krkhhhhhkkrkhhhhkkhhhhhk.....",
      "....khhhhhkhhkhhhhhhhkhhhhhk....",
      "....khhhhkhhhhhhhhhhhhkhhhhk....",
      "....khhhkhhhhhhhhhhhhhhkhhhk....",
      "...khhhhkhhhhhhhhhhhhhhkhhhhk...",
      "...khhhkhhsshhhhhhhhsshhkhhhk...",
      "...khhhkhhsssssssssssshhkhhhk...",
      "...khhhkhsssssssssssssshkhhhk...",
      "...khhhksssssssssssssssskhhhk...",
      "...khhhkssswksssssswkssskhhhk...",
      "...khhhkssskksssssskkssskhhhk...",
      "...khhhkssskksssssskkssskhhhk...",
      "...khhhkpppsssssssssspppkhhhk...",
      "...khhhhpppssssssssssppphhhhk...",
      "...khhhhksssssksskssssskhhhhk...",
      "...khhhhhkssssskkssssskhhhhhk...",
      "...khhhhhhksssssssssskhhhhhhk...",
      "...khhhhhhhkksssssskkhhhhhhhk...",
      "...khhhhhhhhkkkkkkkkhhhhhhhhk...",
      "...khhhhhkkkddddddddkkkhhhhhk...",
      "...khhhhkddddddddddddddkhhhhk...",
      "....kkkkddddddddddddddddkkkk....",
      "......kddddddddddddddddddk......",
      ".....kddddddddddddddddddddk.....",
      ".....kddddddddddddddddddddk.....",
    ],
  },
  {
    id: "ghost",
    name: "유령",
    aliases: ["ghost", "귀신", "할로윈"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      "....kkkkkkkk....",
      "...kwwwwwwwwk...",
      "..kwwwwwwwwwwk..",
      ".kwwwwwwwwwwwwk.",
      ".kwwkwwwwwwkwwk.",
      ".kwwkwwwwwwkwwk.",
      ".kpwwwwwwwwwwpk.",
      ".kwwwwwkkwwwwwk.",
      ".kwwwwwwwwwwwwk.",
      ".kwwwwwwwwwwwwk.",
      ".kwwwwwwwwwwwwk.",
      ".kwwwwwwwwwwwwk.",
      ".kwkkwwwwwwkkwk.",
      ".kk..kkkkkk..kk.",
      "................",
    ],
    rows32: [
      "................................",
      ".............kkkkkk.............",
      "..........kkkwwwwwwkkk..........",
      ".........kwwwwwwwwwwwwk.........",
      "........kwwwwwwwwwwwwwwk........",
      ".......kwwwwwwwwwwwwwwwwk.......",
      "......kwwwwwwwwwwwwwwwwwwk......",
      ".....kwwwwwwwwwwwwwwwwwwwwk.....",
      ".....kwwwwwwwwwwwwwwwwwwwwk.....",
      ".....kwwwwwwwwwwwwwwwwwwwwk.....",
      "....kwwwwwwwwwwwwwwwwwwwwwwk....",
      "....kwwwwwwwwwwwwwwwwwwwwwwk....",
      "....kwwwwwkkkwwwwwwkkkwwwwwk....",
      "....kwwwwwkwkwwwwwwkwkwwwwwk....",
      "....kwwwwwkkkwwwwwwkkkwwwwwk....",
      "....kwwwwwkkkwwwwwwkkkwwwwwk....",
      "...kkwwwwwwwwwwwwwwwwwwwwwwkk...",
      "..kwwwwpppwwwwwwwwwwwwpppwwwwk..",
      ".kwwwwwpppwwwwwkkwwwwwpppwwwwwk.",
      ".kwwwwwwwwwwwwkkkkwwwwwwwwwwwwk.",
      "..kwwwwwwwwwwwwkkwwwwwwwwwwwwk..",
      "...kkwwwwwwwwwwwwwwwwwwwwwwkk...",
      "....kwwwwwwwwwwwwwwwwwwwwwwk....",
      "....kwwwwwwwwwwwwwwwwwwwwwwk....",
      "....kwwwwwwwwwwwwwwwwwwwwwwk....",
      "....kwwwwwwwwwwwwwwwwwwwwwwk....",
      "....kwwwwwkwwwwkwwwwwkwwwwk.....",
      ".....kwwwk.kwwk.kwwwk.kwwk......",
      "......kkk...kk...kkk...kk.......",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "snowman",
    name: "눈사람",
    aliases: ["snowman", "겨울", "눈"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      o: "#ff9f1c",
      r: "#ff4d5e",
      b: "#dbe9f7",
      p: "#ff9eb1",
    },
    rows: [
      "....kkkkkkkk....",
      "....kkkkkkkk....",
      "...kkkkkkkkkk...",
      "....kwwwwwwk....",
      "...kwkwwwwkwk...",
      "...kwwwoowwwk...",
      "...kwwwwwwwwk...",
      "..kkrrrrrrrrkk..",
      ".kwwwwrrrrwwwwk.",
      "kwwwwwwkkwwwwwwk",
      "kwwwwwwwwwwwwwwk",
      "kwwwwwwkkwwwwwwk",
      "kbwwwwwwwwwwwwbk",
      ".kbbbbbbbbbbbbk.",
      "..kkkkkkkkkkkk..",
      "................",
    ],
    rows32: [
      "..........kkkkkkkkkkkkk.........",
      "..........kkkkkkkkkkkkk.........",
      ".........kkkkkkkkkkkkkkk........",
      "........kkkrrrrrrrrrrrkkk.......",
      "........kkkkkkkkkkkkkkkkk.......",
      "........kkkkkkkkkkkkkkkkk.......",
      ".........kkkkkkkkkkkkkkk........",
      "..........kwwwwwwwwwwk..........",
      ".........kwwwwwwwwwwwwk.........",
      ".........kwwwkwwwwkwwwk.........",
      "........kwwwwkwwwwkwwwwk........",
      "........kwwwwwwwwwwwwwwk........",
      "........kwwwpwwoooopowwk........",
      ".........kwwwwwwwwwwwwk.........",
      ".........kwwwwwwwwwwwwk.........",
      "..........kkkkkkkkkkkkk.........",
      ".........krrrrrrrrrrrrrk........",
      ".........krrrrrrrrrrrrrk........",
      ".........kkkkkkkkkrrrkk.........",
      "........kwwwwwwwwkrrrkwk........",
      ".......kwwwwwwwwwkrrrkwwk.......",
      ".......kwwwwwwwwkkrrrkwwk.......",
      ".......kwwwwwwwwwwkkkwwwk.......",
      ".......kwwwwwwwwwwwwwwwwk.......",
      ".......kwwwwwwwwkwwwwwwwk.......",
      ".......kwwwwwwwwwwwwwwwwk.......",
      ".......kwwwwwwwwwwwwwwwwk.......",
      "........kwwwwwwwkwwwwbbk........",
      ".........kwwwwwwwwwwbbk.........",
      ".........kbbwwwwwwbbbbk.........",
      "..........kkbbbbbbbbkk..........",
      "............kkbbbbkk............",
    ],
  },
  {
    id: "smile",
    name: "스마일",
    aliases: ["smile", "웃음", "행복", "이모지", "기쁨"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      "................",
      "....kkkkkkkk....",
      "..kkyyyyyyyykk..",
      ".kyyyyyyyyyyyyk.",
      ".kyyyyyyyyyyyyk.",
      "kyyykyyyyyykyyyk",
      "kyyykyyyyyykyyyk",
      "kpyyyyyyyyyyyypk",
      "kyykyyyyyyyykyyk",
      "kyyykkkkkkkkyyyk",
      ".kyyyyyyyyyyyyk.",
      ".kyyyyyyyyyyyyk.",
      "..kkyyyyyyyykk..",
      "....kkkkkkkk....",
      "................",
    ],
    rows32: [
      "................................",
      "............kkkkkkkk............",
      "..........kkyyyyyyyykk..........",
      "........kkyyyyyyyyyyyykk........",
      ".......kyyyyyyyyyyyyyyyyk.......",
      "......kyyyyyyyyyyyyyyyyyyk......",
      ".....kyyyyyyyyyyyyyyyyyyyyk.....",
      "....kyyyyyyyyyyyyyyyyyyyyyyk....",
      "...kyyyyyyyyyyyyyyyyyyyyyyyyk...",
      "...kyyyyyyyyyyyyyyyyyyyyyyyyk...",
      "..kyyyyyyykkkyyyyyykkkyyyyyyyk..",
      "..kyyyyyyykwkyyyyyykwkyyyyyyyk..",
      ".kyyyyyyyykkkyyyyyykkkyyyyyyyyk.",
      ".kyyyyyyyykkkyyyyyykkkyyyyyyyyk.",
      ".kyyyyyyyykkkyyyyyykkkyyyyyyyyk.",
      ".kyyyyyyyyyyyyyyyyyyyyyyyyyyyyk.",
      ".kyyyyyyyyyyyyyyyyyyyyyyyyyyyyk.",
      ".kyyypppyyyyyyyyyyyyyyyypppyyyk.",
      ".kyypppppyyyyyyyyyyyyyypppppyyk.",
      ".kyyypppkyyyyyyyyyyyyyykpppyyyk.",
      "..kyyyyykkyyyyyyyyyyyykkyyyyyk..",
      "..kyyyyyykkyyyyyyyyyykkyyyyyyk..",
      "...kyyyyyyykkyyyyyykkyyyyyyyk...",
      "...kyyyyyyyyykkkkkkyyyyyyyyyk...",
      "....kyyyyyyyyyyyyyyyyyyyyyyk....",
      ".....kyyyyyyyyyyyyyyyyyyyyk.....",
      "......kyyyyyyyyyyyyyyyyyyk......",
      ".......kyyyyyyyyyyyyyyyyk.......",
      "........kkyyyyyyyyyyyykk........",
      "..........kkyyyyyyyykk..........",
      "............kkkkkkkk............",
      "................................",
    ],
  },
  {
    id: "robot",
    name: "로봇",
    aliases: ["robot", "로보트"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      g: "#b8bcc6",
      c: "#6fd3e8",
      r: "#ff5a6e",
      p: "#ff9eb1",
    },
    rows: [
      ".......kk.......",
      "......krrk......",
      ".......kk.......",
      ".......kk.......",
      "..kkkkkkkkkkkk..",
      "..kggggggggggk..",
      "kkkgkkkggkkkgkkk",
      "kgkgkcckkcckgkgk",
      "kgkgkcckkcckgkgk",
      "kkkgkkkggkkkgkkk",
      "..kgpggggggpgk..",
      "..kggkwkwkwkgk..",
      "..kggkkkkkkkgk..",
      "..kggggggggggk..",
      "..kkkkkkkkkkkk..",
      "................",
    ],
    rows32: [
      "..............kkkk..............",
      ".............krrrrk.............",
      ".............krrrrk.............",
      ".............krrrrk.............",
      "..............kkkk..............",
      "..............kggk..............",
      "..............kggk..............",
      ".....kkkkkkkkkkkkkkkkkkkkkk.....",
      "....kggggggggggggggggggggggk....",
      "...kggggggggggggggggggggggggk...",
      "...kggggggggggggggggggggggggk...",
      "...kggggkkkkkggggggkkkkkggggk...",
      "...kgggkccccckggggkccccckgggk...",
      ".kkkgggkcwwcckggggkccwwckgggkkk.",
      "kggkgggkcwwcckggggkccwwckgggkggk",
      "kggkgggkccccckggggkccccckgggkggk",
      "kggkgggkccccckggggkccccckgggkggk",
      "kggkgggkccccckggggkccccckgggkggk",
      "kggkgpppkkkkkggggggkkkkkpppgkggk",
      "kggkgpppggggggggggggggggpppgkggk",
      "kggkggggggggggggggggggggggggkggk",
      ".kkkgggggkkkkkkkkkkkkkkgggggkkk.",
      "...kggggkwwwkwwkwwkwwwwkggggk...",
      "...kggggkwwwkwwkwwkwwwwkggggk...",
      "...kggggkwwwkwwkwwkwwwwkggggk...",
      "...kggggkwwwkwwkwwkwwwwkggggk...",
      "...kgggggkkkkkkkkkkkkkkgggggk...",
      "...kggggggggggggggggggggggggk...",
      "....kggggggggggggggggggggggk....",
      ".....kkkkkkkkkkkkkkkkkkkkkk.....",
      "................................",
      "................................",
    ],
  },
  {
    id: "alien",
    name: "외계인",
    aliases: ["alien", "에일리언", "우주인", "ufo"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      g: "#8fe07a",
      p: "#ff9eb1",
    },
    rows: [
      "..k..........k..",
      "..kk........kk..",
      "...kk.kkkk.kk...",
      "....kkggggkk....",
      "...kggggggggk...",
      "..kggggggggggk..",
      ".kggggggggggggk.",
      ".kgkkkggggkkkgk.",
      "kggkkwkggkwkkggk",
      "kggkkkkggkkkkggk",
      "kgggkkggggkkgggk",
      ".kpggggggggggpk.",
      ".kgggggkkgggggk.",
      "..kggggggggggk..",
      "...kkggggggkk...",
      ".....kkkkkk.....",
    ],
    rows32: [
      "..kgggk..................kgggk..",
      "..kgggk..................kgggk..",
      "..kgggkk................kkgggk..",
      "...kkkgk................kgkkk...",
      ".....kggk..kkkkkkkkkk..kggk.....",
      "......kgkkkggggggggggkkkgk......",
      "......kkggggggggggggggggkk......",
      "......kggggggggggggggggggk......",
      ".....kggggggggggggggggggggk.....",
      "....kggggggggggggggggggggggk....",
      "...kggggggggggggggggggggggggk...",
      "..kggggggggggggggggggggggggggk..",
      "..kgggggkkkkggggggggkkkkgggggk..",
      "..kggggkkkkkkggggggkkkkkkggggk..",
      ".kgggggkwwkkkggggggkkkwwkgggggk.",
      ".kgggggkwwkkkggggggkkkwwkgggggk.",
      ".kgggggkkkkkkggggggkkkkkkgggggk.",
      ".kgggggkkkkkkggggggkkkkkkgggggk.",
      ".kgggggkkkkwkggggggkwkkkkgggggk.",
      ".kggggggkkkkggggggggkkkkggggggk.",
      "..kgpppggggggggggggggggggpppgk..",
      "..kgpppggggggggggggggggggpppgk..",
      "..kggggggggggggggggggggggggggk..",
      "...kgggggggggkggggkgggggggggk...",
      "....kgggggggggkkkkgggggggggk....",
      ".....kggggggggggggggggggggk.....",
      "......kggggggggggggggggggk......",
      ".......kggggggggggggggggk.......",
      "........kkkggggggggggkkk........",
      "...........kkkkkkkkkk...........",
      "................................",
      "................................",
    ],
  },
];
