import type { DraftTemplate } from "@/types";

/** 음식 도안 */
export const FOOD_DRAFTS: DraftTemplate[] = [
  {
    id: "strawberry",
    name: "딸기",
    aliases: ["strawberry", "베리"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff4d5e",
      g: "#58b368",
      y: "#ffe08a",
    },
    rows: [
      "................",
      ".......kk.......",
      "...kk.kggk.kk...",
      "..kggkggggkggk..",
      ".kkggggggggggkk.",
      "krrkkggggggkkrrk",
      "krrrrkkkkkkrrrrk",
      "krryrrrrrrrryrrk",
      "krrrrrryyrrrrrrk",
      "kryrrrrrrrrrryrk",
      ".krrrryrryrrrrk.",
      ".krrrrrrrrrrrrk.",
      "..kryrrrrrryrk..",
      "...krrrrrrrrk...",
      "....kkkkkkkk....",
      "................",
    ],
    rows32: [
      "...............kk...............",
      "..............kggk..............",
      "..............kggk..............",
      "..............kggk..............",
      "..............kggk..............",
      ".............kgkkk..............",
      "........kkkkkgggggkkkkkk........",
      ".......kggggggggggggggggk.......",
      ".......kkggggggggggggggkk.......",
      ".....kkrrkggggggggggggkrrkk.....",
      "....krrrrrkkkggggggkkkrrrrrk....",
      "...krrrrrrrrrkkkkkkrrrrrrrrrk...",
      "...krrrryrrrrryrrrrryrrrrryrk...",
      "..krrrrryrrrrryrrrrryrrrrryrrk..",
      "..krrrrrrrrrrrrrrrrrrrrrrrrrrk..",
      "..krrrrrrrrrrrrrrrrrrrrrrrrrrk..",
      "..krrryrrrryrrrrryrrrryrrrrrrk..",
      "...krryrrrryrrrrryrrrryrrrrrk...",
      "...krrrrrrrrrrrrrrrrrrrrrrrrk...",
      "....krrrrrrrrrrrrrrrrrrrrrrk....",
      ".....kkrryrrrryrrrryrrrrykk.....",
      "......krryrrrryrrrryrrrryk......",
      ".......krrrrrrrrrrrrrrrrk.......",
      ".......krrrrrrrrrrrrrrrrk.......",
      "........krrrryrrrryrrrrk........",
      ".........krrryrrrryrrrk.........",
      "..........krrrrrrrrrrk..........",
      "...........kkrrrrrrkk...........",
      ".............krrrrk.............",
      "..............kkkk..............",
      "................................",
      "................................",
    ],
  },
  {
    id: "apple",
    name: "사과",
    aliases: ["apple", "애플"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff4d5e",
      g: "#58b368",
      b: "#8a5a2b",
      h: "#ffb3bb",
    },
    rows: [
      "................",
      ".......kk.kk....",
      ".......kbkggk...",
      ".......kbkgk....",
      "..kkkkkkbkkkkk..",
      ".krrrrrrrrrrrrk.",
      "krhhrrrrrrrrrrrk",
      "krhrrrrrrrrrrrrk",
      "krrrrrrrrrrrrrrk",
      "krrrrrrrrrrrrrrk",
      "krrrrrrrrrrrrrrk",
      ".krrrrrrrrrrrrk.",
      ".krrrrrrrrrrrrk.",
      "..krrrrkkrrrrk..",
      "...kkkk..kkkk...",
      "................",
    ],
    rows32: [
      "................................",
      "...............kk...kkkkkkk.....",
      "..............kbbk.kgggggggk....",
      "..............kbbkkgggggggk.....",
      "..............kbbkgggggggk......",
      "..............kbkggggggggk......",
      ".........kkkkkkbbkkkkkkkk.......",
      ".......kkrrrrrkbbkrrrrrkk.......",
      ".....kkrrrrrrrkbbkrrrrrrrkk.....",
      "....krrrrrrrrrrkkrrrrrrrrrrk....",
      "....krrrrrrrrrrrrrrrrrrrrrrk....",
      "...krrrhhrrrrrrrrrrrrrrrrrrrk...",
      "..krrrhhhhrrrrrrrrrrrrrrrrrrrk..",
      "..krrrhhhhrrrrrrrrrrrrrrrrrrrk..",
      ".krrrrhhhhrrrrrrrrrrrrrrrrrrrrk.",
      ".krrrrhhhhrrrrrrrrrrrrrrrrrrrrk.",
      ".krrrrrhhrrrrrrrrrrrrrrrrrrrrrk.",
      ".krrrrrrrrrrrrrrrrrrrrrrrrrrrrk.",
      ".krrrrrrrrrrrrrrrrrrrrrrrrrrrrk.",
      ".krrrrrrrrrrrrrrrrrrrrrrrrrrrrk.",
      ".krrrrrrrrrrrrrrrrrrrrrrrrrrrrk.",
      ".krrrrrrrrrrrrrrrrrrrrrrrrrrrrk.",
      "..krrrrrrrrrrrrrrrrrrrrrrrrrrk..",
      "..krrrrrrrrrrrrrrrrrrrrrrrrrrk..",
      "...krrrrrrrrrrrrrrrrrrrrrrrrk...",
      "....krrrrrrrrrrrrrrrrrrrrrrk....",
      "....krrrrrrrrrrrrrrrrrrrrrrk....",
      ".....kkrrrrrrrrrrrrrrrrrrkk.....",
      ".......kkrrrrrrrrrrrrrrkk.......",
      ".........kkkrrrrrrrrkkk.........",
      "............kkkkkkkk............",
      "................................",
    ],
  },
  {
    id: "watermelon",
    name: "수박",
    aliases: ["watermelon", "여름"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a6e",
      g: "#3fa34d",
      l: "#bdf0a8",
    },
    rows: [
      "................",
      "................",
      "................",
      "kkkkkkkkkkkkkkkk",
      "krrrrrrrrrrrrrrk",
      "krrkrrrrrrrrkrrk",
      ".krrrrrkrrrrrrk.",
      ".krrrrrrrrkrrrk.",
      "..krrkrrrrrrrk..",
      "..llrrrrrrrrll..",
      "...kllllllllk...",
      "....kggggggk....",
      ".....kkkkkk.....",
      "................",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
      "kgllrrrrrrrrrrrrrrrrrrrrrrrrllgk",
      "kgllrrrrrrrrrrrrrrrrrrrrrrrrllgk",
      "kgllrrrrrrrrrrrrrrrrrrrrrrrrllgk",
      "kgglrrrrkrrrrrrrrrrrrrrrkrrrlggk",
      ".kgllrrrkrrrrrrrrrrrrrrrkrrllgk.",
      ".kgglrrrrrrrrkrrrrrkrrrrrrrlggk.",
      ".kggllrrrrrrrkrrrrrkrrrrrrllggk.",
      "..kggllrrrrrrrrrrrrrrrrrrllggk..",
      "...kggllrrrkrrrrrrrrrkrrllggk...",
      "....kggllrrkrrrrrrrrrkrllggk....",
      ".....kgglllrrrrrkrrrrlllggk.....",
      "......kgggllllllklllllgggk......",
      ".......kggggllllllllggggk.......",
      "........kkkgggkgggkggkkk........",
      "...........kkkkkkkkkk...........",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "icecream",
    name: "아이스크림",
    aliases: ["ice cream", "콘", "아이스크림콘"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#ffb3c6",
      c: "#e2a86a",
      d: "#b8773a",
      r: "#ff4d5e",
    },
    rows: [
      "......kkkk......",
      ".....krrrrk.....",
      "....kkkkkkkk....",
      "...kppppppppk...",
      "..kppppppppppk..",
      "..kpwppppppwpk..",
      ".kppppppppppppk.",
      ".kppppppppppppk.",
      "kkkkkkkkkkkkkkkk",
      ".kcdcdcddcdcdck.",
      "..kcdcdccdcdck..",
      "...kcdcddcdck...",
      "....kcdccdck....",
      ".....kcddck.....",
      "......kcck......",
      ".......kk.......",
    ],
    rows32: [
      "..............krrk..............",
      ".............krwrrk.............",
      "...........kkkrrrrkkk...........",
      "..........kppkrrrrkppk..........",
      ".........kppppkrrkppppk.........",
      "........kppppppkkppppppk........",
      ".......kpppwwpppppppppppk.......",
      ".......kpppwwpppppppppppk.......",
      "......kppppwwppppppppppppk......",
      "......kppppwwppppppppppppk......",
      "......kppppppppppppppppppk......",
      "......kppppppppppppppppppk......",
      "......kppppppppppppppppppk......",
      "......kppppppppppppppppppk......",
      ".....kppppppppppppppppppppk.....",
      ".....kppppppppppppppppppppk.....",
      ".....kppppppppppppppppppppk.....",
      ".....kppppppppppppppppppppk.....",
      "......kkpkkppppppppppkkpkk......",
      "........kdckkppppppkkdck........",
      ".........kccdkkkkkkcdck.........",
      ".........kcdcdcdcdcdcdk.........",
      "..........kcccdcccdcck..........",
      "..........kdcdcdcdcdck..........",
      "...........kdcccdccck...........",
      "............kdcdcdck............",
      "............kcdcccdk............",
      ".............kcdcdk.............",
      ".............kccdck.............",
      "..............kdck..............",
      "..............kcck..............",
      "...............kk...............",
    ],
  },
  {
    id: "cake",
    name: "케이크",
    aliases: ["cake", "생일케이크", "생일"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      c: "#fff3e0",
      p: "#ffb3c6",
      b: "#c98a4b",
      r: "#ff4d5e",
      y: "#ffd93d",
    },
    rows: [
      "................",
      ".......yy.......",
      ".......kk.......",
      ".......kk.......",
      "....kkkkkkkk....",
      "...kppppppppk...",
      "..kppppppppppk..",
      "..kpkpkppkpkpk..",
      "..kcccccccccck..",
      "..kcccccccccck..",
      "..kbbbbbbbbbbk..",
      "..kbbbbbbbbbbk..",
      "..kcccccccccck..",
      "..kbbbbbbbbbbk..",
      "..kkkkkkkkkkkk..",
      "................",
    ],
    rows32: [
      "..............krrk..............",
      "..............krrk..............",
      ".............krryrk.............",
      "..............kyrk..............",
      "..............krrk..............",
      "..............kkkk..............",
      "..............kyyk..............",
      "..............kryk..............",
      "......kk......kyrk......kk......",
      ".....krrk.....kryk.....krrk.....",
      "....krrrrk....kyrk....krrrrk....",
      "...kkkrrkkkkkkkyykkkkkkkrrkkk...",
      "..kpppkkpppppppkkpppppppkkpppk..",
      "..kppppppppppppppppppppppppppk..",
      "..kppppppppppppppppppppppppppk..",
      "..kppppppppppppppppppppppppppk..",
      "..kkppppkkppppppppppppkkppppkk..",
      "..kckppkckppppppppppppkckppkck..",
      "..kcckkccckppkkkkkkppkccckkcck..",
      "..kcccccccckkcccccckkcccccccck..",
      "..kbbbbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbbbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbbbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kcccccccccccccccccccccccccck..",
      "..kcccccccccccccccccccccccccck..",
      "..kcccccccccccccccccccccccccck..",
      "..kcccccccccccccccccccccccccck..",
      "..kcccccccccccccccccccccccccck..",
      "..kcccccccccccccccccccccccccck..",
      "...kkkkkkkkkkkkkkkkkkkkkkkkkk...",
      "................................",
      "................................",
    ],
  },
  {
    id: "donut",
    name: "도넛",
    aliases: ["donut", "도너츠"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#e2a86a",
      p: "#ff8fb1",
      y: "#ffd93d",
      l: "#7ec8e3",
    },
    rows: [
      "................",
      "................",
      "....kkkkkkkk....",
      "..kkppppppppkk..",
      ".kppyppppppyppk.",
      ".kpppplpplppppk.",
      "kplpppppppppplpk",
      "kppppkkkkkkppppk",
      "kpypk......kpypk",
      "kbppk......kppbk",
      "kbbppkkkkkkppbbk",
      ".kbbppppppppbbk.",
      ".kbbbbbbbbbbbbk.",
      "..kkbbbbbbbbkk..",
      "....kkkkkkkk....",
      "................",
    ],
    rows32: [
      "................................",
      "............kkkkkkkk............",
      "..........kkbbbbbbbbkk..........",
      "........kkbbbppppppbbbkk........",
      ".......kbbppppppppppppbbk.......",
      "......kbbppppppppppppppbbk......",
      ".....kbbpppppppwwpppppppbbk.....",
      "....kbbppppppppppppppllppbbk....",
      "...kbbpppyypppppppppppppppbbk...",
      "...kbppppppppppppppppppppppbk...",
      "..kbbppppppppppppppppppppppbbk..",
      "..kbbpppppppppkkkkpppppppppbbk..",
      ".kbbpppppppppkbbbbkpppppppppbbk.",
      ".kbbppppppppkb....bkppppppppbbk.",
      ".kbbpppppppkb......bkppppyypbbk.",
      ".kbbppllpppkb......bkpppppppbbk.",
      ".kbppppppppkb......bkppppppppbk.",
      ".kbppppppppkb......bkppppppppbk.",
      ".kbbppppppppkb....bkppppppppbbk.",
      ".kbbbppppppppkbbbbkppppppppbbbk.",
      "..kbbpppppppppkkkkppppppppwwbk..",
      "..kbbbppppppppppppppppppppbbbk..",
      "...kbpppppyypppppppppppppppbk...",
      "...kbppppppppppppppppllppppbk...",
      "....kbppppppppppppppppppppbk....",
      ".....kbbbbppppppppppppbbbbk.....",
      "......kbbbbppppppppppbbbbk......",
      ".......kbbbppppbbppppbbbk.......",
      "........kkbbppbbbbppbbkk........",
      "..........kkbbbbbbbbkk..........",
      "............kkkkkkkk............",
      "................................",
    ],
  },
  {
    id: "burger",
    name: "햄버거",
    aliases: ["burger", "hamburger", "버거", "패스트푸드"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#e2a86a",
      g: "#6bcb77",
      y: "#ffd93d",
      d: "#6b3e1f",
    },
    rows: [
      "................",
      "................",
      "................",
      "....kkkkkkkk....",
      "..kkbbbbbbbbkk..",
      ".kbbwbbbbbbwbbk.",
      "kbbbbbbbbbbbbbbk",
      "kkkkkkkkkkkkkkkk",
      "kggggggggggggggk",
      "kyyyyyyyyyyyyyyk",
      "kddddddddddddddk",
      "kddddddddddddddk",
      "kkkkkkkkkkkkkkkk",
      "kbbbbbbbbbbbbbbk",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "............kkkkkkkk............",
      ".........kkkbbbbbbbbkkk.........",
      ".......kkbbbbbbbbbbbbbbkk.......",
      ".....kkbbbbbbbbbwbbbbbbbbkk.....",
      "....kbbbbbbbbbbwbbbbbbbbbbbk....",
      "...kbbbbbbwbbbbbbbbbbwbbbbbbk...",
      "..kbbbbbbwbbbbbbbbbbbbwbbbbbbk..",
      "..kbbbbbbbbbbbbbbbbbbbbbbbbbbk..",
      ".kbbbbbbbbbbbbbbbbbbbbbbbbbbbbk.",
      ".kbbbbbbbbbbwbbbbbbwbbbbbbbbbbk.",
      ".kbbbbbbbbbbbbbbbbbbbbbbbbbbbbk.",
      ".kbbbbbbbbbbbbbbbbbbbbbbbbbbbbk.",
      ".kbbbbbbbbbbbbbbbbbbbbbbbbbbbbk.",
      ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
      "kgggggggggggggggggggggggggggggk.",
      "kggggggggggggggggggggggggggggk..",
      ".kggkkggkkggkkggkkggkkggkkggkk..",
      ".kkkddkkdkkkyykkkdkkyykkykkkddk.",
      ".kddddddddkyyyykddddkyykkdddddk.",
      ".kdddddddddkyykddddddkkdddddddk.",
      ".kddddddddddkkddddddddddddddddk.",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "..kbbbbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbbbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbbbbbbbbbbbbbbbbbbbbbbbbbk..",
      "...kbbbbbbbbbbbbbbbbbbbbbbbbk...",
      "....kkkkkkkkkkkkkkkkkkkkkkkk....",
      "................................",
      "................................",
    ],
  },
  {
    id: "pizza",
    name: "피자",
    aliases: ["pizza", "치즈"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      c: "#e2a86a",
      y: "#ffd93d",
      r: "#ff4d5e",
      g: "#58b368",
    },
    rows: [
      "................",
      "................",
      "kkkkkkkkkkkkkkkk",
      "kcccccccccccccck",
      "kyyyyyyyyyyyyyyk",
      ".kyrryyyyyyrryk.",
      ".kyrryyyyyyrryk.",
      "..kyyyrrrryyyk..",
      "..kyyyrrrryyyk..",
      "...kyyyyyyyyk...",
      "...kyyyyyyyyk...",
      "....kyyyyyyk....",
      "....kyyyyyyk....",
      ".....kyyyyk.....",
      "......kkkk......",
      "................",
    ],
    rows32: [
      "................................",
      "...kkkkkkkkkkkkkkkkkkkkkkkkkk...",
      "..kcccccccccccccccccccccccccck..",
      ".kcccccccccccccccccccccccccccck.",
      ".kcccccccccccccccccccccccccccck.",
      ".kcccccccccccccccccccccccccccck.",
      ".kcccccccccccccccccccccccccccck.",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "...kyyyykkkkyyyyyykkkkyyyyyyk...",
      "....kyykrrrrkyyyykrrrrkyyyyk....",
      "....kyykrwrrkyyyykrwrrkyyyyk....",
      ".....kykrrrrkyyyykrrrrkyyyk.....",
      ".....kykrrrrkyyyykrrrrkyyyk.....",
      "......kykkkkyyyyyykkkkyyyk......",
      "......kyyyyyyygyyyyyyyyyyk......",
      ".......kyyyyyyyyyyyyyyyyk.......",
      ".......kygyyyykkkkyyyygyk.......",
      "........kyyyykrrrrkyyyyk........",
      ".........kyyykrwrrkyyyk.........",
      ".........kyyykrrrrkyyyk.........",
      "..........kyykrrrrkyyk..........",
      "..........kyyykkkkyyyk..........",
      "...........kkkkyyyyyk...........",
      "..........krrrrkyyyyk...........",
      "..........krrrrkyyyk............",
      "..........krrrrkyygk............",
      "..........krrrrkyyk.............",
      "...........kkkkyyyk.............",
      "..............kyyk..............",
      "..............kyyk..............",
      "...............kk...............",
      "................................",
    ],
  },
  {
    id: "cherry",
    name: "체리",
    aliases: ["cherry", "앵두"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff4d5e",
      g: "#58b368",
    },
    rows: [
      "................",
      ".......gg.......",
      "......g..g......",
      ".....g....g.....",
      "....g......g....",
      "...g........g...",
      "..kkk......kkk..",
      ".krrrk....krrrk.",
      "krwrrrk..krrrwrk",
      "krrrrrk..krrrrrk",
      "krrrrrk..krrrrrk",
      ".krrrk....krrrk.",
      "..kkk......kkk..",
      "................",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "....................kkkkkkk.....",
      "...................kgggggggk....",
      "..................kgggggggk.....",
      ".................kgggggggk......",
      "................kgkkggggk.......",
      "................kgk.kkkk........",
      "...............kgkgk............",
      "...............kgkgk............",
      "..............kgkkgk............",
      "..............kgk.kgk...........",
      ".............kgk..kgk...........",
      ".............kgk..kgk...........",
      "............kgk....kgk..........",
      "............kgk....kgk..........",
      "...........kgk.....kgk..........",
      "........kkkkgk.....kgk..........",
      "......kkrrrkk.......kkkk........",
      ".....krrrrrrrk.....kkrrrkk......",
      "....krrrrrrrrrk...krrrrrrrk.....",
      "...krrwwwrrrrrrk.krrrrrrrrrk....",
      "...krrwwwrrrrrrkkrrwwwrrrrrrk...",
      "..krrrwwwrrrrrrrkrrwwwrrrrrrk...",
      "..krrrrrrrrrrrrkrrrwwwrrrrrrrk..",
      "..krrrrrrrrrrrrkrrrrrrrrrrrrrk..",
      "...krrrrrrrrrrrkrrrrrrrrrrrrrk..",
      "...krrrrrrrrrrrkkrrrrrrrrrrrk...",
      "....krrrrrrrrrk.krrrrrrrrrrrk...",
      ".....krrrrrrrk...krrrrrrrrrk....",
      "......kkrrrkk.....krrrrrrrk.....",
      "........kkk........kkrrrkk......",
      ".....................kkk........",
    ],
  },
  {
    id: "grape",
    name: "포도",
    aliases: ["grape", "청포도"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#8e5bd6",
      l: "#c3a2f0",
      b: "#8a5a2b",
      g: "#58b368",
    },
    rows: [
      ".....ggbbgg.....",
      "......gbbg......",
      "..kkkkkkkkkkkk..",
      ".kplpplpplpplpk.",
      ".kppppppppppppk.",
      ".kplpplpplpplpk.",
      "..kppppppppppk..",
      "..kplppllpplpk..",
      "...kppppppppk...",
      "...kplpppplpk...",
      "....kppppppk....",
      ".....kpllpk.....",
      "......kkkk......",
      "................",
      "................",
      "................",
    ],
    rows32: [
      "...............kk....kkk........",
      "..............kbbk.kkgggkkkk....",
      "..............kbbkkgggggggggk...",
      "..............kbbkgggggggggk....",
      "........kk....kkkkkgggkkggk.....",
      "......kkppkk.kkppkkkkkppkk......",
      ".....kppppppkppppppkppppppk.....",
      ".....kplppppkplppppkplppppk.....",
      "....kppppppkppppppkppppppppk....",
      "....kppppppkppppppkppppppppk....",
      "....kkkkpppkkkppppkkkpppkkkk....",
      "...kppppkpkpppkppkpppkpkppppk...",
      "..kplppppkpppppkkpppppkplppppk..",
      ".kppppppppkppppkplpppkppppppppk.",
      ".kppppppppkppppkpppppkppppppppk.",
      ".kppppppppkppppkpppppkppppppppk.",
      "..kppppkkkkppppkkppppkkkkppppk..",
      "...kppkppppkpkkppkkpkppppkppk...",
      "....kkplppppkppppppkplppppkk....",
      "....kpppppppkplpppkppppppppk....",
      "....kppppppkppppppkppppppppk....",
      "....kppppppkkkppppkkkppppppk....",
      ".....kppppkpppkppkpppkppppk.....",
      "......kppkpppppkkpppppkppk......",
      ".......kkplppppkplpppppkk.......",
      "........kppppppkpppppppk........",
      "........kppppppkpppppppk........",
      "........kppppppkpppppppk........",
      ".........kpppppkkpppppk.........",
      "..........kpppk..kpppk..........",
      "...........kkk....kkk...........",
      "................................",
    ],
  },
  {
    id: "coffee",
    name: "커피",
    aliases: ["coffee", "카페", "라떼", "아메리카노", "음료"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#c98a4b",
    },
    rows: [
      "................",
      "..kkkkkkkkkkkk..",
      ".kwwwwwwwwwwwwk.",
      ".kkkkkkkkkkkkkk.",
      "..kwwwwwwwwwwk..",
      "..kwwwwwwwwwwk..",
      "..kbbbbbbbbbbk..",
      "..kbbbbbbbbbbk..",
      "...kbbbbbbbbk...",
      "...kwwwwwwwwk...",
      "...kwwwwwwwwk...",
      "....kwwwwwwk....",
      "....kkkkkkkk....",
      "................",
      "................",
      "................",
    ],
    rows32: [
      "..........kkkkkkkkkkkk..........",
      ".........kwwwwwwwwwwwwk.........",
      ".........kwwwwwwwwwwwwk.........",
      "......kkkkwwwwwwwwwwwwkkkk......",
      ".....kwwwwkkkkkkkkkkkkwwwwk.....",
      "....kwwwwwwwwwwwwwwwwwwwwwwk....",
      "....kwwwwwwwwwwwwwwwwwwwwwwk....",
      "....kwwwwwwwwwwwwwwwwwwwwwwk....",
      ".....kkkkkkkkkkkkkkkkkkkkkk.....",
      "......kwwwwwwwwwwwwwwwwwwk......",
      "......kwwwwwwwwwwwwwwwwwwk......",
      "......kwwwwwwwwwwwwwwwwwwk......",
      ".......kwwwwwwwwwwwwwwwwk.......",
      ".......kkkkkkkkkkkkkkkkkk.......",
      ".......kbbbbbbbbbbbbbbbbk.......",
      ".......kbbbbbbbbbbbbbbbbk.......",
      ".......kbbbbbbbbbbbbbbbbk.......",
      ".......kbbbbbkbbbbkbbbbbk.......",
      ".......kbbbbbkbbbbkbbbbbk.......",
      ".......kbbbbbbbkkbbbbbbbk.......",
      ".......kbbbbbbbkkbbbbbbbk.......",
      "........kbbbbbbbbbbbbbbk........",
      "........kkkkkkkkkkkkkkkk........",
      "........kwwwwwwwwwwwwwwk........",
      "........kwwwwwwwwwwwwwwk........",
      "........kwwwwwwwwwwwwwwk........",
      "........kwwwwwwwwwwwwwwk........",
      "........kwwwwwwwwwwwwwwk........",
      "........kwwwwwwwwwwwwwwk........",
      "........kwwwwwwwwwwwwwwk........",
      ".........kkkkkkkkkkkkkk.........",
      "................................",
    ],
  },
  {
    id: "cookie",
    name: "쿠키",
    aliases: ["cookie", "과자", "비스킷"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      c: "#d9a066",
      d: "#6b3e1f",
    },
    rows: [
      "................",
      "................",
      "....kkkkkkkk....",
      "..kkcccccccckk..",
      ".kccdccccccdcck.",
      ".kcccccddccccck.",
      "kcccccccccccccck",
      "kcdccccccccccdck",
      "kccccdccccdcccck",
      "kcccccccccccccck",
      "kcccdccccccdccck",
      ".kcccccccccccck.",
      ".kccdccccccdcck.",
      "..kkcccccccckk..",
      "....kkkkkkkk....",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "...........kkkkkkkkkk...........",
      ".........kkcccccccccckk.........",
      "........kcccccccccccccck........",
      "......kkcccccccccccccccck.......",
      ".....kcccccccccccccccccck.......",
      ".....kcccccccccccddccccck.......",
      "....kcccccddcccccdcccccck.......",
      "...kccccccdcccccccccccccckkk....",
      "...kcccccccccccccccccddccccck...",
      "..kccccccccccccccccccdccccccck..",
      "..kcccccccccccccccccccccccccck..",
      "..kccccccccccccddcccccccccccck..",
      "..kccccccccccccdccccccccccccck..",
      "..kcccccddccccccccccccddccccck..",
      "..kcccccdcccccccccccccdcccccck..",
      "..kcccccccccccccccccccccccccck..",
      "..kcccccccccccccccccccccccccck..",
      "..kcccccccccccccccccccccccccck..",
      "..kcccccccccccccccddccccccccck..",
      "...kcccccccddcccccdccccccccck...",
      "...kcccccccdccccccccccccddcck...",
      "....kcccccccccccccccccccdcck....",
      ".....kcccccccccccccccccccck.....",
      ".....kcccccccccccccccccccck.....",
      "......kkcccccccddccccccckk......",
      "........kccccccdccccccck........",
      ".........kkcccccccccckk.........",
      "...........kkkkkkkkkk...........",
      "................................",
      "................................",
    ],
  },
  {
    id: "candy",
    name: "사탕",
    aliases: ["candy", "캔디", "막대사탕"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#ff8fb1",
      y: "#ffd93d",
    },
    rows: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "kk...kkkkkk...kk",
      "kpk.kyyppyyk.kpk",
      "kppkpyyppyypkppk",
      "kppkppyyyyppkppk",
      "kpk.kpyyyypk.kpk",
      "kk...kkkkkk...kk",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "............kkkkkkkk............",
      "...........kpyyyppyyk...........",
      "..k.......kyppyyyppyyk.......k..",
      ".kpk.....kyyppyyyppyyyk.....kpk.",
      ".kppk...kpyyywpyyyppyyyk...kppk.",
      ".kpppk.kyppywyppyyyppyyyk.kpppk.",
      ".kppppkkyppyyyppyyyppyyykkppppk.",
      ".kpppppkyyppyyyppyyyppyykpppppk.",
      ".kpppppkyyppyyyppyyyppyykpppppk.",
      ".kpppppkyyyppyyyppyyyppykpppppk.",
      ".kpppppkpyyyppyyyppyyyppkpppppk.",
      ".kppppkkpyyyppyyyppyyyppkkppppk.",
      ".kpppk.kppyyyppyyyppyyypk.kpppk.",
      ".kppk...kpyyyppyyyppyyyk...kppk.",
      ".kpk.....kpyyyppyyyppyk.....kpk.",
      "..k.......kpyyyppyyypk.......k..",
      "...........kyyyppyyyk...........",
      "............kkkkkkkk............",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "pudding",
    name: "푸딩",
    aliases: ["pudding", "푸린", "젤리", "디저트"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffe08a",
      d: "#9c6334",
      p: "#ff9eb1",
      q: "#ff4d5e",
    },
    rows: [
      "................",
      "................",
      "................",
      "....kkkkkkkk....",
      "...kddddddddk...",
      "..kddddddddddk..",
      "..kyyyyyyyyyyk..",
      ".kyyyyyyyyyyyyk.",
      ".kyyykyyyykyyyk.",
      ".kpyyyyyyyyyypk.",
      "kyyyyyykkyyyyyyk",
      "kyyyyyyyyyyyyyyk",
      "kkkkkkkkkkkkkkkk",
      ".kwwwwwwwwwwwwk.",
      "kkkkkkkkkkkkkkkk",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "..............kkkk..............",
      ".............kqqqqk.............",
      ".............kqqqqk.............",
      ".............kqqqqk.............",
      "..........kkkkqqqqkkkk..........",
      "........kkddddkkkkddddkk........",
      ".......kddddddddddddddddk.......",
      ".......kddddddddddddddddk.......",
      ".......kddddddddddddddddk.......",
      ".......kddddddddddddddddk.......",
      "......kyddddyyddddyyddddyk......",
      "......kyyddyyyddddyyyddyyk......",
      "......kyyyyyyyyddyyyyyyyyk......",
      "......kyyyyyyyyyyyyyyyyyyk......",
      "......kyyyyyyyyyyyyyyyyyyk......",
      "......kyyyyyyyyyyyyyyyyyyk......",
      ".....kyyyyywkyyyyyywkyyyyyk.....",
      ".....kyyyyykkyyyyyykkyyyyyk.....",
      ".....kyypppyyyyyyyyyypppyyk.....",
      ".....kyypppyyykyykyyypppyyk.....",
      ".....kyyyyyyyyykkyyyyyyyyyk.....",
      ".....kyyyyyyyyyyyyyyyyyyyyk.....",
      "....kyyyyyyyyyyyyyyyyyyyyyyk....",
      "...kkyyyyyyyyyyyyyyyyyyyyyykk...",
      "..kwkyyyyyyyyyyyyyyyyyyyyyykwk..",
      ".kwwwkkkkkkkkkkkkkkkkkkkkkkwwwk.",
      "..kwwwwwwwwwwwwwwwwwwwwwwwwwwk..",
      "...kkkwwwwwwwwwwwwwwwwwwwwkkk...",
      "......kkkkkkkkkkkkkkkkkkkk......",
      "................................",
    ],
  },
  {
    id: "riceball",
    name: "주먹밥",
    aliases: ["onigiri", "삼각김밥", "김밥", "밥"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      n: "#2f4f3a",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      "................",
      "......kkkk......",
      ".....kwwwwk.....",
      "....kwwwwwwk....",
      "....kwwwwwwk....",
      "...kwkwwwwkwk...",
      "...kwwwwwwwwk...",
      "..kpwwwwwwwwpk..",
      "..kwwnnnnnnwwk..",
      ".kwwwnnnnnnwwwk.",
      ".kwwwnnnnnnwwwk.",
      ".kkkkkkkkkkkkkk.",
      "................",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "..............kkkk..............",
      ".............kwwwwk.............",
      "............kwwwwwwk............",
      "...........kwwwwwwwwk...........",
      "...........kwwwwwwwwk...........",
      "...........kwwwwwwwwk...........",
      "...........kwwwwwwwwk...........",
      "...........kwwwwwwwwk...........",
      "...........kwwwwwwwwk...........",
      "..........kwwwwwwwwwwk..........",
      ".........kwwwwwwwwwwwwk.........",
      ".........kwwwwwwwwwwwwk.........",
      "........kwwwwwwwwwwwwwwk........",
      "........kwwwkwwwwwwwkwwk........",
      ".......kwwwkkwwwwwwkkwwwk.......",
      "......kpppwwwwwwwwwwwwpppk......",
      "......kpppwwwwkwwkwwwwpppk......",
      ".....kwwwwwwwwwkkwwwwwwwwwk.....",
      ".....kwwwwwwwwwwwwwwwwwwwwk.....",
      "....kwwwwwkkkkkkkkkkkkwwwwwk....",
      "...kwwwwwknnnnnnnnnnnnkwwwwwk...",
      "..kwwwwwwknnnnnnnnnnnnkwwwwwwk..",
      ".kwwwwwwwknnnnnnnnnnnnkwwwwwwwk.",
      ".kwwwwwwwknnnnnnnnnnnnkwwwwwwwk.",
      ".kwwwwwwwknnnnnnnnnnnnkwwwwwwwk.",
      ".kwwwwwwwknnnnnnnnnnnnkwwwwwwwk.",
      "..kwwwwwwknnnnnnnnnnnnkwwwwwwk..",
      "...kwwwwwknnnnnnnnnnnnkwwwwwk...",
      "....kkkkkknnnnnnnnnnnnkkkkkk....",
      "..........kkkkkkkkkkkk..........",
      "................................",
    ],
  },
  {
    id: "banana",
    name: "바나나",
    aliases: ["banana"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
      d: "#f2b82e",
      b: "#8b5a2b",
    },
    rows: [
      "................",
      "................",
      "..............k.",
      ".............kbk",
      "k............kyk",
      "kbk.........kyyk",
      "kyyk.......kyyyk",
      "kyyyk....kkyyyyk",
      ".kyyykkkkyyyyyk.",
      ".kdyyyyyyyyyydk.",
      "..kddyyyyyyddk..",
      "...kkddddddkk...",
      ".....kkkkkk.....",
      "................",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "................................",
      "............................kk..",
      "...........................kbbk.",
      "...........................kbbk.",
      "...........................kbbk.",
      "...........................kbbk.",
      "............................kk..",
      ".............................k..",
      "............................kyk.",
      "...........................kyyk.",
      ".k........................kyyyk.",
      "kbkk....................kkyyyyk.",
      "kbbykk................kkyyyyyyk.",
      "kbbyyykkk..........kkkyyyyyyydk.",
      "kbbyyyyyykkkkkkkkkkyyyyyyyyyddk.",
      "kbbdyyyyyyyyyyyyyyyyyyyyyyyddk..",
      ".kbdddyyyyyyyyyyyyyyyyyyydddk...",
      "..kkdddyyyyyyyyyyyyyyyyyddkk....",
      "....kdddddyyyyyyyyyyyddddk......",
      ".....kkddddddddydddddddkk.......",
      ".......kkkkddddddddkkkk.........",
      "...........kkkkkkkk.............",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "peach",
    name: "복숭아",
    aliases: ["peach", "복숭"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#ffb3b8",
      r: "#ff8a95",
      g: "#6cc46c",
      b: "#8b5a2b",
    },
    rows: [
      "................",
      "..........kkk...",
      ".........kgggk..",
      "........kggkk...",
      "...kkkk.kkkkk...",
      "..kppppkkpppppk.",
      ".kpwpppkpppppppk",
      ".kpwppppkppppppk",
      "kppppppkpppppppk",
      "kppppppkppppprpk",
      "kppppppkpppprrpk",
      "kpppppppkpprrrpk",
      ".kppppppkprrrrk.",
      "..kkppppprrrkk..",
      "....kkkkkkkk....",
      "................",
    ],
    rows32: [
      ".....................kkkk.......",
      "..................kkkggggk......",
      ".................kggggggk.......",
      "...............kkgggggggk.......",
      "..............kbbkggggggk.......",
      "..............kbbkgggggk........",
      "..............kbbkgggkk.........",
      "........kkkkkkkbbkkkkkkk........",
      "......kkppppppkbbkppppppkk......",
      ".....kpppppppppkkpppppppppk.....",
      "....kppppppppppprppppppppppk....",
      "...kppppppppppprppppppppppppk...",
      "..kppppwwpppppprpppppppppppppk..",
      "..kpppwwwwpppprppppppppppppppk..",
      ".kppppwwwwpppprpppppppppppppppk.",
      ".kpppppwwppppprpppppppppprrpppk.",
      ".kpppppppppppprpppppppppprrrppk.",
      ".kpppppppppppprppppppppprrrrrpk.",
      ".kpppppppppppprppppppppprrrrrpk.",
      ".kppppppppppppprpppppppprrrrrrk.",
      ".kppppppppppppprppppppprrrrrrrk.",
      ".kppppppppppppprpppppprrrrrrrrk.",
      "..kpppppppppppprppppprrrrrrrrk..",
      "..kppppppppppppppppprrrrrrrrrk..",
      "...kppppppppppppprrrrrrrrrrrk...",
      "....kpppppppppprrrrrrrrrrrrk....",
      ".....kppppppppprrrrrrrrrrrk.....",
      "......kkpppppppprrrrrrrrkk......",
      "........kkppppppprrrrrkk........",
      "..........kkppppppprkk..........",
      "............kkkkkkkk............",
      "................................",
    ],
  },
  {
    id: "carrot",
    name: "당근",
    aliases: ["carrot", "당근이"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      o: "#ff9a3c",
      d: "#e07b24",
      g: "#6cc46c",
    },
    rows: [
      "................",
      ".........k.k.k..",
      "........kgkgkgk.",
      ".........kgggk..",
      "........kkkgkk..",
      ".......kooookk..",
      "......koooooook.",
      ".....koodoooook.",
      ".....koooooodk..",
      "....koooooooook.",
      "....kodoooook...",
      "...koooooodk....",
      "...koooooook....",
      "..kooodook......",
      "..koook.........",
      "..kkk...........",
    ],
    rows32: [
      "................................",
      "................................",
      "...................k......k.....",
      "..................kgk....kgk....",
      "..................kgk...kgk.....",
      "..................kggk.kggk.....",
      "..................kgggkgggk.....",
      "..................kggkgggk......",
      "..............kkkkkgkggggk......",
      ".............koooookggkkkkkkk...",
      "............koooooookkkkkggggk..",
      "...........koooooooookgggggkk...",
      "...........kooooooooookggkk.....",
      "..........koooooooooookkk.......",
      "..........koooooooooook.........",
      ".........kooooooooooook.........",
      ".........kooddooooooook.........",
      "........koooooddoooook..........",
      "........koooooooooook...........",
      ".......koooooooodook............",
      ".......koddoooooodk.............",
      "......kooooddoookkd.............",
      "......kooooooook................",
      ".....koooooookk.................",
      ".....koooookk...................",
      "....koodddk.....................",
      "....koookk......................",
      "...koook........................",
      "...kokk.........................",
      "..kok...........................",
      "...k............................",
      "................................",
    ],
  },
  {
    id: "fries",
    name: "감자튀김",
    aliases: ["감튀", "프렌치프라이", "fries", "french fries"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
      r: "#ff5a6e",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      "....k..k.k......",
      "...kyk.kykk.k...",
      "...kykkkykyk.kk.",
      "..kkykykykykkyk.",
      "..kyykykykykyyk.",
      "..kkkkkkkkkkkkk.",
      "..krrrrrrrrrrrk.",
      "..krrrrrrrrrrrk.",
      "..krrkrrrrrkrrk.",
      "...krkrrrrrkrk..",
      "...krrrrkrrrrk..",
      "...kprrrrrrrpk..",
      "...krrrrrrrrrk..",
      "...kkkkkkkkkkk..",
      "................",
    ],
    rows32: [
      "................................",
      "...............kk...............",
      ".........kk...kyyk...kk.........",
      "........kyyk..kyykkkkyyk........",
      "........kyykkkkyykyykyyk........",
      "......kkkyykyykyykyykyykkk......",
      ".....kyykyykyykyykyykyykyyk.....",
      ".....kyykyykyykyykyykyykyyk.....",
      ".....kyykyykyykyykyykyykyyk.....",
      ".....kyykkkkkkkkkkkkkkkkyyk.....",
      ".....kkkkrrrrrrrrrrrrrrkkkk.....",
      "....kkrrrrrrrrrrrrrrrrrrrrkk....",
      "...krrrrrrrrrrrrrrrrrrrrrrrrk...",
      "...krrrrrrrrrrrrrrrrrrrrrrrrk...",
      "...krrrrrrrrrrrrrrrrrrrrrrrrk...",
      "...krrrrrrrrrrrrrrrrrrrrrrrrk...",
      "...krrrrrrrrrrrrrrrrrrrrrrrrk...",
      "....krrrrrrrrrrrrrrrrrrrrrrk....",
      "....krrrrrrrrrrrrrrrrrrrrrrk....",
      "....krrrrrrwkrrrrrrwkrrrrrrk....",
      "....krrrrrrkkrrrrrrkkrrrrrrk....",
      "....krrrppprrrrrrrrrrppprrrk....",
      "....krrrppprrrkrrkrrrppprrrk....",
      "....krrrrrrrrrrkkrrrrrrrrrrk....",
      "....krrrrrrrrrrrrrrrrrrrrrrk....",
      "....krrrrrrrrrrrrrrrrrrrrrrk....",
      ".....krrrrrrrrrrrrrrrrrrrrk.....",
      ".....krrrrrrrrrrrrrrrrrrrrk.....",
      ".....krrrrrrrrrrrrrrrrrrrrk.....",
      ".....krrrrrrrrrrrrrrrrrrrrk.....",
      "......kkkkkkkkkkkkkkkkkkkk......",
      "................................",
    ],
  },
  {
    id: "milk",
    name: "우유",
    aliases: ["milk", "우유팩", "딸기우유", "초코우유"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#6fb6ff",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      "......kkkk......",
      ".....kwwwwk.....",
      "....kwwwwwwk....",
      "...kwwwwwwwwk...",
      "...kkkkkkkkkk...",
      "...kwwwwwwwwk...",
      "...kwwwwwwwwk...",
      "...kwkwwwwkwk...",
      "...kwkwwwwkwk...",
      "...kpwwkkwwpk...",
      "...kbbbbbbbbk...",
      "...kbwbbbbwbk...",
      "...kbbbbbbbbk...",
      "...kkkkkkkkkk...",
      "................",
    ],
    rows32: [
      "............kkkkkkkkk...........",
      "...........kwwwwwwwwwk..........",
      "...........kwwwwwwwwwk..........",
      "...........kwwwwwwwwwk..........",
      "............kkkkkkkkk...........",
      "............kwwwwwwk............",
      "...........kwwwwwwwwk...........",
      "..........kwwwwwwwwwwk..........",
      ".........kwwwwwwwwwwwwk.........",
      "........kwwwwwwwwwwwwwwk........",
      ".......kkkkkkkkkkkkkkkkkk.......",
      "......kkkkkkkkkkkkkkkkkkkk......",
      "......kwwwwwwwwwwwwwwwwwwk......",
      "......kwwwwwwwwwwwwwwwwwwk......",
      "......kwwwwwwwwwwwwwwwwwwk......",
      "......kwwwwwkwwwwwwwkwwwwk......",
      "......kwwwwkkwwwwwwkkwwwwk......",
      "......kwwwwwwwwwwwwwwwwwwk......",
      "......kwpppwwwkwwkwwwpppwk......",
      "......kwpppwwwwkkwwwwpppwk......",
      "......kwwwwwwwwwwwwwwwwwwk......",
      "......kwwwwwwwwwwwwwwwwwwk......",
      "......kwwwwwwwwwwwwwwwwwwk......",
      "......kbbbbbbbbbbbbbbbbbbk......",
      "......kbbbbbbbbbbbbbbbbbbk......",
      "......kbbbbbbbbbbbbbbbbbbk......",
      "......kbbbbbbbbbbbbbbbbbbk......",
      "......kbbbbbbbbbbbbbbbbbbk......",
      "......kbbbbbbbbbbbbbbbbbbk......",
      "......kbbbbbbbbbbbbbbbbbbk......",
      "......kbbbbbbbbbbbbbbbbbbk......",
      ".......kkkkkkkkkkkkkkkkkk.......",
    ],
  },
  {
    id: "egg",
    name: "계란",
    aliases: ["계란후라이", "계란프라이", "달걀", "egg", "에그"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffc93d",
      l: "#ffe9a6",
    },
    rows: [
      "................",
      "................",
      "....kkkkk.......",
      "...kwwwwwkkkk...",
      "..kwwwwwwwwwwk..",
      ".kwwwwkkkkwwwwk.",
      ".kwwwkyyyykwwwk.",
      "kwwwkylyyyykwwk.",
      "kwwwkyyyyyykwwwk",
      ".kwwkyyyyyykwwwk",
      ".kwwwkyyyykwwwk.",
      "..kwwwkkkkwwwwk.",
      "..kwwwwwwwwwwk..",
      "...kkwwwwwkkk...",
      ".....kkkkk......",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "...................kkkkkk.......",
      ".......kkkk.kkkkkkkwwwwwwk......",
      ".....kkwwwwkwwwwwwwwwwwwwwk.....",
      "....kwwwwwwwwwwwwwwwwwwwwwwk....",
      "...kwwwwwwwwwwwwwwwwwwwwwwwk....",
      "...kwwwwwwwwwwwwwwwwwwwwwwwk....",
      "..kwwwwwwwwwwkkkkkkwwwwwwwwk....",
      "..kwwwwwwwwwkyyyyyykwwwwwwwk....",
      "..kwwwwwwwwkyyyyyyyykwwwwwwk....",
      "..kwwwwwwwkyyllyyyyyykwwwwk.....",
      "...kwwwwwkyyllllyyyyyykwwwk.....",
      "...kwwwwwkyyyllyyyyyyykwwwk.....",
      "...kwwwwwkyyyyyyyyyyyykwwwkk....",
      "...kwwwwwkyyyyyyyyyyyykwwwwwk...",
      "...kwwwwwkyyyyyyyyyyyykwwwwwk...",
      "...kwwwwwkyyyyyyyyyyyykwwwwwwk..",
      "....kwwwwwkyyyyyyyyyykwwwwwwwk..",
      "...kwwwwwwwkyyyyyyyykwwwwwwwwk..",
      "...kwwwwwwwwkyyyyyykwwwwwwwwwk..",
      "...kwwwwwwwwwkkkkkkwwwwwwwwwwk..",
      "...kwwwwwwwwwwwwwwwwwwwwwwwwwk..",
      "....kwwwwwwwwwwwwwwwwwwwwwwwk...",
      "....kwwwwwwwwwwwwwwwwwwwwwwwk...",
      ".....kwwwwwwwwwwwwkkwwwwwwkk....",
      "......kkwwwwkkkkkk..kkkkkk......",
      "........kkkk....................",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "pineapple",
    name: "파인애플",
    aliases: ["pineapple"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
      d: "#f2b82e",
      g: "#6cc46c",
    },
    rows: [
      "......k..k......",
      ".....kgkkgk.....",
      "..kk.kggggk.kk..",
      "..kgkkggggkkgk..",
      "...kgggggggggk..",
      "....kkggggkk....",
      "....kkkkkkkk....",
      "...kyyyyyyyyk...",
      "..kydyyyydyyyk..",
      "..kyyydyyyyydk..",
      "..kydyyyydyyyk..",
      "..kyyydyyyyydk..",
      "..kydyyyydyyyk..",
      "...kyyydyyyyk...",
      "....kkkkkkkk....",
      "................",
    ],
    rows32: [
      "................................",
      "...............kk...............",
      "..............kggk..............",
      "..........k...kggk...k..........",
      ".........kgk..kggk..kgk.........",
      "..........kgkkggggkkgk..........",
      "......k...kggkggggkggk...k......",
      ".....kgk..kggkggggkggk..kgk.....",
      "......kgkkkgggkggkgggkkkgk......",
      ".......kggkkgggkkgggkkggk.......",
      ".......kggggkkkkkkkkggggk.......",
      "........kggkkyyydyykkggk........",
      ".........kkydyydydyydkk.........",
      "........kdyyyddyyyddyyyk........",
      ".......kddyyyddyyyddyyydk.......",
      ".......kyydydyydydyydydyk.......",
      "......kyyyydyyyydyyyydyyyk......",
      "......kdyydydyydydyydydyyk......",
      ".....kyyddyyyddyyyddyyyddyk.....",
      ".....kyyddyyyddyyyddyyyddyk.....",
      ".....kydyydydyydydyydydyydk.....",
      ".....kdyyyydyyyydyyyydyyyyk.....",
      ".....kydyydydyydydyydydyydk.....",
      ".....kyyddyyyddyyyddyyyddyk.....",
      "......kyddyyyddyyyddyyyddk......",
      "......kdyydydyydydyydydyyk......",
      ".......kyyydyyyydyyyydyyk.......",
      ".......kyydydyydydyydydyk.......",
      "........kdyyyddyyyddyyyk........",
      ".........kkyyddyyyddykk.........",
      "...........kkyydydykk...........",
      ".............kkkkkk.............",
    ],
  },
];
