import type { DraftTemplate } from "@/types";

/** 자연·날씨 도안 */
export const NATURE_DRAFTS: DraftTemplate[] = [
  {
    id: "flower",
    name: "꽃",
    aliases: ["flower", "꽃송이"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#ff8fb1",
      y: "#ffd93d",
      g: "#58b368",
    },
    rows: [
      "................",
      "....kkkkkkkk....",
      "...kppppppppk...",
      ".kkkppppppppkkk.",
      "kppkppppppppkppk",
      "kpppkkkkkkkkpppk",
      "kpppkyyyyyykpppk",
      ".kkkkyyyyyykkkk.",
      "kppkkyyyyyykkppk",
      "kpppkkkkkkkkpppk",
      "kpppkppppppkpppk",
      ".kkkppppppppkkk.",
      "....kkkggkkk....",
      "..kk..kggk..kk..",
      "..kgk.kggk.kgk..",
      "...kgkggggkgk...",
    ],
    rows32: [
      ".............kkkkkk.............",
      "............kppppppk............",
      "...........kppppppppk...........",
      "..........kppppppppppk..........",
      "........kkkppppppppppkkk........",
      "......kkppppppppppppppppkk......",
      ".....kppppppppppppppppppppk.....",
      "....kpppppppppkkkkpppppppppk....",
      "....kppppppppkyyyykppppppppk....",
      "....kpppppppkyyyyyykpppppppk....",
      "....kppppppkyyyyyyyykppppppk....",
      "....kppppppkyykyykyykppppppk....",
      "....kppppppkyyyyyyyykppppppk....",
      ".....kpppppkyyykkyyykpppppk.....",
      "......kkppppkyyyyyykppppkk......",
      "......kppppppkyyyykppppppk......",
      "......kpppppppkkkkpppppppk......",
      "......kppppppppppppppppppk......",
      "......kppppppppppppppppppk......",
      ".......kppppppppppppppppk.......",
      ".......kppppppppppppppppk.......",
      "........kkpppppkkpppppkk........",
      ".........kkkkkkggkkkkkk.........",
      "........kgggggkggkgggggk........",
      ".......kggggggkggkggggggk.......",
      "......kggggggkkggkkggggggk......",
      "......kgggggk.kggk.kgggggk......",
      "......kggggk..kggk..kggggk......",
      ".......kkkk...kggk...kkkk.......",
      "..............kggk..............",
      "..............kggk..............",
      "..............kggk..............",
    ],
  },
  {
    id: "sun",
    name: "해",
    aliases: ["태양", "sun", "햇님"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
      o: "#ff9f1c",
      p: "#ff9eb1",
    },
    rows: [
      ".......oo.......",
      ".o.....oo.....o.",
      "..o..........o..",
      "....kkkkkkkk....",
      "...kyyyyyyyyk...",
      "..kyyyyyyyyyyk..",
      "..kyykyyyykyyk..",
      "ookyykyyyykyykoo",
      "..kyyyyyyyyyyk..",
      "..kpyyyyyyyypk..",
      "..kyykyyyykyyk..",
      "...kyykkkkyyk...",
      "....kkkkkkkk....",
      "..o..........o..",
      ".o.....oo.....o.",
      ".......oo.......",
    ],
    rows32: [
      "................................",
      "..............kkkk..............",
      ".............kooook.............",
      ".............kooook.............",
      "......kk.....kooook.....kk......",
      ".....kook.....kkkk.....kook.....",
      "....kooook..kkkkkkkk..kooook....",
      "....kooookkkyyyyyyyykkkooook....",
      ".....koookyyyyyyyyyyyykoook.....",
      "......kkkyyyyyyyyyyyyyykkk......",
      ".......kyyyyyyyyyyyyyyyyk.......",
      ".......kyyyyyyyyyyyyyyyyk.......",
      "......kyyyyyyyyyyyyyyyyyyk......",
      "..kkk.kyyyywkyyyyyywkyyyyk.kkk..",
      ".koookkyyyykkyyyyyykkyyyykkoook.",
      ".koookkyyyyyyyyyyyyyyyyyykkoook.",
      ".koookkyyyyyyyyyyyyyyyyyykkoook.",
      ".koookkypppyyykyykyyypppykkoook.",
      "..kkk.kypppyyyykkyyyypppyk.kkk..",
      "......kyyyyyyyyyyyyyyyyyyk......",
      ".......kyyyyyyyyyyyyyyyyk.......",
      ".......kyyyyyyyyyyyyyyyyk.......",
      "......kkkyyyyyyyyyyyyyykkk......",
      ".....koookyyyyyyyyyyyykoook.....",
      "....kooookkkyyyyyyyykkkooook....",
      "....kooook..kkkkkkkk..kooook....",
      ".....kook.....kkkk.....kook.....",
      "......kk.....kooook.....kk......",
      ".............kooook.............",
      ".............kooook.............",
      "..............kkkk..............",
      "................................",
    ],
  },
  {
    id: "moon",
    name: "달",
    aliases: ["moon", "초승달", "밤"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffe27a",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      ".....kkkk.......",
      "...kkyyyk.......",
      "..kyyyyk........",
      ".kyyyyk.........",
      ".kyyyyk.........",
      "kyyyyk..........",
      "kyyyyk..........",
      "kyyyyk..........",
      "kyyyyyk.........",
      ".kyyyyyk......k.",
      ".kyyyyyykk..kkk.",
      "..kyyyyyyykkyyk.",
      "...kkyyyyyyyyk..",
      ".....kkkkkkkk...",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "..........kkkk..................",
      "........kkyyyyk.................",
      ".......kyyyyyyk.................",
      ".....kkyyyyyyk..................",
      "....kyyyyyyyk...................",
      "....kyyyyyyyk...................",
      "...kyyyyyyyyk...................",
      "..kyyyyyyyyyk...................",
      "..kyyyyyyyyyk...................",
      ".kyyyyyyyyyyk...................",
      ".kyyyyyyyyyyk...................",
      ".kyyyyyyyyyyk...................",
      ".kyyyyyyyyyyk...................",
      ".kyyyyyykyykk...................",
      ".kyyyyyyykkyyk..................",
      ".kyyyyyyyyyyyyk.................",
      ".kyyyyyyyyyyyyk.................",
      ".kyyyyypppyyyyykk...............",
      ".kyyyyypppyyyyyyyk..............",
      "..kyyyyyyyyyyyyyyykkkkkkkkk.....",
      "..kyyyyyyyyyyyyyyyyyyyyyyyyk....",
      "...kyyyyyyyyyyyyyyyyyyyyyyk.....",
      "....kyyyyyyyyyyyyyyyyyyyyk......",
      "....kyyyyyyyyyyyyyyyyyyyyk......",
      ".....kkyyyyyyyyyyyyyyyykk.......",
      ".......kyyyyyyyyyyyyyyk.........",
      "........kkyyyyyyyyyykk..........",
      "..........kkkkkkkkkk............",
      "................................",
      "................................",
    ],
  },
  {
    id: "cloud",
    name: "구름",
    aliases: ["cloud", "뭉게구름"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#dbe9f7",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      "................",
      "................",
      "......kkkk......",
      ".....kwwwwk.....",
      "..kkkwwwwwwkkk..",
      ".kwwwkwwwwkwwwk.",
      ".kwwwwwwwwwwwwk.",
      "kwwwwwwwwwwwwwwk",
      "kwwkwwwwwwwwkwwk",
      "kwwwwwkkkkwwwwwk",
      "kbwwwwwwwwwwwwbk",
      ".kbbbbbbbbbbbbk.",
      "..kkkkkkkkkkkk..",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      ".............kkkkkkkk...........",
      "............kwwwwwwwwk..........",
      "...........kwwwwwwwwwwk.........",
      "..........kwwwwwwwwwwwwk........",
      ".........kwwwwwwwwwwwwwwk.......",
      ".........kwwwwwwwwwwwwwwk.......",
      "........kwwwwwwwwwwwwwwwwkk.....",
      "......kkkwwwwwwwwwwwwwwwwwwk....",
      ".....kwwwwwwwwwwwwwwwwwwwwwwk...",
      "....kwwwwwwwwwwwwwwwwwwwwwwwwk..",
      "...kwwwwwwwwwwwwwwwwwwwwwwwwwwk.",
      "...kwwwwwwwwwkwwwwwkwwwwwwwwwwk.",
      "...kwwwwwwwwkkwwwwkkwwwwwwwwwwk.",
      "..kwwwwwwwwwwwwwwwwwwwwwwwwwwwk.",
      "...kwwwwwpppwwkwwkwwpppwwwwwwwk.",
      "...kwwwwwpppwwwkkwwwpppwwwwwwk..",
      "...kwwwwwwwwwwwwwwwwwwwwwwwwk...",
      "....kwwwwwwwwwwwwwwwwwwwwwwwk...",
      ".....kbbbbbbbbbbbbbbbbbbbbbbk...",
      ".....kbbbbbbbbbbbbbbbbbbbbbbk...",
      "......kkkkkkkkkkkkkkkkkkkkkk....",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "rainbow",
    name: "무지개",
    aliases: ["rainbow", "레인보우"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a6e",
      o: "#ff9f1c",
      y: "#ffd93d",
      g: "#6bcb77",
      b: "#4d96ff",
      c: "#e8f1fb",
    },
    rows: [
      "................",
      "................",
      "....kkkkkkkk....",
      "..kkrrrrrrrrkk..",
      ".krroooooooorrk.",
      ".kroyyyyyyyyork.",
      "kroyyggggggyyork",
      "kroygbbbbbbgyork",
      "kroygbkkkkbgyork",
      "kroygbk..kbgyork",
      "kroygbk..kbgyork",
      "kkkkkkk..kkkkkkk",
      "kccckk....kkccck",
      "kccccck..kccccck",
      ".kkkkkk..kkkkkk.",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "............kkkkkkkk............",
      ".........kkkrrrrrrrrkkk.........",
      "........krrrrrrrrrrrrrrk........",
      "......kkrrrroooooooorrrrkk......",
      ".....krrrroooooooooooorrrrk.....",
      "....krrroooooyyyyyyooooorrrk....",
      "...krrroooyyyyyyyyyyyyooorrrk...",
      "...krroooyyyyggggggyyyyooorrk...",
      "..krroooyyyggggggggggyyyooorrk..",
      ".krrrooyyygggbbbbbbgggyyyoorrrk.",
      ".krrooyyygggbbbbbbbbgggyyyoorrk.",
      ".krrooyygggbbbkkkkbbbgggyyoorrk.",
      "krroooyyggbbkk....kkbbggyyooorrk",
      "krkkkkyggbbbk......kbbbggykkkkrk",
      "kkcccckkkkbk........kbkkkkcccckk",
      "kccccccccckk........kkccccccccck",
      "kcccccccccck........kcccccccccck",
      "kcccccccccck........kcccccccccck",
      "kcccccccccck........kcccccccccck",
      "kcccccccccck........kcccccccccck",
      "kcccccccccck........kcccccccccck",
      ".kkkkkkkkkk..........kkkkkkkkkk.",
      "................................",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "tree",
    name: "나무",
    aliases: ["tree", "크리스마스트리", "숲"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      g: "#58b368",
      d: "#3f8f4f",
      b: "#8a5a2b",
    },
    rows: [
      "................",
      "....kkkkkkkk....",
      "...kggggggggk...",
      "..kggggggggggk..",
      ".kgggggddgggggk.",
      ".kgdggggggggdgk.",
      "kggggggggggggggk",
      "kgggggdggdgggggk",
      "kggdggggggggdggk",
      ".kggggggggggggk.",
      "..kkkggggggkkk..",
      "....kkbbbbkk....",
      ".....kbbbbk.....",
      ".....kbbbbk.....",
      "....kkkkkkkk....",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "............kkkkkkkk............",
      "...........kggggggggk...........",
      "..........kggggggggggk..........",
      ".........kggggggggggggk.........",
      "........kgggddgggggggggk........",
      ".......kggggddggggggggggk.......",
      ".......kggggggggggggddggk.......",
      ".....kkgggggggggggggddgggkk.....",
      "....kggggggggggggggggggggggk....",
      "...kggggggggggggggggggggggggk...",
      "...kggggggggggddddggggggggggk...",
      "..kgggggggggggddddgggggggggggk..",
      "..kggggggggggggggggggggggggggk..",
      "..kggggggggggggggggggggggggggk..",
      "..kggggddddggggggggggddddggggk..",
      "...kgggddddggggggggggddddgggk...",
      "...kggggggggggggggggggggggggk...",
      "....kggggggggggggggggggggggk....",
      ".....kkggggggggggggggggggkk.....",
      ".......kkkkkggggggggkkkkk.......",
      "............kkggggkk............",
      "............kbkkkkbk............",
      "............kbbbbbbk............",
      "............kbbbbbbk............",
      "............kbbbbbbk............",
      "...........kbbbbbbbbk...........",
      "..........kbbbbbbbbbbk..........",
      "..........kbbbbbbbbbbk..........",
      ".........kbbbbbbbbbbbbk.........",
      "..........kkkkkkkkkkkk..........",
    ],
  },
  {
    id: "mushroom",
    name: "버섯",
    aliases: ["mushroom", "버섯돌이"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a6e",
      c: "#fff3e0",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      "....kkkkkkkk....",
      "..kkrrrrrrrrkk..",
      ".krrwwrrrrwwrrk.",
      ".krwwwrrrrwwwrk.",
      "krrrrrrwwrrrrrrk",
      "kwrrrrrwwrrrrrwk",
      "kwwrrrrrrrrrrwwk",
      "kkkkkkkkkkkkkkkk",
      "...kcccccccck...",
      "...kckcccckck...",
      "...kckcccckck...",
      "...kcccccccck...",
      "...kcccccccck...",
      "....kkkkkkkk....",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "............kkkkkkkk............",
      ".........kkkrrrrrrrrkkk.........",
      ".......kkrrrrrwwwwrrrrrkk.......",
      "......krrrrrrrwwwwrrrrrrrk......",
      ".....krrrrrrrrwwwwrrrrrrrrk.....",
      "....krrrrrrrrrwwwwrrrrrrrrrk....",
      "...krrrrrrrrrrrrrrrrrrrrrrrrk...",
      "..krrrrwwwwrrrrrrrrrrwwwwrrrrk..",
      "..krrrrwwwwrrrrrrrrrrwwwwrrrrk..",
      ".krrrrrwwwwrrrrrrrrrrwwwwrrrrrk.",
      ".krrrrrwwwwrrrrrrrrrrwwwwrrrrrk.",
      ".krrrrrrrrrrwwrrrrrwwrrrrrrrrrk.",
      ".krrrrrrrrrrwwrrrrrwwrrrrrrrrrk.",
      ".krrrrrrrrrrrrrrrrrrrrrrrrrrrrk.",
      ".krrrrrrrrrrrrrrrrrrrrrrrrrrrrk.",
      ".krrrrrrrrrrrrrrrrrrrrrrrrrrrrk.",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      ".........kcccccccccccck.........",
      ".........kcccccccccccck.........",
      ".........kccwkccccwkcck.........",
      ".........kcckkcccckkcck.........",
      ".........kcccccccccccck.........",
      ".........kcccckcckcccck.........",
      ".........kccccckkccccck.........",
      ".........kcccccccccccck.........",
      ".........kcccccccccccck.........",
      ".........kcccccccccccck.........",
      "..........kcccccccccck..........",
      "...........kkkkkkkkkk...........",
      "................................",
    ],
  },
  {
    id: "cactus",
    name: "선인장",
    aliases: ["cactus", "다육이", "화분", "식물"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      g: "#58b368",
      o: "#d9774b",
      p: "#ff8fb1",
    },
    rows: [
      ".......pp.......",
      "......kkkk......",
      ".....kggggk.....",
      ".....kggggk.....",
      ".kk..kggggk..kk.",
      "kggk.kggggk.kggk",
      "kggk.kggggk.kggk",
      "kggkkkggggkkkggk",
      ".kggggggggggggk.",
      "..kkkkggggkkkk..",
      ".....kggggk.....",
      ".....kggggk.....",
      "..kkkkkkkkkkkk..",
      "..kooooooooook..",
      "...kooooooook...",
      "...kkkkkkkkkk...",
    ],
    rows32: [
      ".............kpppk..............",
      ".............kpppk..............",
      "............kkpppkk.............",
      "...........kgkpppkgk............",
      "..........kgggkkkgggk...kkk.....",
      "..........kggggggggggk.kgggk....",
      "....kkk...kggggggggggk.kggggk...",
      "...kgggk..kggggggggggk.kggggk...",
      "...kggggk.kgggggggwggk.kggggk...",
      "...kggggk.kggwgggggggk.kggwgk...",
      "...kggggk.kggggggggggkkkggggk...",
      "...kgwggk.kgggggggggggggggggk...",
      "...kggggkkkgggggggggggggggggk...",
      "...kggggggggggggggwgggggggggk...",
      "...kggggggggggggggggggggggggk...",
      "...kgggggggggwgggggggkkkkkkk....",
      "...kgggggggggggggggggk..........",
      "....kkkkkkkggggggggggk..........",
      "..........kggggggggggk..........",
      ".....kkkkkkggggggggggkkkkkk.....",
      "....kooooookkkkkkkkkkooooook....",
      "....kooooooooooooooooooooook....",
      "....kooooooooooooooooooooook....",
      "....kooooooooooooooooooooook....",
      ".....kkkkkkkkkkkkkkkkkkkkkk.....",
      ".......kooooooooooooooook.......",
      ".......kooooooooooooooook.......",
      ".......kooooooooooooooook.......",
      ".......kooooooooooooooook.......",
      "........kooooooooooooook........",
      "........kooooooooooooook........",
      ".........kkkkkkkkkkkkkk.........",
    ],
  },
  {
    id: "clover",
    name: "클로버",
    aliases: ["clover", "네잎클로버", "행운"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      g: "#58b368",
      l: "#8fd694",
    },
    rows: [
      "................",
      "...kkk....kkk...",
      "..kgggk..kgggk..",
      ".kgglggkkgglggk.",
      ".kgggggkkgggggk.",
      ".kgggggkkgggggk.",
      "..kgggkkkkgggk..",
      "...kkkkggkkkk...",
      "..kgggkkkkgggk..",
      ".kgggggkkgggggk.",
      ".kgglggkkgglggk.",
      ".kgggggkkgggggk.",
      "..kgggk..kgggk..",
      "...kkk....kkk...",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "...........kkkk..kkkk...........",
      "..........kggggkkggggk..........",
      ".........kggggggggggggk.........",
      ".........kggggggggggggk.........",
      "........kggggggggggggggk........",
      ".........kggggggggggggk.........",
      "......k..kgggggglgggggk..k......",
      "....kkgkk.kggggglggggk.kkgkk....",
      "...kgggggk.kkggglggkk.kgggggk...",
      "..kgggggggk.kggglggk.kgggggggk..",
      "..kgggggggkk.kgglgk.kkgggggggk..",
      "..kgggggggggk.kglk.kgggggggggk..",
      "..kggggggggggk.kl.kggggggggggk..",
      "...kggggggggggk..kggggggggggk...",
      "...kgggglllllll..klllllllgggk...",
      "..kggggggggggk.kkkkggggggggggk..",
      "..kgggggggggk.kglkkkgggggggggk..",
      "..kgggggggkk.kgglgk.kkgggggggk..",
      "..kgggggggk.kggglggk.kgggggggk..",
      "...kgggggk.kkggglggkk.kgggggk...",
      "....kkgkk.kggggglggggk.kkgkk....",
      "......k..kgggggglgggggk..k......",
      ".........kgggggglgggggk.........",
      "........kggggggggggggggk........",
      ".........kggggggggggggk.........",
      ".........kggggggggggggk.........",
      "..........kggggkkggggk..........",
      "...........kkkk..kkkkk..........",
      "..................kggk..........",
      "..................kggk..........",
      "...................kk...........",
    ],
  },
  {
    id: "lightning",
    name: "번개",
    aliases: ["lightning", "번쩍", "전기", "천둥"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
    },
    rows: [
      "................",
      ".......kkkkk....",
      "......kyyyyk....",
      ".....kyyyyk.....",
      "....kyyyyk......",
      "...kyyyyk.......",
      "..kyyyyykkkkk...",
      "..kyyyyyyyyyk...",
      "..kkkkkyyyyk....",
      "......kyyyk.....",
      ".....kyyyk......",
      ".....kyyk.......",
      "....kyyk........",
      "....kyk.........",
      "....kk..........",
      "................",
    ],
    rows32: [
      "...................kkkk.........",
      "..................kyyyyk........",
      ".................kyyyyk.........",
      "................kyyyyyk.........",
      "...............kyyyyyk..........",
      "...............kyyyyyk..........",
      "..............kyyyyyk...........",
      ".............kyyyyyk............",
      "............kyyyyyyk............",
      "...........kyyyyyyk.............",
      "...........kyyyyyyk.............",
      "..........kyyyyyykkkkkkkkk......",
      ".........kyyyyyyyyyyyyyyyyk.....",
      "........kyyyyyyyyyyyyyyyyk......",
      "........kyyyyyyyyyyyyyyyk.......",
      ".......kyyyyyyyyyyyyyyyk........",
      "......kyyyyyyyyyyyyyyyk.........",
      ".....kyyyyyyyyyyyyyyyyk.........",
      "......kkkkkkkkkyyyyyyk..........",
      "..............kyyyyyk...........",
      ".............kyyyyyk............",
      ".............kyyyyk.............",
      ".............kyyyyk.............",
      "............kyyyyk..............",
      "............kyyyk...............",
      "............kyyk................",
      "...........kyyyk................",
      "...........kyyk.................",
      "...........kyk..................",
      "..........kyk...................",
      "...........k....................",
      "................................",
    ],
  },
  {
    id: "snowflake",
    name: "눈송이",
    aliases: ["snowflake", "눈꽃", "크리스탈"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#7ec8e3",
    },
    rows: [
      "................",
      ".......bb.......",
      ".....b.bb.b.....",
      "......bbbb......",
      "..b....bb....b..",
      "...b...bb...b...",
      "....b..bb..b....",
      ".bbbbbbbbbbbbbb.",
      ".bbbbbbbbbbbbbb.",
      "....b..bb..b....",
      "...b...bb...b...",
      "..b....bb....b..",
      "......bbbb......",
      ".....b.bb.b.....",
      ".......bb.......",
      "................",
    ],
    rows32: [
      "................................",
      "...............k................",
      ".............kkbk.k.............",
      "............kbkbkkbk............",
      ".............kbbbbk.............",
      ".............kkbkkk.............",
      "......k.....kbkbkkbk.....k......",
      ".....kbk.....kbbbbk.....kbk.....",
      "....kkbkk.....kbkk.....kkbkk....",
      "...kbkbkbk.....kbk....kbkbkbk...",
      "...kkbbkbk.....kbk....kbkbbkk...",
      "..kbbkkbbbk....kbk...kbkbkkbbk..",
      "...kk.kkbbbk...kbk..kkbbkk.kk...",
      ".....kbbkkkbkk.kbk.kbbkkbbk.....",
      "......kk...kbbkkbkkbkk..kk......",
      "............kkbbbbbk............",
      "..............kbbkk.............",
      "......kk...kkkbkbbbkk...kk......",
      ".....kbbkkkbbbkkbkkbbkkkbbk.....",
      "...kk.kkbbbkkk.kbk.kkbbbkk.kk...",
      "..kbbkkbbbk....kbk...kbbbkkbbk..",
      "...kkbbkbk.....kbk....kbkbbkk...",
      "...kbbbkbk.....kbk....kbkbkbk...",
      "....kkbkk.....kkbk.....kkbkk....",
      ".....kbk.....kbbbbk.....kbk.....",
      "......k.....kbkkbkbk.....k......",
      ".............kkkbkk.............",
      ".............kbbbbk.............",
      "............kbkkbkbk............",
      ".............k..k.k.............",
      "................................",
      "................................",
    ],
  },
  {
    id: "fire",
    name: "불",
    aliases: ["fire", "불꽃", "열정", "hot"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a3c",
      o: "#ff9f1c",
      y: "#ffd93d",
    },
    rows: [
      "................",
      ".......kk.......",
      "......krrk......",
      "......krrk......",
      ".....krrrrk.....",
      "..k..krrrrk..k..",
      ".krk.kroork.krk.",
      ".krrkkroorkkrrk.",
      "krrrroyyyyorrrrk",
      "krrrooyyyyoorrrk",
      "krrooyyyyyyoorrk",
      "krrooyyyyyyoorrk",
      ".krrooyyyyoorrk.",
      "..krroooooorrk..",
      "...kkkkkkkkkk...",
      "................",
    ],
    rows32: [
      "................................",
      "................kk..............",
      "...............krrk.............",
      "........k......krrk.............",
      ".......krk.....krrrk............",
      ".......krk....krrrrk....k.......",
      "......krrrk...krrrrk...krk......",
      "......krrrk...krrrrrk.krrk......",
      "......krrrrk.krrrrrrkkrrrk......",
      "......krrrrrkkrroorrrrrrrrk.....",
      "......krrrrrkkrroorrrrrrrrk.....",
      ".....krrrrrrrrrroorrrrrrrrk.....",
      ".....krrrrrrrrroooorrrrrrrk.....",
      ".....krrrrrorrroooorrrorrrk.....",
      ".....krrrroorrroooorroorrrk.....",
      ".....krrrrooorooooooooorrrk.....",
      ".....krrrrooooooooooooorrrrk....",
      "....krrrrroooooooyooooorrrrk....",
      "....krrrrooooooooyyooooorrrk....",
      "....krrrrooooyyooyyooooorrrk....",
      "....krrrrooooyyyyyyooooorrrk....",
      "....krrroooooyyyyyyyoooorrrk....",
      "....krrrooooyyyyyyyyoooorrrk....",
      "....krrrooooyyyyyyyyoooorrrk....",
      ".....krrooooyyyyyyyyoooorrk.....",
      ".....krrroooyyyyyyyyooorrrk.....",
      "......krroooyyyyyyyyooorrk......",
      ".......krrooyyyyyyyyoorrk.......",
      "........krrooyyyyyyoorrk........",
      ".........kkrroooooorrkk.........",
      "...........kkkkkkkkkk...........",
      "................................",
    ],
  },
  {
    id: "tulip",
    name: "튤립",
    aliases: ["tulip"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a6e",
      h: "#ffc2cb",
      g: "#6cc46c",
    },
    rows: [
      "................",
      "....k..kk..k....",
      "...krkkrrkkrk...",
      "...krrkrrkrrk...",
      "...khrrrrrrrk...",
      "...khrrrrrrrk...",
      "...krrrrrrrrk...",
      "....krrrrrrk....",
      ".....kkkkkk.....",
      ".......kgk......",
      "..kkk..kgk..kkk.",
      "..kggk.kgk.kggk.",
      "...kggkkgkkggk..",
      "....kgggggggk...",
      ".....kkkkkkk....",
      "................",
    ],
    rows32: [
      "................................",
      "...............kk......k........",
      "........k.....krrk....krk.......",
      ".......krk...krrrrk..krrk.......",
      ".......krrk.krrrrrrkkrrrk.......",
      ".......krrrkrrrrrrrrrrrrk.......",
      ".......krrrrrrrrrrrrrrrrk.......",
      ".......krrrrkrrrrrrrkrrrk.......",
      ".......krhhrkrrrrrrrkrrrk.......",
      ".......krhhrkrrrrrrrkrrrk.......",
      ".......krhhrkrrrrrrrkrrrk.......",
      ".......krhhrrkrrrrrkrrrrk.......",
      ".......krhhrrkrrrrrkrrrrk.......",
      ".......krhhrrkrrrrrkrrrrk.......",
      ".......krrrrrkrrrrrkrrrrk.......",
      "........krrrrrrrrrrrrrrk........",
      ".........krrrrrrrrrrrrk.........",
      "..........krrrrrrrrrrk..........",
      "...........krrrrrrrrk...........",
      "..........kgkkkkkkkkgk..........",
      ".........kggggkggkggggk.........",
      "........kgggggkggkgggggk........",
      ".......kgggggkkggkkgggggk.......",
      ".......kgggggkkggkkgggggk.......",
      "......kgggggk.kggk.kgggggk......",
      "......kgggggk.kggk.kgggggk......",
      ".....kgggggk..kggk..kgggggk.....",
      ".....kggggk...kggk...kggggk.....",
      ".....kgggk....kggk....kgggk.....",
      "......kkk.....kggk.....kkk......",
      "..............kggk..............",
      "...............kk...............",
    ],
  },
  {
    id: "sunflower",
    name: "해바라기",
    aliases: ["sunflower"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
      b: "#8b5a2b",
      g: "#6cc46c",
      d: "#6b3e1f",
      p: "#ff9eb1",
    },
    rows: [
      "......kkkk......",
      "...kkkyyyykkk...",
      "..kyykyyyykyyk..",
      "..kyyykkkkyyyk..",
      ".kkykkbbbbkkykk.",
      "kyyykbbbbbbkyyyk",
      "kyyykbkbbkbkyyyk",
      "kyyykbbbbbbkyyyk",
      ".kkykkbbbbkkykk.",
      "..kyyykkkkyyyk..",
      "..kyykyyyykyyk..",
      "...kkkyyyykkk...",
      "......kkgkk.....",
      "...kkk.kgk......",
      "...kggkkgk......",
      "....kkkkkk......",
    ],
    rows32: [
      "...........kkkkyykkkk...........",
      ".........kkyyyyyyyyyykk.........",
      "........kyyyyyyyyyyyyyyk........",
      "........kyyyyyyyyyyyyyyk........",
      "......kkyyyyyyyyyyyyyyyykk......",
      ".....kyyyyyyykkkkkkyyyyyyyk.....",
      ".....kyyyyykkbbdbbbkkyyyyyk.....",
      "....kyyyyykbbbdbbdbbbkyyyyyk....",
      "....kyyyyykbbdbbdbbdbkyyyyyk....",
      "....kyyyykbbdbbdbbdbbbkyyyyk....",
      "....kyyyykbdwkdbbdwkdbkyyyyk....",
      "...kyyyyykdbkkbbdbkkbbkyyyyyk...",
      "...kyyyyykbbdbbdbbdbbdkyyyyyk...",
      "....kyyyykbdbbdbbdbbdbkyyyyk....",
      "....kyyyykbbbdkbdkbdbbkyyyyk....",
      "....kyyyyykbdbbkkbdbbkyyyyyk....",
      "....kyyyyykbbbdbbdbbbkyyyyyk....",
      ".....kyyyyykkbbbdbbkkyyyyyk.....",
      ".....kyyyyyyykkkkkkyyyyyyyk.....",
      "......kkyyyyyyyyyyyyyyyykk......",
      "........kyyyyyyyyyyyyyyk........",
      "........kyyyyyyyyyyyyyyk........",
      ".........kkyyyyyyyyyykk.........",
      "...........kkkkyykkkkkk.........",
      "..............kkkggggggk........",
      "..............kgkgggggggk.......",
      "..............kggkgggggggk......",
      "..............kggkkggggggk......",
      "..............kggk.kkggggk......",
      "..............kggk...kkkk.......",
      "..............kggk..............",
      "..............kggk..............",
    ],
  },
  {
    id: "leaf",
    name: "나뭇잎",
    aliases: ["잎", "잎사귀", "leaf", "새싹"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      g: "#6cc46c",
      d: "#3f9a4f",
    },
    rows: [
      "................",
      "..........kkkkk.",
      "........kkgggdk.",
      ".......kgggggdk.",
      "......kggggggdk.",
      ".....kgggggdgdk.",
      "....kggggggdgk..",
      "....kgggggdggk..",
      "...kgggggdgggk..",
      "...kggggdggggk..",
      "...kgggdggggk...",
      "...kggdggggk....",
      "...kgdgggkk.....",
      "..kkdkkkk.......",
      ".kdk............",
      ".kk.............",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "...................kkkkkkk......",
      ".................kkgggggggk.....",
      "...............kkggdgggggggk....",
      "..............kgggggdggggggk....",
      ".............kgggggggdgggdgk....",
      "............kgdgggggggggdggk....",
      "...........kgggdgggggggdgggk....",
      "..........kgggggdgggggdggggk....",
      ".........kgggggggdgggdgggggk....",
      "........kgdgggggggggdgggggk.....",
      "........kggdgggggggdggggggk.....",
      ".......kggggdgggggdggggggk......",
      ".......kgggggdgggdgggggggk......",
      "......kgggggggggdgggggggk.......",
      "......kggggggggdgggggggk........",
      "......kgggggggdgggggggk.........",
      "......kggggggdgggggggk..........",
      "......kgggggdgggggggk...........",
      "......kggggdgggggggk............",
      "......kgggdggggggkk.............",
      ".......kgdgggggkk...............",
      ".......kkkkkkkk.................",
      "......kdk.......................",
      ".....kdk........................",
      "....kdk.........................",
      "...kdk..........................",
      "..kdk...........................",
      "...k............................",
      "................................",
    ],
  },
  {
    id: "waterdrop",
    name: "물방울",
    aliases: ["물", "water", "빗방울"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#5b9df0",
      c: "#9fd8ff",
      p: "#ff9eb1",
    },
    rows: [
      ".......kk.......",
      "......kbbk......",
      "......kbbk......",
      ".....kbbbbk.....",
      ".....kbbbbk.....",
      "....kbbbbbbk....",
      "...kbbbbbbbbk...",
      "..kbcbbbbbbbbk..",
      "..kbcbbbbbbbbk..",
      ".kbcbbkbbbkbbbk.",
      ".kbcbbkbbbkbbbk.",
      ".kbbbbbbbbbbbbk.",
      ".kbbpbbkkbbpbbk.",
      "..kbbbbbbbbbbk..",
      "...kkbbbbbbkk...",
      ".....kkkkkk.....",
    ],
    rows32: [
      "...............kk...............",
      "..............kbbk..............",
      "..............kbbk..............",
      ".............kbbbbk.............",
      ".............kbbbbk.............",
      "............kbbbbbbk............",
      "...........kbbbbbbbbk...........",
      "...........kbbbbbbbbk...........",
      "..........kbbbbbbbbbbk..........",
      ".........kbbbbbbbbbbbbk.........",
      ".........kbbbbbbbbbbbbk.........",
      "........kbbbbbbbbbbbbbbk........",
      "........kbbbbbbbbbbbbbbk........",
      ".......kbbbbbbbbbbbbbbbbk.......",
      "......kbbccbbbbbbbbbbbbbbk......",
      "......kbbccbbbbbbbbbbbbbbk......",
      ".....kbbbccbbbbbbbbbbbbbbbk.....",
      ".....kbbbccbbbbbbbbbbbbbbbk.....",
      ".....kbbbccbbbbbbbbbbbbbbbk.....",
      ".....kbbbccwkbbbbbbwkbbbbbk.....",
      ".....kbbbbbkkbbbbbbkkbbbbbk.....",
      ".....kbbbbbbbbbbbbbbbbbbbbk.....",
      ".....kbbbbbbbbbbbbbbbbbbbbk.....",
      ".....kbbpppbbbkbbkbbbpppbbk.....",
      "......kbpppbbbbkkbbbbpppbk......",
      "......kbbbbbbbbbbbbbbbbbbk......",
      ".......kbbbbbbbbbbbbbbbbk.......",
      "........kbbbbbbbbbbbbbbk........",
      ".........kbbbbbbbbbbbbk.........",
      "..........kkbbbbbbbbkk..........",
      "............kkkkkkkk............",
      "................................",
    ],
  },
];
