import type { DraftTemplate } from "@/types";

/** 물건·기호 도안 */
export const OBJECT_DRAFTS: DraftTemplate[] = [
  {
    id: "heart",
    name: "하트",
    aliases: ["사랑", "love", "heart"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a6e",
      h: "#ffc2cb",
    },
    rows: [
      "................",
      "................",
      "..kkkk....kkkk..",
      ".krrrrk..krrrrk.",
      "krhhrrrkkrrrrrrk",
      "krhrrrrrrrrrrrrk",
      "krrrrrrrrrrrrrrk",
      "krrrrrrrrrrrrrrk",
      ".krrrrrrrrrrrrk.",
      "..krrrrrrrrrrk..",
      "...krrrrrrrrk...",
      "....krrrrrrk....",
      ".....krrrrk.....",
      "......krrk......",
      ".......kk.......",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      ".......kkkkk........kkkkk.......",
      ".....kkrrrrrkk....kkrrrrrkk.....",
      "....krrrrrrrrrk..krrrrrrrrrk....",
      "...krrrrrrrrrrrkkrrrrrrrrrrrk...",
      "..krrrrrhrrrrrrrrrrrrrrrrrrrrk..",
      "..krrrhhhhhrrrrrrrrrrrrrrrrrrk..",
      "..krrrhhhhhrrrrrrrrrrrrrrrrrrk..",
      "..krrrrrhrrrrrrrrrrrrrrrrrrrrk..",
      "..krrrhrrrrrrrrrrrrrrrrrrrrrrk..",
      "..krrrhrrrrrrrrrrrrrrrrrrrrrrk..",
      "..krrrrrrrrrrrrrrrrrrrrrrrrrrk..",
      "..krrrrrrrrrrrrrrrrrrrrrrrrrrk..",
      "...krrrrrrrrrrrrrrrrrrrrrrrrk...",
      "....krrrrrrrrrrrrrrrrrrrrrrk....",
      ".....kkrrrrrrrrrrrrrrrrrrkk.....",
      ".......krrrrrrrrrrrrrrrrk.......",
      ".......krrrrrrrrrrrrrrrrk.......",
      "........krrrrrrrrrrrrrrk........",
      ".........krrrrrrrrrrrrk.........",
      "..........krrrrrrrrrrk..........",
      "...........krrrrrrrrk...........",
      "............krrrrrrk............",
      ".............krrrrk.............",
      "..............krrk..............",
      "...............kk...............",
      "................................",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "star",
    name: "별",
    aliases: ["star", "스타"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
      p: "#ff9eb1",
    },
    rows: [
      ".......kk.......",
      "......kyyk......",
      "......kyyk......",
      ".....kyyyyk.....",
      "kkkkkkyyyykkkkkk",
      "kyyyyyyyyyyyyyyk",
      ".kyyyyyyyyyyyyk.",
      "..kyyykyykyyyk..",
      "...kyyyyyyyyk...",
      "...kpyyyyyypk...",
      "..kyyyyyyyyyyk..",
      ".kyyyyykkyyyyyk.",
      ".kyyykk..kkyyyk.",
      "kyykk......kkyyk",
      "kkk..........kkk",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "...............kk...............",
      "..............kyyk..............",
      "..............kyyk..............",
      "..............kyyk..............",
      ".............kyyyyk.............",
      ".............kyyyyk.............",
      "............kyyyyyyk............",
      "............kyyyyyyk............",
      "............kyyyyyyk............",
      "..kkkkkkkkkkyyyyyyyykkkkkkkkkk..",
      ".kyyyyyyyyyyyyyyyyyyyyyyyyyyyyk.",
      "..kyyyyyyyyyyyyyyyyyyyyyyyyyyk..",
      "...kyyyyyyyyyyyyyyyyyyyyyyyyk...",
      "....kkyyyyyywkyyyywkyyyyyykk....",
      "......kyyyyykkyyyykkyyyyyk......",
      ".......kyyyykkyyyykkyyyyk.......",
      "........kpppykyyyykypppk........",
      ".........pppyykkkkyyppp.........",
      "........kyyyyyyyyyyyyyyk........",
      "........kyyyyyyyyyyyyyyk........",
      "........kyyyyyyyyyyyyyyk........",
      "........kyyyyyyyyyyyyyyk........",
      ".......kyyyyyykkkkyyyyyyk.......",
      ".......kyyyyyk....kyyyyyk.......",
      ".......kyyykk......kkyyyk.......",
      ".......kyyk..........kyyk.......",
      "......kykk............kkyk......",
      ".......k................k.......",
      "................................",
      "................................",
    ],
  },
  {
    id: "house",
    name: "집",
    aliases: ["house", "home", "우리집"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff6b6b",
      y: "#fff3c4",
      b: "#b8773a",
      l: "#7ec8e3",
    },
    rows: [
      ".......kk.......",
      "......krrk......",
      ".....krrrrk.....",
      "....krrrrrrk....",
      "...krrrrrrrrk...",
      "..krrrrrrrrrrk..",
      ".kkkkkkkkkkkkkk.",
      "..kyyyyyyyyyyk..",
      "..kykkkyykkkyk..",
      "..kyklkyyklkyk..",
      "..kykkkyykkkyk..",
      "..kyyykkkkyyyk..",
      "..kyyykbbkyyyk..",
      "..kyyykbbkyyyk..",
      "..kkkkkkkkkkkk..",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "...............kk...............",
      "..............krrk...kkkk.......",
      ".............krrrrk.kbbbbk......",
      "............krrrrrrkkbbbbk......",
      "...........krrrrrrrrkbbbbk......",
      "..........krrrrrrrrrrkbbbk......",
      ".........krrrrrrrrrrrrkbbk......",
      "........krrrrrkkkkrrrrrkbk......",
      ".......krrrrrkllllkrrrrrkk......",
      "......krrrrrrkllllkrrrrrrk......",
      ".....krrrrrrrkllllkrrrrrrrk.....",
      "....krrrrrrrrrkkkkrrrrrrrrrk....",
      "...krrrrrrrrrrrrrrrrrrrrrrrrk...",
      "..krrrrrrrrrrrrrrrrrrrrrrrrrrk..",
      ".krrrrrrrrrrrrrrrrrrrrrrrrrrrrk.",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      ".....kyyyyyyyyyyyyyyyyyyyyk.....",
      ".....kyykkkyyyyyyyyyykkkyyk.....",
      ".....kyklklkykkkkkkyklklkyk.....",
      ".....kykkkkkkbbbbbbkkkkkkyk.....",
      ".....kyklklkkbbbbbbkklklkyk.....",
      ".....kyklklkkbbbbbbkklklkyk.....",
      ".....kyykkkykbbbbbbkykkkyyk.....",
      ".....kyyyyyykbbbbbbkyyyyyyk.....",
      ".....kyyyyyykbbbbybkyyyyyyk.....",
      ".....kyyyyyykbbbbbbkyyyyyyk.....",
      ".....kyyyyyykbbbbbbkyyyyyyk.....",
      ".....kyyyyyykbbbbbbkyyyyyyk.....",
      ".....kyyyyyykbbbbbbkyyyyyyk.....",
      "......kkkkkkkkkkkkkkkkkkkk......",
    ],
  },
  {
    id: "crown",
    name: "왕관",
    aliases: ["crown", "왕", "공주"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
      r: "#ff4d5e",
      b: "#4d96ff",
      d: "#f2b82e",
    },
    rows: [
      "................",
      "................",
      ".k.....kk.....k.",
      "kyk...kyyk...kyk",
      "kyyk.kyyyyk.kyyk",
      "kyyykyyyyyykyyyk",
      "kyyyyyyyyyyyyyyk",
      "kyyyyyyyyyyyyyyk",
      "kyyryyybbyyyryyk",
      "kyyyyyyyyyyyyyyk",
      "kkkkkkkkkkkkkkkk",
      "kyyyyyyyyyyyyyyk",
      "kkkkkkkkkkkkkkkk",
      "................",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "..............kkkk..............",
      ".............kyyyyk.............",
      ".............kyyyyk.............",
      "...k.........kyyyyk.........k...",
      "..kyk........kyyyyk........kyk..",
      ".kyyyk........kkkk........kyyyk.",
      "kyyyyyk.......kyyk.......kyyyyyk",
      ".kyyyk.......kyyyyk.......kyyyk.",
      "..kyk........kyyyyk........kyk..",
      "..kkk.......kyyyyyyk.......kkk..",
      "..kyyk.....kyyyyyyyyk.....kyyk..",
      "..kyyyk....kyyyyyyyyk....kyyyk..",
      "..kyyyyk..kyyyyyyyyyyk..kyyyyk..",
      "..kyyyyykkyyyyyyyyyyyykkyyyyyk..",
      "..kyyyyyykyyyykkkkyyyykyyyyyyk..",
      "..kyyyyyyyyyykrrrrkyyyyyyyyyyk..",
      "..kyyyykkkyyykrrrrkyyykkkyyyyk..",
      "..kyyykbbbkyykrrrrkyykbbbkyyyk..",
      "..kyyykbbbkyykrrrrkyykbbbkyyyk..",
      "..kyyykbbbkyyykkkkyyykbbbkyyyk..",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "..kyyyyyyyyyyyyyyyyyyyyyyyyyyk..",
      "..kyyyyyyyyyyyyyyyyyyyyyyyyyyk..",
      "..kddddddddddddddddddddddddddk..",
      "..kyyyyyyyyyyyyyyyyyyyyyyyyyyk..",
      "..kyyyyyyyyyyyyyyyyyyyyyyyyyyk..",
      "...kkkkkkkkkkkkkkkkkkkkkkkkkk...",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "gift",
    name: "선물",
    aliases: ["gift", "선물상자", "present"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a6e",
      y: "#ffd93d",
      d: "#f2b82e",
    },
    rows: [
      "................",
      "...kk..kk..kk...",
      "..kyyk.kk.kyyk..",
      "..kyyykkkkyyyk..",
      "...kkkkyykkkk...",
      "kkkkkkkyykkkkkkk",
      "krrrrrryyrrrrrrk",
      "krrrrrryyrrrrrrk",
      "kkkkkkkyykkkkkkk",
      ".krrrrryyrrrrrk.",
      ".krrrrryyrrrrrk.",
      ".krrrrryyrrrrrk.",
      ".krrrrryyrrrrrk.",
      ".krrrrryyrrrrrk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
    rows32: [
      "................................",
      ".......kkkk..........kkkk.......",
      "......kyyyykk......kkyyyyk......",
      ".....kyyyyyyyk....kyyyyyyyk.....",
      ".....kyyyyyyyyk..kyyyyyyyyk.....",
      "......kyyddddykkkkyddddyyk......",
      ".......kyyyyykyyyykyyyyyk.......",
      "........kyyyykyyyykyyyyk........",
      "..kkkkkkkkkyykyyyykyykkkkkkkkk..",
      ".krrrrrrrrrkkkyyyykkkrrrrrrrrrk.",
      ".krrrrrrrrrrrrkkkkrrrrrrrrrrrrk.",
      ".krrrrrrrrrrrryyyyrrrrrrrrrrrrk.",
      ".krrrrrrrrrrrryyyyrrrrrrrrrrrrk.",
      ".krrrrrrrrrrrryyyyrrrrrrrrrrrrk.",
      ".krrkkkkkkkkkkkkkkkkkkkkkkkkrrk.",
      "..kkkkkkkkkkkkyyyykkkkkkkkkkkk..",
      "...krrrrrrrrrryyyyrrrrrrrrrrk...",
      "...krrrrrrrrrryyyyrrrrrrrrrrk...",
      "...krrrrrrrrrryyyyrrrrrrrrrrk...",
      "...krrrrrrrrrryyyyrrrrrrrrrrk...",
      "...krrrrrrrrrryyyyrrrrrrrrrrk...",
      "...krrrrrrrrrryyyyrrrrrrrrrrk...",
      "...krrrrrrrrrryyyyrrrrrrrrrrk...",
      "...krrrrrrrrrryyyyrrrrrrrrrrk...",
      "...krrrrrrrrrryyyyrrrrrrrrrrk...",
      "...krrrrrrrrrryyyyrrrrrrrrrrk...",
      "...krrrrrrrrrryyyyrrrrrrrrrrk...",
      "...krrrrrrrrrryyyyrrrrrrrrrrk...",
      "...krrrrrrrrrryyyyrrrrrrrrrrk...",
      "...krrrrrrrrrryyyyrrrrrrrrrrk...",
      "...krrrrrrrrrryyyyrrrrrrrrrrk...",
      "....kkkkkkkkkkkkkkkkkkkkkkkk....",
    ],
  },
  {
    id: "balloon",
    name: "풍선",
    aliases: ["balloon", "파티"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a6e",
      h: "#ffc2cb",
    },
    rows: [
      "................",
      ".....kkkkkk.....",
      "....krrrrrrk....",
      "...krhhrrrrrk...",
      "...krhrrrrrrk...",
      "...krrrrrrrrk...",
      "...krrrrrrrrk...",
      "....krrrrrrk....",
      ".....krrrrk.....",
      "......krrk......",
      ".......kk.......",
      "........k.......",
      ".......k........",
      "........k.......",
      ".......k........",
      "................",
    ],
    rows32: [
      ".............kkkkkk.............",
      "...........kkrrrrrrkk...........",
      "..........krrrrrrrrrrk..........",
      ".........krrrrrrrrrrrrk.........",
      "........krrrrrrrrrrrrrrk........",
      ".......krrrhrrrrrrrrrrrrk.......",
      "......krrrhhhrrrrrrrrrrrrk......",
      "......krrrhhhrrrrrrrrrrrrk......",
      "......krrrhhhrrrrrrrrrrrrk......",
      ".....krrrrhhhrrrrrrrrrrrrrk.....",
      ".....krrrrrhrrrrrrrrrrrrrrk.....",
      ".....krrrrrrrrrrrrrrrrrrrrk.....",
      ".....krrrrrrrrrrrrrrrrrrrrk.....",
      ".....krrrrrrrrrrrrrrrrrrrrk.....",
      ".....krrrrrrrrrrrrrrrrrrrrk.....",
      ".....krrrrrrrrrrrrrrrrrrrrk.....",
      "......krrrrrrrrrrrrrrrrrrk......",
      "......krrrrrrrrrrrrrrrrrrk......",
      "......krrrrrrrrrrrrrrrrrrk......",
      ".......krrrrrrrrrrrrrrrrk.......",
      "........krrrrrrrrrrrrrrk........",
      ".........krrrrrrrrrrrrk.........",
      "..........krrrrkkrrrrk..........",
      "...........kkrkrrkrkk...........",
      ".............krrrrk.............",
      "..............kkkk..............",
      "..............kkk...............",
      ".............kkkk...............",
      "..............kkkk..............",
      "...............kkkk.............",
      "...............kkk..............",
      "..............kkk...............",
    ],
  },
  {
    id: "rocket",
    name: "로켓",
    aliases: ["rocket", "우주", "우주선"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a6e",
      l: "#7ec8e3",
      o: "#ff9f1c",
      y: "#ffd93d",
    },
    rows: [
      ".......kk.......",
      "......krrk......",
      ".....krrrrk.....",
      ".....kwwwwk.....",
      "....kwwwwwwk....",
      "....kwkkkkwk....",
      "....kwkllkwk....",
      "....kwkkkkwk....",
      "....kwwwwwwk....",
      "...krwwwwwwrk...",
      "..krrwwwwwwrrk..",
      "..krrkkkkkkrrk..",
      "..kk.kyooyk.kk..",
      ".......yy.......",
      "................",
      "................",
    ],
    rows32: [
      "..............kkkk..............",
      ".............krrrrk.............",
      "............krrrrrrk............",
      "...........krrrrrrrrk...........",
      "...........krrrrrrrrk...........",
      "..........krrrrrrrrrrk..........",
      "..........krrrrrrrrrrk..........",
      "..........kwwwwwwwwwwk..........",
      "..........kwwwwwwwwwwk..........",
      ".........kwwwwkkkkwwwwk.........",
      ".........kwwwkllllkwwwk.........",
      ".........kwwkllllllkwwk.........",
      ".........kwwkllwlllkwwk.........",
      ".........kwwkllllllkwwk.........",
      ".........kwwkllllllkwwk.........",
      ".........kwwwkllllkwwwk.........",
      ".........kwwwwkkkkwwwwk.........",
      ".........kwwwwwwwwwwwwk.........",
      "........kkwwwwwwwwwwwwkk........",
      ".......krkwwwwkkkkwwwwkrk.......",
      ".......krkwwwkrrrrkwwwkrk.......",
      "......krrkwwwkrrrrkwwwkrrk......",
      "......krrkwwwkrrrrkwwwkrrk......",
      ".....krrrkwwwkrrrrkwwwkrrrk.....",
      "....krrrrkwwwkrrrrkwwwkrrrrk....",
      "....krrrrkwwwkrrrrkwwwkrrrrk....",
      "....krrrkkkkkkrrrrkkkkkkrrrk....",
      "....krkk....kokkkkok....kkrk....",
      ".....k.......koyyok.......k.....",
      "..............kook..............",
      "..............kook..............",
      "...............kk...............",
    ],
  },
  {
    id: "car",
    name: "자동차",
    aliases: ["car", "차", "붕붕", "버스", "bus"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a6e",
      l: "#bde4ff",
      y: "#ffd93d",
      g: "#8a8a8a",
    },
    rows: [
      "................",
      "................",
      "................",
      "................",
      "....kkkkkkkk....",
      "...krrrrrrrrk...",
      "..krlllkklllrk..",
      ".krrrrrrrrrrrrk.",
      "krrrrrrrrrrrrrrk",
      "kyrrrrrrrrrrrryk",
      "krkkkrrrrrrkkkrk",
      ".kkgkkkkkkkkgkk.",
      "..kkk......kkk..",
      "................",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "...........kkkkkkkkkk...........",
      "..........krrrrrrrrrrk..........",
      ".........krrrrrrrrrrrrk.........",
      ".........krrlllrrlllrrk.........",
      ".........krrlllrrllllrrk........",
      "........krrllllrrllllrrk........",
      "........krrllllrrlllllrrk.......",
      "...kkkkkkkkkkkkkkkkkkkkkkkkkk...",
      "..krrrrrrrrrrrrrrrrrrrrrrrrrrk..",
      ".krrrrrrrrrrrrrrrrrrrrrrrrrrrrk.",
      ".krrrrrrrrrrrrrrrrrrrrrrrrryyrk.",
      ".krrrrrrrrrrrrrrrrrrrrrrrrryyrk.",
      ".krrrrrrkrrrrrrrrrrrrrrkrrrrrrk.",
      ".krkkkkkgkkkkkkkkkkkkkkgkkkkkrk.",
      ".krrrkgggggkrrrrrrrrkgggggkrrrk.",
      ".krrkgggggggkrrrrrrkgggggggkrrk.",
      ".krrkggwwwggkrrrrrrkggwwwggkrrk.",
      "..kkkggwwwggkkkkkkkkggwwwggkkk..",
      "....kgggggggk......kgggggggk....",
      ".....kgggggk........kgggggk.....",
      "......kkgkk..........kkgkk......",
      "........k..............k........",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "airplane",
    name: "비행기",
    aliases: ["airplane", "plane", "여행"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#7ec8e3",
      l: "#4d96ff",
    },
    rows: [
      ".......kk.......",
      "......kwwk......",
      "......kwwk......",
      "......kllk......",
      "......kwwk......",
      "...kkkkwwkkkk...",
      ".kkbbbbwwbbbbkk.",
      "kbbbbbbwwbbbbbbk",
      "kkkkkkkwwkkkkkkk",
      "......kwwk......",
      "......kwwk......",
      "....kkkwwkkk....",
      "...kbbbwwbbbk...",
      "...kkkkkkkkkk...",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "...............kk...............",
      "..............kwwk..............",
      "..............kwwk..............",
      ".............kwwwwk.............",
      ".............kwllwk.............",
      ".............kwllwk.............",
      ".............kwwwwk.............",
      ".............kwwwwk.............",
      "............kwwwwwwk............",
      "............kwwllwwk............",
      "............kwwwwwwk............",
      "...........kkwwwwwwkk...........",
      "........kkkbkwwllwwkbkkk........",
      ".....kkkbbbbkwwwwwwkbbbbkkk.....",
      "..kkkbbbbbbbkwwwwwwkbbbbbbbkkk..",
      ".kbbbbbbbbbbkwwllwwkbbbbbbbbbbk.",
      "kbbbbbbbbbbbkwwwwwwkbbbbbbbbbbbk",
      "kbbbbbbbkkkkkwwwwwwkkkkkbbbbbbbk",
      "kbbkkkkk....kwwllwwk....kkkkkbbk",
      ".kk.........kwwwwwwk.........kk.",
      "............kwwwwwwk............",
      "............kwwwwwwk............",
      ".............kwwwwk.............",
      ".............kwwwwk.............",
      "............kkwwwwkk............",
      "...........kbkwwwwkbk...........",
      "..........kbbkwwwwkbbk..........",
      ".........kbbbbkwwkbbbbk.........",
      ".........kbbkkkwwkkkbbk.........",
      "..........kk...kk...kk..........",
      "................................",
    ],
  },
  {
    id: "umbrella",
    name: "우산",
    aliases: ["umbrella", "비", "장마", "rain"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a6e",
      y: "#ffd93d",
    },
    rows: [
      "................",
      "................",
      "....kkkkkkkk....",
      "..kkrryyyyrrkk..",
      ".krrryyyyyyrrrk.",
      "krrrryyyyyyrrrrk",
      "krrrryyyyyyrrrrk",
      "kkkkkkkkkkkkkkkk",
      ".......kk.......",
      ".......kk.......",
      ".......kk.......",
      ".......kk.......",
      ".......kk.......",
      ".......kk.......",
      "................",
      "................",
    ],
    rows32: [
      "..............kkkk..............",
      "...........kkkkkkkkkk...........",
      ".........kkrrrkkkkrrrkk.........",
      ".......kkrrrrrrkkrrrrrrkk.......",
      "......krrrrrrrryyrrrrrrrrk......",
      ".....krrrrrrrrryyrrrrrrrrrk.....",
      "....krrrrrrrrryyyrrrrrrrrrrk....",
      "...krrrrrrrrrryyyyrrrrrrrrrrk...",
      "...krrrrrrrrrryyyyrrrrrrrrrrk...",
      "..krrrrrrrrrryyyyyrrrrrrrrrrrk..",
      "..krrrrrrrrrryyyyyyrrrrrrrrrrk..",
      ".krrrrrrrrrrryyyyyyrrrrrrrrrrrk.",
      ".krrrrrrrrrryyyyyyyrrrrrrrrrrrk.",
      ".krrrrrrrrrryyyyyyyyrrrrrrrrrrk.",
      ".krrrrrrrrrryyyyyyyyrrrrrrrrrrk.",
      ".krrrrrrrrryyyyyyyyyrrrrrrrrrrk.",
      ".krrkkkrrrrkkkkyykkkkrrrrkkkrrk.",
      "..kk...kkkk....kkk...kkkk...kk..",
      "...............kkk..............",
      "...............kkk..............",
      "...............kkk..............",
      "...............kkk..............",
      "...............kkk..............",
      "...............kkk..............",
      "...............kkk..............",
      "...............kkk..............",
      "...........k...kkk..............",
      "..........kkk..kkk..............",
      "...........kkkkkk...............",
      "...........kkkkk................",
      "............kkk.................",
      "................................",
    ],
  },
  {
    id: "music",
    name: "음표",
    aliases: ["music", "노래", "음악", "note"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#8e5bd6",
    },
    rows: [
      "................",
      "....kkkkkkkkk...",
      "....kppppppkk...",
      "....kkkkkkkkk...",
      "....k.......k...",
      "....k.......k...",
      "....k.......k...",
      "....k.......k...",
      "..kkk.....kkk...",
      ".kpppk...kpppk..",
      ".kpppk...kpppk..",
      "..kkk.....kkk...",
      "................",
      "................",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      ".......................kk.......",
      "....................kkkkkk......",
      "................kkkkkkkkkkk.....",
      ".............kkkkkkkkkkkkkk.....",
      "...........kkkkkkkkkkkkkkkk.....",
      "..........kkkkkkkkkkkkkkkkk.....",
      "..........kkkkkkkkkkkkkkkkk.....",
      "..........kkkkkkkkkkkkkkkkk.....",
      "..........kkkkkkkkkk...kkkk.....",
      "..........kkkkkk.......kkkk.....",
      "..........kkkk.........kkkk.....",
      "..........kkkk.........kkkk.....",
      "..........kkkk.........kkkk.....",
      "..........kkkk.........kkkk.....",
      "..........kkkk.........kkkk.....",
      "..........kkkk.........kkkk.....",
      "..........kkkk.........kkkk.....",
      "..........kkkk.....kkkkkkkk.....",
      "..........kkkk....kpppppkkk.....",
      "..........kkkk...kppwppppkk.....",
      "......kkkkkkkk..kppppppppk......",
      ".....kpppppkkk..kpppppppk.......",
      "....kppwppppkk...kpppppk........",
      "...kppppppppk.....kkkkk.........",
      "...kpppppppk....................",
      "....kpppppk.....................",
      ".....kkkkk......................",
      "................................",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "ball",
    name: "공",
    aliases: ["ball", "농구공", "농구", "축구공", "축구", "운동"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      o: "#f28c38",
    },
    rows: [
      "................",
      "................",
      "....kkkkkkkk....",
      "..kkoookkoookk..",
      ".kooookookooook.",
      ".kooookookooook.",
      "kkooookookooookk",
      "kokkkkkkkkkkkkok",
      "kookoookkoookook",
      "koooookookoooook",
      "koooookookoooook",
      ".kooookookooook.",
      ".kooookookooook.",
      "..kkoookkoookk..",
      "....kkkkkkkk....",
      "................",
    ],
    rows32: [
      "................................",
      "............kkkkkkkk............",
      "..........kkoookkoookk..........",
      "........kkoooookkoooookk........",
      ".......koooooookkoooooook.......",
      "......kooooooookkooooooook......",
      ".....koooooooookkoooooooook.....",
      "....kkkoowwooookkooooooookkk....",
      "...kookkowwooookkoooooookkook...",
      "...koookoooooookkoooooookoook...",
      "..koooookooooookkooooookoooook..",
      "..koooookooooookkooooookoooook..",
      ".kooooookkoooookkoooookkooooook.",
      ".koooooookoooookkoooookoooooook.",
      ".koooooookoooookkoooookoooooook.",
      ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
      ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
      ".koooooookoooookkoooookoooooook.",
      ".koooooookoooookkoooookoooooook.",
      ".kooooookkoooookkoooookkooooook.",
      "..koooookooooookkooooookoooook..",
      "..koooookooooookkooooookoooook..",
      "...koookoooooookkoooooookoook...",
      "...kookkoooooookkoooooookkook...",
      "....kkkooooooookkooooooookkk....",
      ".....koooooooookkoooooooook.....",
      "......kooooooookkooooooook......",
      ".......koooooookkoooooook.......",
      "........kkoooookkoooookk........",
      "..........kkoookkoookk..........",
      "............kkkkkkkk............",
      "................................",
    ],
  },
  {
    id: "diamond",
    name: "보석",
    aliases: ["diamond", "다이아몬드", "다이아", "반지"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      l: "#bde4ff",
      b: "#4d96ff",
    },
    rows: [
      "................",
      "................",
      "................",
      "..kkkkkkkkkkkk..",
      ".kllwllbbllwllk.",
      "kkkkkkkkkkkkkkkk",
      ".kbbbllllllbbbk.",
      "..kbbbllllbbbk..",
      "...kbbllllbbk...",
      "....kbbllbbk....",
      ".....kbllbk.....",
      "......kbbk......",
      ".......kk.......",
      "................",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "................................",
      "........kkkkkkkkkkkkkkkk........",
      ".......kklllllllklllllllk.......",
      "......klkllllllklkllllllkk......",
      ".....klllklllwlklklllllkllk.....",
      "....kllllkllllklllkllllklllk....",
      "...kllwlllkllklllllkllklllllk...",
      "..kllwllllklklllllllklkllllllk..",
      ".klllllllllkklllllllkkllllllllk.",
      ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
      "..kbbbbbbbbllllllllllbbbbbbbbk..",
      "...kbbbbbbbllllllllllbbbbbbbk...",
      "...kbbbbbbbllllllllllbbbbbbbk...",
      "....kbbbbbbbllllllllbbbbbbbk....",
      ".....kbbbbbbllllllllbbbbbbk.....",
      "......kbbbbbllllllllbbbbbk......",
      ".......kbbbbbllllllbbbbbk.......",
      "........kbbbbllllllbbbbk........",
      ".........kbbbllllllbbbk.........",
      ".........kbbbbllllbbbbk.........",
      "..........kbbbllllbbbk..........",
      "...........kbbllllbbk...........",
      "............kbbllbbk............",
      ".............kbllbk.............",
      "..............kllk..............",
      "...............kk...............",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "ribbon",
    name: "리본",
    aliases: ["ribbon", "bow", "나비넥타이"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#ff8fb1",
      d: "#ff6f9c",
    },
    rows: [
      "................",
      "................",
      "................",
      "................",
      "kk............kk",
      "kpkk........kkpk",
      "kpppk.kkkk.kpppk",
      "kppppkppppkppppk",
      "kppppkppppkppppk",
      "kpppk.kkkk.kpppk",
      "kkk..kpkkpk..kkk",
      ".....kpkkpk.....",
      "....kpk..kpk....",
      "....kk....kk....",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "...k........................k...",
      "..kpk......................kpk..",
      ".kpppkk..................kkpppk.",
      ".kpppppk................kpppppk.",
      ".kppppppkk............kkppppppk.",
      "kppppddpppk..........kpppddppppk",
      "kpppddddpppkk.kkkk.kkpppddddpppk",
      "kpppddddddpppkppppkpppddddddpppk",
      "kpppdddddddpkppppppkpdddddddpppk",
      ".kppddddddddkppppppkddddddddppk.",
      ".kppddddddddkppppppkddddddddppk.",
      ".kpppdddddppkppppppkppdddddpppk.",
      ".kpppddpppppkppppppkpppppddpppk.",
      ".kppppppppkkkkppppkkkkppppppppk.",
      "..kppppkkk..kpkkkkpk..kkkppppk..",
      "..kpkkk.....kpk..kpk.....kkkpk..",
      "...k.......kppk..kppk.......k...",
      "...........kppk..kppk...........",
      "..........kpppk..kpppk..........",
      "..........kpppk..kpppk..........",
      "..........kppppkkppppk..........",
      ".........kpppppkkpppppk.........",
      ".........kpppppkkpppppk.........",
      "........kppkkppkkppkkppk........",
      ".........kk..kpkkpk..kk.........",
      "..............k..k..............",
      "................................",
    ],
  },
  {
    id: "pencil",
    name: "연필",
    aliases: ["pencil", "펜", "색연필"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
      d: "#f2b82e",
      t: "#f0cfa8",
      h: "#ffc2cb",
      g: "#b8bcc6",
    },
    rows: [
      "............kkk.",
      "...........khhhk",
      "..........khhhhk",
      ".........kgkhhk.",
      "........kyygkk..",
      ".......kyyydk...",
      "......kyyydk....",
      ".....kyyydk.....",
      "....kyyydk......",
      "...kyyydk.......",
      "..ktyydk........",
      "..kttdk.........",
      ".kttkk..........",
      ".kkkk...........",
      "kkk.............",
      "................",
    ],
    rows32: [
      "..........................kk....",
      ".........................khhk...",
      "........................khhhhk..",
      ".......................kkhhhhhk.",
      "......................kggkhhhhhk",
      ".....................kkgggkhhhhk",
      "....................kyykgggkhhk.",
      "...................kyyyykgggkk..",
      "..................kyyyyydkggk...",
      ".................kyyyyydddkk....",
      "................kyyyyyddddk.....",
      "...............kyyyyyddddk......",
      "..............kyyyyyddddk.......",
      ".............kyyyyyddddk........",
      "............kyyyyyddddk.........",
      "...........kyyyyyddddk..........",
      "..........kyyyyyddddk...........",
      ".........kyyyyyddddk............",
      "........kyyyyyddddk.............",
      ".......kkyyyyddddk..............",
      ".......ktkyyddddk...............",
      "......ktttkddddk................",
      "......kttttkddk.................",
      ".....kttttttkk..................",
      "....kttttttkk...................",
      "....kktttkk.....................",
      "...ktkktk.......................",
      "...kktkk........................",
      "..kkkk..........................",
      "...k............................",
      "................................",
      "................................",
    ],
  },
  {
    id: "book",
    name: "책",
    aliases: ["book", "공책", "노트", "동화책"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#5b9df0",
      y: "#ffd93d",
      g: "#dde3ea",
      d: "#f2b82e",
    },
    rows: [
      "................",
      "................",
      "..kkkkkkkkkkkk..",
      ".kbbbbbbbbbbbbk.",
      ".kbbbbbbbbbbbbk.",
      ".kbbkkkkkkkkbbk.",
      ".kbbkyyyyyykbbk.",
      ".kbbkkkkkkkkbbk.",
      ".kbbbbbbbbbbbbk.",
      ".kbbbbbbbbbbbbk.",
      ".kbbbbbbbbbbbbk.",
      ".kbbbbbbbbbbbbk.",
      ".kkkkkkkkkkkkkk.",
      ".kwgwgwgwgwgwgk.",
      "..kkkkkkkkkkkkk.",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "...kkkkkkkkkkkkkkkkkkkkkkkkkk...",
      "..kbbkbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbkbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbkbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbkbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbkbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbkbbbbkkkkkkkkkkkkkkbbbbbk..",
      "..kbbkbbbkyyyyyyyyyyyyyykbbbbk..",
      "..kbbkbbbkyyyyyyyyyyyyyykbbbbk..",
      "..kbbkbbbkyyddddddddddyykbbbbk..",
      "..kbbkbbbkyyyyyyyyyyyyyykbbbbk..",
      "..kbbkbbbkyyyyyyyyyyyyyykbbbbk..",
      "..kbbkbbbbkkkkkkkkkkkkkkbbbbbk..",
      "..kbbkbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbkbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbkbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbkbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbkbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbkbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbkbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbkbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbkbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbkbbbbbbbbbbbbbbbbbbbbbbbk..",
      "..kbbkbbbbbbbbbbbbbbbbbbbbbbbk..",
      "...kkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "...kwwwwwwwwwwwwwwwwwwwwwwwwwk..",
      "...kgggggggggggggggggggggggggk..",
      "...kwwwwwwwwwwwwwwwwwwwwwwwwwk..",
      "....kkkkkkkkkkkkkkkkkkkkkkkkk...",
      "................................",
    ],
  },
  {
    id: "camera",
    name: "카메라",
    aliases: ["camera", "사진기", "사진"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      g: "#8a93a3",
      l: "#dde3ea",
      c: "#6fb6ff",
      r: "#ff5a6e",
    },
    rows: [
      "................",
      "................",
      "................",
      "..kkk..kkkkk....",
      ".krrk.kgggggk...",
      "kkkkkkkkkkkkkkkk",
      "kggggggkkkkggggk",
      "kgggggkccwckgggk",
      "klllllkcwcckllwk",
      "klllllkccccklllk",
      "kgggggkcccckgggk",
      "kggggggkkkkggggk",
      "kkkkkkkkkkkkkkkk",
      "................",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "................................",
      "....kkkkkk.kkkkkkkkkkk..........",
      "...krrrrrrkgggggggggggk.........",
      "...krrrrrrkgggggggggggk.........",
      "...krrrrrrkgggggggggggk.........",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      ".kgggggggggggkkkkkkgggggggggggk.",
      "kgggggggggggkggggggkgggggggggggk",
      "kggggggggggkggggggggkggggwwwgggk",
      "kgggggggggkggkkkkkkggkgggwwwgggk",
      "kggggggggkggkcccccckggkggggggggk",
      "klllllllkggkccwwcccckggklllllllk",
      "klllllllkggkccwwcccckggklllllllk",
      "klllllllkggkcccccccckggklllllllk",
      "klllllllkggkcccccccckggklllllllk",
      "klllllllkggkcccccccckggklllllllk",
      "klllllllkggkcccccccckggklllllllk",
      "kllllllllkggkcccccckggkllllllllk",
      "klllllllllkggkkkkkkggklllllllllk",
      "kggggggggggkggggggggkggggggggggk",
      "kgggggggggggkggggggkgggggggggggk",
      "kggggggggggggkkkkkkggggggggggggk",
      "kggggggggggggggggggggggggggggggk",
      "kggggggggggggggggggggggggggggggk",
      ".kggggggggggggggggggggggggggggk.",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "letter",
    name: "편지",
    aliases: ["편지봉투", "봉투", "letter", "mail", "메일"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      c: "#fff4d6",
      r: "#ff5a6e",
    },
    rows: [
      "................",
      "................",
      "................",
      "kkkkkkkkkkkkkkkk",
      "kkcccccccccccckk",
      "kckcccccccccckck",
      "kcckcccccccckcck",
      "kccckcccccckccck",
      "kcccckcccckcccck",
      "kccccckrrkccccck",
      "kcccccrrrrccccck",
      "kccccccrrcccccck",
      "kkkkkkkkkkkkkkkk",
      "................",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
      "kkcccccccccccccccccccccccccccckk",
      "kckcccccccccccccccccccccccccckck",
      "kcckkcccccccccccccccccccccckkcck",
      "kcccckcccccccccccccccccccckcccck",
      "kccccckcccccccccccccccccckccccck",
      "kcccccckkcccccccccccccckkcccccck",
      "kcccccccckcccccccccccckcccccccck",
      "kccccccccckcccccccccckccccccccck",
      "kcccccccccckcccccccckcccccccccck",
      "kccccccccccckkkcckkkccccccccccck",
      "kccccccccccckrrkkrrkccccccccccck",
      "kcccccccccckrrrrrrrrkcccccccccck",
      "kcccccccccckrrrrrrrrkcccccccccck",
      "kccccccccccckrrrrrrkccccccccccck",
      "kcccccccccccckrrrrkcccccccccccck",
      "kccccccccccccckrrkccccccccccccck",
      "kcccccccccccccckkcccccccccccccck",
      "kcccccccccccccccccccccccccccccck",
      "kcccccccccccccccccccccccccccccck",
      "kcccccccccccccccccccccccccccccck",
      ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
      "................................",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "key",
    name: "열쇠",
    aliases: ["key", "키"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
      d: "#f2b82e",
    },
    rows: [
      "................",
      "................",
      "................",
      "..kkkk..........",
      ".kyyyyk.........",
      "kyykkyyk........",
      "kykk.kykkkkkkkk.",
      "kyk..kyyyyyyyyyk",
      "kykk.kydddddddk.",
      "kyykkyydkkdkdk..",
      ".kyyyydk.kk.k...",
      "..kkkkk.........",
      "................",
      "................",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      ".....kkkkkk.....................",
      "....kyyyyyyk....................",
      "...kyyyyyyyyk...................",
      "..kyyyyyyyyyyk..................",
      ".kywwwwkkyyyyyk.................",
      "kyyyyykddkyyyyykkkkkkkkkkkkkkk..",
      "kyyyykd..dkyyyykyyyyyyyyyyyyyyk.",
      "kyyykd....dkyyykyyyyyyyyyyyyyyk.",
      "kyyykd....dkyyykyyyyyyyyyyyyyyk.",
      "kyyyykd..dkyyyykyyyyyyyyyyyyyyk.",
      "kyyyyykddkyyyyykyyyyyyyyyyyyyyk.",
      ".kyyyyykkyyyyykkkkkkkyyykkyyyk..",
      "..kyyyyyyyyyyk......kyyykkyyyk..",
      "...kyyyyyyyyk.......kyyykkyyyk..",
      "....kyyyyyyk........kyyykkyyyk..",
      ".....kkkkkk..........kkk.kyyyk..",
      "..........................kkk...",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "gamepad",
    name: "게임기",
    aliases: ["게임", "게임패드", "조이스틱", "game", "컨트롤러"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#b28cf0",
      r: "#ff5a6e",
      y: "#ffd93d",
    },
    rows: [
      "................",
      "................",
      "................",
      "..kkkkkkkkkkkk..",
      ".kppppppppppppk.",
      "kppkpppppppprppk",
      "kpkkkpppppypprpk",
      "kppkppppppppyppk",
      "kppppppppppppppk",
      "kpppppkkkkpppppk",
      "kppppk....kppppk",
      ".kkkk......kkkk.",
      "................",
      "................",
      "................",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "......kkkkkkkkkkkkkkkkkkkk......",
      ".....kppppppppppppppppppppk.....",
      "...kkpppppppppppppppppkkppkk....",
      "..kppppppppppppppppppkrrkpppk...",
      ".kpppppppppppppppppppkrrkppppk..",
      ".kppppppkkpppppppppkkpkkpkkppk..",
      "kpppppppkkppppppppkyykppkyykppk.",
      "kpppppkkkkkkppppppkyykppkyykppk.",
      "kpppppkkkkkkpppppppkkpkkpkkpppk.",
      "kpppppppkkpppppppppppkrrkpppppk.",
      ".kppppppkkpppppppppppkrrkppppk..",
      ".kppppppppppppppppppppkkpppppk..",
      ".kpppppppppppppppppppppppppppk..",
      ".kppppppppkkkkkkkkkkkppppppppk..",
      ".kppppppppk.........kppppppppk..",
      ".kppppppppk..........kpppppppk..",
      "..kppppppk...........kppppppk...",
      "...kkkkkk.............kkkkkk....",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
    ],
  },
  {
    id: "trophy",
    name: "트로피",
    aliases: ["trophy", "우승", "상", "1등"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
      d: "#f2b82e",
      b: "#a0673c",
    },
    rows: [
      "................",
      "..kkkkkkkkkkkk..",
      "kkkywyyyyyyydkkk",
      "kykywyyyyyyydkyk",
      "kykywyyyyyyydkyk",
      "kykkyyyyyyyydkyk",
      ".kykyyyyyyyydkyk",
      "..kkkyyyyyyddkk.",
      "....kkyyyyddk...",
      "......kyydk.....",
      "......kyydk.....",
      ".....kkyyddk....",
      "....kbbbbbbbk...",
      "....kbbyydbbk...",
      "...kkkkkkkkkkk..",
      "................",
    ],
    rows32: [
      "................................",
      "................................",
      "........kkkkkkkkkkkkkkkk........",
      ".......kyyyyyyyyyyyyydddk.......",
      ".......kyyyyyyyyyyyyydddk.......",
      "...kkkkkyywwyyyyyyyyydddkkkk....",
      ".kkyyyykyywwyyyyyyyyydddkyyykk..",
      "kyyyyyykyywwyyyyyyyyydddkyyyyyk.",
      "kyykkkkkyywwyyyyyyyyydddkkkkyyk.",
      "yyk....kyywwyyyyyyyyydddk...kyyk",
      "yyk....kyywwyyyyyyyyyddk....kyyk",
      "yyk....kyywwyyyyyyyyyddk....kyyk",
      "yyk....kkywwyyyyyyyyydkk....kyyk",
      "kyykkkkykyyyyyyyyyyyydkykkkkyyk.",
      "kyyyyyyyykyyyyyyyyyyykyyyyyyyyk.",
      ".kkyyyykk.kyyyyyyyyyk.kkyyyykk..",
      "...kkkk....kkykkkkkk....kkkk....",
      ".............kyyyyk.............",
      ".............kyyyyk.............",
      ".............kyyyyk.............",
      ".............kyyyyk.............",
      ".............kyyyyk.............",
      ".........kkkkkkkkkkkkkk.........",
      "........kbbbbbbbbbbbbbbk........",
      "........kbbbbbbbbbbbbbbk........",
      "........kbbbyyyyyyyybbbk........",
      "........kbbbyyyyyyyybbbk........",
      "........kbbbbbbbbbbbbbbk........",
      "........kbbbbbbbbbbbbbbk........",
      "........kbbbbbbbbbbbbbbk........",
      ".........kkkkkkkkkkkkkk.........",
      "................................",
    ],
  },
];
