import type { DraftTemplate } from "@/types";

/**
 * AI 도안 라이브러리 (16×16)
 * rows의 각 글자는 palette의 색, "."은 빈 칸. 32×32 캔버스에서는 2배로 키워 사용
 */
export const DRAFT_LIBRARY: DraftTemplate[] = [
  {
    id: "heart",
    name: "하트",
    aliases: ["사랑", "love", "heart"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a6e",
      h: "#ffc2cb",
    },
    rows: [
      "................",
      "................",
      "..kkkk....kkkk..",
      ".krrrrk..krrrrk.",
      "krhhrrrkkrrrrrrk",
      "krhrrrrrrrrrrrrk",
      "krrrrrrrrrrrrrrk",
      "krrrrrrrrrrrrrrk",
      ".krrrrrrrrrrrrk.",
      "..krrrrrrrrrrk..",
      "...krrrrrrrrk...",
      "....krrrrrrk....",
      ".....krrrrk.....",
      "......krrk......",
      ".......kk.......",
      "................",
    ],
  },
  {
    id: "star",
    name: "별",
    aliases: ["star", "스타"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
      p: "#ff9eb1",
    },
    rows: [
      ".......kk.......",
      "......kyyk......",
      "......kyyk......",
      ".....kyyyyk.....",
      "kkkkkkyyyykkkkkk",
      "kyyyyyyyyyyyyyyk",
      ".kyyyyyyyyyyyyk.",
      "..kyyykyykyyyk..",
      "...kyyyyyyyyk...",
      "...kpyyyyyypk...",
      "..kyyyyyyyyyyk..",
      ".kyyyyykkyyyyyk.",
      ".kyyykk..kkyyyk.",
      "kyykk......kkyyk",
      "kkk..........kkk",
      "................",
    ],
  },
  {
    id: "cat",
    name: "고양이",
    aliases: ["냥이", "야옹이", "cat", "kitty"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      o: "#f6a04d",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      ".k............k.",
      ".kk..........kk.",
      ".kok........kok.",
      ".kookkkkkkkkook.",
      ".kooooooooooook.",
      "kooooooooooooook",
      "kooooooooooooook",
      "kookooooooookook",
      "kookooooooookook",
      "kpoooooooooooopk",
      "kooooooppooooook",
      "kooooookkooooook",
      ".kooooooooooook.",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  {
    id: "bear",
    name: "곰",
    aliases: ["곰돌이", "bear", "테디베어"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#a0673c",
      t: "#e8c39e",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      ".kkk........kkk.",
      "kbbbk......kbbbk",
      "kbtbkkkkkkkkbtbk",
      "kbbbbbbbbbbbbbbk",
      "kbbbbbbbbbbbbbbk",
      "kbbbbbbbbbbbbbbk",
      "kbbkbbbbbbbbkbbk",
      "kbbkbbbbbbbbkbbk",
      "kbbbbttttttbbbbk",
      "kbpbtttkktttbpbk",
      "kbbbttttttttbbbk",
      ".kbbbttttttbbbk.",
      "..kbbbbbbbbbbk..",
      "...kkkkkkkkkk...",
      "................",
    ],
  },
  {
    id: "rabbit",
    name: "토끼",
    aliases: ["토깽이", "rabbit", "bunny"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#ff9eb1",
    },
    rows: [
      "..kk........kk..",
      ".kwwk......kwwk.",
      ".kwpk......kpwk.",
      ".kwpk......kpwk.",
      ".kwpk......kpwk.",
      ".kwwk......kwwk.",
      ".kwwkkkkkkkkwwk.",
      "kwwwwwwwwwwwwwwk",
      "kwwwwwwwwwwwwwwk",
      "kwwkwwwwwwwwkwwk",
      "kwwkwwwwwwwwkwwk",
      "kppwwwwppwwwwppk",
      "kwwwwwwkkwwwwwwk",
      ".kwwwwwwwwwwwwk.",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  {
    id: "dog",
    name: "강아지",
    aliases: ["멍멍이", "개", "puppy", "dog"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      d: "#e2a86a",
      e: "#9c6334",
      l: "#f8e3c4",
    },
    rows: [
      "................",
      "...kkkkkkkkkk...",
      "..kddddddddddk..",
      "kkkddddddddddkkk",
      "keekddddddddkeek",
      "keekddddddddkeek",
      "keekdkddddkdkeek",
      "keekdkddddkdkeek",
      "keekdlllllldkeek",
      "keekdllkklldkeek",
      ".kkkdlllllldkkk.",
      "...kdllkklldk...",
      "...kddddddddk...",
      "....kddddddk....",
      ".....kkkkkk.....",
      "................",
    ],
  },
  {
    id: "chick",
    name: "병아리",
    aliases: ["삐약이", "chick", "새", "아기새"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
      o: "#ff9f1c",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      ".......kk.......",
      ".....kkkkkk.....",
      "....kyyyyyyk....",
      "...kyyyyyyyyk...",
      "..kyyyyyyyyyyk..",
      "..kyykyyyykyyk..",
      ".kyyykyyyykyyyk.",
      ".kyyyyooooyyyyk.",
      ".kpyyyyooyyyypk.",
      ".kyyyyyyyyyyyyk.",
      ".kyyyyyyyyyyyyk.",
      "..kyyyyyyyyyyk..",
      "...kkkkkkkkkk...",
      ".....o....o.....",
      "....oo....oo....",
    ],
  },
  {
    id: "pig",
    name: "돼지",
    aliases: ["꿀꿀이", "pig", "돼지코"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#ffb3c6",
      d: "#ff8fab",
    },
    rows: [
      "................",
      ".kk..........kk.",
      ".kpk........kpk.",
      ".kppkkkkkkkkppk.",
      ".kppppppppppppk.",
      "kppppppppppppppk",
      "kppkppppppppkppk",
      "kppkppppppppkppk",
      "kpppkkkkkkkkpppk",
      "kpppkdkddkdkpppk",
      "kpppkkkkkkkkpppk",
      "kppppppppppppppk",
      ".kppppppppppppk.",
      "..kppppppppppk..",
      "...kkkkkkkkkk...",
      "................",
    ],
  },
  {
    id: "frog",
    name: "개구리",
    aliases: ["frog", "개굴"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      g: "#6bcb77",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      ".kkkk......kkkk.",
      "kwwwwk....kwwwwk",
      "kwkkwk....kwkkwk",
      "kwkkwkkkkkkwkkwk",
      "kggggggggggggggk",
      "kggggggggggggggk",
      "kpggggggggggggpk",
      "kgkggggggggggkgk",
      "kggkkkkkkkkkkggk",
      "kggggggggggggggk",
      ".kggggggggggggk.",
      "..kkkkkkkkkkkk..",
      "................",
      "................",
      "................",
    ],
  },
  {
    id: "penguin",
    name: "펭귄",
    aliases: ["penguin", "펭수"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      n: "#3b4a5e",
      o: "#ff9f1c",
    },
    rows: [
      "................",
      "....kkkkkkkk....",
      "...knnnnnnnnk...",
      "..knnnnnnnnnnk..",
      "..knwwwwwwwwnk..",
      ".knwkwwwwwwkwnk.",
      ".knwwwoooowwwnk.",
      ".knwwwwoowwwwnk.",
      "knnwwwwwwwwwwnnk",
      "knnwwwwwwwwwwnnk",
      "knnwwwwwwwwwwnnk",
      "knnwwwwwwwwwwnnk",
      ".knnwwwwwwwwnnk.",
      "..knnnnnnnnnnk..",
      "..kookkkkkkook..",
      "................",
    ],
  },
  {
    id: "panda",
    name: "판다",
    aliases: ["panda", "푸바오"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      ".kkk........kkk.",
      "kkkkk......kkkkk",
      "kkkkkkkkkkkkkkkk",
      "kwwwwwwwwwwwwwwk",
      "kwwwwwwwwwwwwwwk",
      "kwwkkwwwwwwkkwwk",
      "kwkwkwwwwwwkwkwk",
      "kwkkkwwwwwwkkkwk",
      "kwwwwwwkkwwwwwwk",
      "kpwwwwwwwwwwwwpk",
      ".kwwwwwwwwwwwwk.",
      "..kwwwwwwwwwwk..",
      "...kkkkkkkkkk...",
      "................",
      "................",
    ],
  },
  {
    id: "strawberry",
    name: "딸기",
    aliases: ["strawberry", "베리"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff4d5e",
      g: "#58b368",
      y: "#ffe08a",
    },
    rows: [
      "................",
      ".......kk.......",
      "...kk.kggk.kk...",
      "..kggkggggkggk..",
      ".kkggggggggggkk.",
      "krrkkggggggkkrrk",
      "krrrrkkkkkkrrrrk",
      "krryrrrrrrrryrrk",
      "krrrrrryyrrrrrrk",
      "kryrrrrrrrrrryrk",
      ".krrrryrryrrrrk.",
      ".krrrrrrrrrrrrk.",
      "..kryrrrrrryrk..",
      "...krrrrrrrrk...",
      "....kkkkkkkk....",
      "................",
    ],
  },
  {
    id: "apple",
    name: "사과",
    aliases: ["apple", "애플"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff4d5e",
      g: "#58b368",
      b: "#8a5a2b",
      h: "#ffb3bb",
    },
    rows: [
      "................",
      ".......kk.kk....",
      ".......kbkggk...",
      ".......kbkgk....",
      "..kkkkkkbkkkkk..",
      ".krrrrrrrrrrrrk.",
      "krhhrrrrrrrrrrrk",
      "krhrrrrrrrrrrrrk",
      "krrrrrrrrrrrrrrk",
      "krrrrrrrrrrrrrrk",
      "krrrrrrrrrrrrrrk",
      ".krrrrrrrrrrrrk.",
      ".krrrrrrrrrrrrk.",
      "..krrrrkkrrrrk..",
      "...kkkk..kkkk...",
      "................",
    ],
  },
  {
    id: "watermelon",
    name: "수박",
    aliases: ["watermelon", "여름"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a6e",
      g: "#3fa34d",
      l: "#bdf0a8",
    },
    rows: [
      "................",
      "................",
      "................",
      "kkkkkkkkkkkkkkkk",
      "krrrrrrrrrrrrrrk",
      "krrkrrrrrrrrkrrk",
      ".krrrrrkrrrrrrk.",
      ".krrrrrrrrkrrrk.",
      "..krrkrrrrrrrk..",
      "..llrrrrrrrrll..",
      "...kllllllllk...",
      "....kggggggk....",
      ".....kkkkkk.....",
      "................",
      "................",
      "................",
    ],
  },
  {
    id: "icecream",
    name: "아이스크림",
    aliases: ["ice cream", "콘", "아이스크림콘"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#ffb3c6",
      c: "#e2a86a",
      d: "#b8773a",
      r: "#ff4d5e",
    },
    rows: [
      "......kkkk......",
      ".....krrrrk.....",
      "....kkkkkkkk....",
      "...kppppppppk...",
      "..kppppppppppk..",
      "..kpwppppppwpk..",
      ".kppppppppppppk.",
      ".kppppppppppppk.",
      "kkkkkkkkkkkkkkkk",
      ".kcdcdcddcdcdck.",
      "..kcdcdccdcdck..",
      "...kcdcddcdck...",
      "....kcdccdck....",
      ".....kcddck.....",
      "......kcck......",
      ".......kk.......",
    ],
  },
  {
    id: "cake",
    name: "케이크",
    aliases: ["cake", "생일케이크", "생일"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      c: "#fff3e0",
      p: "#ffb3c6",
      b: "#c98a4b",
      r: "#ff4d5e",
      y: "#ffd93d",
    },
    rows: [
      "................",
      ".......yy.......",
      ".......kk.......",
      ".......kk.......",
      "....kkkkkkkk....",
      "...kppppppppk...",
      "..kppppppppppk..",
      "..kpkpkppkpkpk..",
      "..kcccccccccck..",
      "..kcccccccccck..",
      "..kbbbbbbbbbbk..",
      "..kbbbbbbbbbbk..",
      "..kcccccccccck..",
      "..kbbbbbbbbbbk..",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  {
    id: "donut",
    name: "도넛",
    aliases: ["donut", "도너츠"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#e2a86a",
      p: "#ff8fb1",
      y: "#ffd93d",
      l: "#7ec8e3",
    },
    rows: [
      "................",
      "................",
      "....kkkkkkkk....",
      "..kkppppppppkk..",
      ".kppyppppppyppk.",
      ".kpppplpplppppk.",
      "kplpppppppppplpk",
      "kppppkkkkkkppppk",
      "kpypk......kpypk",
      "kbppk......kppbk",
      "kbbppkkkkkkppbbk",
      ".kbbppppppppbbk.",
      ".kbbbbbbbbbbbbk.",
      "..kkbbbbbbbbkk..",
      "....kkkkkkkk....",
      "................",
    ],
  },
  {
    id: "flower",
    name: "꽃",
    aliases: ["flower", "튤립", "꽃송이"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#ff8fb1",
      y: "#ffd93d",
      g: "#58b368",
    },
    rows: [
      "................",
      "....kkkkkkkk....",
      "...kppppppppk...",
      ".kkkppppppppkkk.",
      "kppkppppppppkppk",
      "kpppkkkkkkkkpppk",
      "kpppkyyyyyykpppk",
      ".kkkkyyyyyykkkk.",
      "kppkkyyyyyykkppk",
      "kpppkkkkkkkkpppk",
      "kpppkppppppkpppk",
      ".kkkppppppppkkk.",
      "....kkkggkkk....",
      "..kk..kggk..kk..",
      "..kgk.kggk.kgk..",
      "...kgkggggkgk...",
    ],
  },
  {
    id: "sun",
    name: "해",
    aliases: ["태양", "sun", "햇님"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
      o: "#ff9f1c",
      p: "#ff9eb1",
    },
    rows: [
      ".......oo.......",
      ".o.....oo.....o.",
      "..o..........o..",
      "....kkkkkkkk....",
      "...kyyyyyyyyk...",
      "..kyyyyyyyyyyk..",
      "..kyykyyyykyyk..",
      "ookyykyyyykyykoo",
      "..kyyyyyyyyyyk..",
      "..kpyyyyyyyypk..",
      "..kyykyyyykyyk..",
      "...kyykkkkyyk...",
      "....kkkkkkkk....",
      "..o..........o..",
      ".o.....oo.....o.",
      ".......oo.......",
    ],
  },
  {
    id: "moon",
    name: "달",
    aliases: ["moon", "초승달", "밤"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffe27a",
    },
    rows: [
      "................",
      ".....kkkk.......",
      "...kkyyyk.......",
      "..kyyyyk........",
      ".kyyyyk.........",
      ".kyyyyk.........",
      "kyyyyk..........",
      "kyyyyk..........",
      "kyyyyk..........",
      "kyyyyyk.........",
      ".kyyyyyk......k.",
      ".kyyyyyykk..kkk.",
      "..kyyyyyyykkyyk.",
      "...kkyyyyyyyyk..",
      ".....kkkkkkkk...",
      "................",
    ],
  },
  {
    id: "cloud",
    name: "구름",
    aliases: ["cloud", "뭉게구름"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#dbe9f7",
    },
    rows: [
      "................",
      "................",
      "................",
      "......kkkk......",
      ".....kwwwwk.....",
      "..kkkwwwwwwkkk..",
      ".kwwwkwwwwkwwwk.",
      ".kwwwwwwwwwwwwk.",
      "kwwwwwwwwwwwwwwk",
      "kwwkwwwwwwwwkwwk",
      "kwwwwwkkkkwwwwwk",
      "kbwwwwwwwwwwwwbk",
      ".kbbbbbbbbbbbbk.",
      "..kkkkkkkkkkkk..",
      "................",
      "................",
    ],
  },
  {
    id: "rainbow",
    name: "무지개",
    aliases: ["rainbow", "레인보우"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a6e",
      o: "#ff9f1c",
      y: "#ffd93d",
      g: "#6bcb77",
      b: "#4d96ff",
      c: "#e8f1fb",
    },
    rows: [
      "................",
      "................",
      "....kkkkkkkk....",
      "..kkrrrrrrrrkk..",
      ".krroooooooorrk.",
      ".kroyyyyyyyyork.",
      "kroyyggggggyyork",
      "kroygbbbbbbgyork",
      "kroygbkkkkbgyork",
      "kroygbk..kbgyork",
      "kroygbk..kbgyork",
      "kkkkkkk..kkkkkkk",
      "kccckk....kkccck",
      "kccccck..kccccck",
      ".kkkkkk..kkkkkk.",
      "................",
    ],
  },
  {
    id: "tree",
    name: "나무",
    aliases: ["tree", "크리스마스트리", "숲"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      g: "#58b368",
      d: "#3f8f4f",
      b: "#8a5a2b",
    },
    rows: [
      "................",
      "....kkkkkkkk....",
      "...kggggggggk...",
      "..kggggggggggk..",
      ".kgggggddgggggk.",
      ".kgdggggggggdgk.",
      "kggggggggggggggk",
      "kgggggdggdgggggk",
      "kggdggggggggdggk",
      ".kggggggggggggk.",
      "..kkkggggggkkk..",
      "....kkbbbbkk....",
      ".....kbbbbk.....",
      ".....kbbbbk.....",
      "....kkkkkkkk....",
      "................",
    ],
  },
  {
    id: "snowman",
    name: "눈사람",
    aliases: ["snowman", "겨울", "눈"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      o: "#ff9f1c",
      r: "#ff4d5e",
      b: "#dbe9f7",
    },
    rows: [
      "....kkkkkkkk....",
      "....kkkkkkkk....",
      "...kkkkkkkkkk...",
      "....kwwwwwwk....",
      "...kwkwwwwkwk...",
      "...kwwwoowwwk...",
      "...kwwwwwwwwk...",
      "..kkrrrrrrrrkk..",
      ".kwwwwrrrrwwwwk.",
      "kwwwwwwkkwwwwwwk",
      "kwwwwwwwwwwwwwwk",
      "kwwwwwwkkwwwwwwk",
      "kbwwwwwwwwwwwwbk",
      ".kbbbbbbbbbbbbk.",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  {
    id: "house",
    name: "집",
    aliases: ["house", "home", "우리집"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff6b6b",
      y: "#fff3c4",
      b: "#b8773a",
      l: "#7ec8e3",
    },
    rows: [
      ".......kk.......",
      "......krrk......",
      ".....krrrrk.....",
      "....krrrrrrk....",
      "...krrrrrrrrk...",
      "..krrrrrrrrrrk..",
      ".kkkkkkkkkkkkkk.",
      "..kyyyyyyyyyyk..",
      "..kykkkyykkkyk..",
      "..kyklkyyklkyk..",
      "..kykkkyykkkyk..",
      "..kyyykkkkyyyk..",
      "..kyyykbbkyyyk..",
      "..kyyykbbkyyyk..",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  {
    id: "crown",
    name: "왕관",
    aliases: ["crown", "왕", "공주"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
      r: "#ff4d5e",
      b: "#4d96ff",
    },
    rows: [
      "................",
      "................",
      ".k.....kk.....k.",
      "kyk...kyyk...kyk",
      "kyyk.kyyyyk.kyyk",
      "kyyykyyyyyykyyyk",
      "kyyyyyyyyyyyyyyk",
      "kyyyyyyyyyyyyyyk",
      "kyyryyybbyyyryyk",
      "kyyyyyyyyyyyyyyk",
      "kkkkkkkkkkkkkkkk",
      "kyyyyyyyyyyyyyyk",
      "kkkkkkkkkkkkkkkk",
      "................",
      "................",
      "................",
    ],
  },
  {
    id: "gift",
    name: "선물",
    aliases: ["gift", "선물상자", "present"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a6e",
      y: "#ffd93d",
    },
    rows: [
      "................",
      "...kk..kk..kk...",
      "..kyyk.kk.kyyk..",
      "..kyyykkkkyyyk..",
      "...kkkkyykkkk...",
      "kkkkkkkyykkkkkkk",
      "krrrrrryyrrrrrrk",
      "krrrrrryyrrrrrrk",
      "kkkkkkkyykkkkkkk",
      ".krrrrryyrrrrrk.",
      ".krrrrryyrrrrrk.",
      ".krrrrryyrrrrrk.",
      ".krrrrryyrrrrrk.",
      ".krrrrryyrrrrrk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  },
  {
    id: "balloon",
    name: "풍선",
    aliases: ["balloon", "파티"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a6e",
      h: "#ffc2cb",
    },
    rows: [
      "................",
      ".....kkkkkk.....",
      "....krrrrrrk....",
      "...krhhrrrrrk...",
      "...krhrrrrrrk...",
      "...krrrrrrrrk...",
      "...krrrrrrrrk...",
      "....krrrrrrk....",
      ".....krrrrk.....",
      "......krrk......",
      ".......kk.......",
      "........k.......",
      ".......k........",
      "........k.......",
      ".......k........",
      "................",
    ],
  },
  {
    id: "mushroom",
    name: "버섯",
    aliases: ["mushroom", "버섯돌이"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a6e",
      c: "#fff3e0",
    },
    rows: [
      "................",
      "....kkkkkkkk....",
      "..kkrrrrrrrrkk..",
      ".krrwwrrrrwwrrk.",
      ".krwwwrrrrwwwrk.",
      "krrrrrrwwrrrrrrk",
      "kwrrrrrwwrrrrrwk",
      "kwwrrrrrrrrrrwwk",
      "kkkkkkkkkkkkkkkk",
      "...kcccccccck...",
      "...kckcccckck...",
      "...kckcccckck...",
      "...kcccccccck...",
      "...kcccccccck...",
      "....kkkkkkkk....",
      "................",
    ],
  },
  {
    id: "ghost",
    name: "유령",
    aliases: ["ghost", "귀신", "할로윈"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      "....kkkkkkkk....",
      "...kwwwwwwwwk...",
      "..kwwwwwwwwwwk..",
      ".kwwwwwwwwwwwwk.",
      ".kwwkwwwwwwkwwk.",
      ".kwwkwwwwwwkwwk.",
      ".kpwwwwwwwwwwpk.",
      ".kwwwwwkkwwwwwk.",
      ".kwwwwwwwwwwwwk.",
      ".kwwwwwwwwwwwwk.",
      ".kwwwwwwwwwwwwk.",
      ".kwwwwwwwwwwwwk.",
      ".kwkkwwwwwwkkwk.",
      ".kk..kkkkkk..kk.",
      "................",
    ],
  },
  {
    id: "rocket",
    name: "로켓",
    aliases: ["rocket", "우주", "우주선"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a6e",
      l: "#7ec8e3",
      o: "#ff9f1c",
      y: "#ffd93d",
    },
    rows: [
      ".......kk.......",
      "......krrk......",
      ".....krrrrk.....",
      ".....kwwwwk.....",
      "....kwwwwwwk....",
      "....kwkkkkwk....",
      "....kwkllkwk....",
      "....kwkkkkwk....",
      "....kwwwwwwk....",
      "...krwwwwwwrk...",
      "..krrwwwwwwrrk..",
      "..krrkkkkkkrrk..",
      "..kk.kyooyk.kk..",
      ".......yy.......",
      "................",
      "................",
    ],
  },
  {
    id: "boy",
    name: "남자",
    aliases: ["남자아이", "소년", "boy", "사람", "친구", "아이", "나", "아빠"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      h: "#3b2a20",
      s: "#ffd7b5",
      p: "#ff9eb1",
      b: "#4d96ff",
    },
    rows: [
      "................",
      "...kkkkkkkkkk...",
      "..khhhhhhhhhhk..",
      ".khhhhhhhhhhhhk.",
      ".khhhhhhhhhhhhk.",
      "khhsssssssssshhk",
      "khsssssssssssshk",
      "khsskssssssksshk",
      "khsskssssssksshk",
      ".kspsssssssspsk.",
      ".kssssskksssssk.",
      "..kssssssssssk..",
      "...kkkkkkkkkk...",
      ".kkbbbbbbbbbbkk.",
      "kbbbbbbbbbbbbbbk",
      "kbbbbbbbbbbbbbbk",
    ],
  },
  {
    id: "girl",
    name: "여자",
    aliases: ["여자아이", "소녀", "girl", "엄마", "언니", "누나"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      h: "#6b3e1f",
      s: "#ffd7b5",
      p: "#ff9eb1",
      d: "#ff8fb1",
      r: "#ff4d5e",
    },
    rows: [
      "................",
      "..rkkkkkkkkkkr..",
      ".rrhhhhhhhhhhrr.",
      "..rhhhhhhhhhhr..",
      "khhhhhhhhhhhhhhk",
      "khhsssssssssshhk",
      "khsssssssssssshk",
      "khsskssssssksshk",
      "khsskssssssksshk",
      "khpssssssssssphk",
      "khssssskkssssshk",
      "khhsssssssssshhk",
      "khhkkkkkkkkkkhhk",
      "khkddddddddddkhk",
      "kkddddddddddddkk",
      "kddddddddddddddk",
    ],
  },
  {
    id: "hamster",
    name: "햄스터",
    aliases: ["hamster", "햄찌", "다람쥐"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      h: "#f2c08a",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      "................",
      "..kk........kk..",
      ".khhk......khhk.",
      ".khpkkkkkkkkphk.",
      ".khhhhhhhhhhhhk.",
      "khhhhhhhhhhhhhhk",
      "khhkhhhhhhhhkhhk",
      "kwwkhhhhhhhhkwwk",
      "kwpwwwwppwwwwpwk",
      "kwwwwwwkkwwwwwwk",
      ".kwwwwwwwwwwwwk.",
      "..khhwwwwwwhhk..",
      "...kkkkkkkkkk...",
      "................",
      "................",
    ],
  },
  {
    id: "fox",
    name: "여우",
    aliases: ["fox", "여우비"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      o: "#f28c38",
    },
    rows: [
      "................",
      "k..............k",
      "kk............kk",
      "kok..........kok",
      "kowk........kwok",
      "kowokkkkkkkkowok",
      "kooooooooooooook",
      "kookooooooookook",
      "kookooooooookook",
      "kwwwoooooooowwwk",
      ".kwwwwoooowwwwk.",
      "..kwwwwwwwwwwk..",
      "...kwwwwwwwwk...",
      "....kwwkkwwk....",
      ".....kkkkkk.....",
      "................",
    ],
  },
  {
    id: "lion",
    name: "사자",
    aliases: ["lion", "라이언", "호랑이", "tiger"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      m: "#c9651c",
      y: "#ffc94d",
    },
    rows: [
      "................",
      "...kkkkkkkkkk...",
      ".kkmmmmmmmmmmkk.",
      "kmmmmmmmmmmmmmmk",
      "kmmmkkkkkkkkmmmk",
      "kmmkyyyyyyyykmmk",
      "kmkyyyyyyyyyykmk",
      "kmkyykyyyykyykmk",
      "kmkyykyyyykyykmk",
      "kmkyyyykkyyyykmk",
      "kmkyyyyyyyyyykmk",
      "kmmkyyyyyyyykmmk",
      "kmmmkkkkkkkkmmmk",
      ".kmmmmmmmmmmmmk.",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  {
    id: "koala",
    name: "코알라",
    aliases: ["koala"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      g: "#a8b0b8",
      l: "#d7dde3",
    },
    rows: [
      "................",
      ".kkk........kkk.",
      "kgggk......kgggk",
      "kglgkkkkkkkkglgk",
      "kggggggggggggggk",
      ".kggggggggggggk.",
      ".kggkggggggkggk.",
      ".kggkggggggkggk.",
      ".kgggkkkkkkgggk.",
      ".kgggkkkkkkgggk.",
      ".kggggkkkkggggk.",
      ".kggggggggggggk.",
      "..kggggggggggk..",
      "...kkkkkkkkkk...",
      "................",
      "................",
    ],
  },
  {
    id: "owl",
    name: "부엉이",
    aliases: ["owl", "올빼미"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#8a5a2b",
      t: "#e8c39e",
      o: "#ff9f1c",
    },
    rows: [
      "................",
      "k..............k",
      "kk............kk",
      "kbkkkkkkkkkkkkbk",
      "kbbbbbbbbbbbbbbk",
      "kbkkkbbbbbbkkkbk",
      "kkwwwkbbbbkwwwkk",
      "kkwkwkboobkwkwkk",
      "kbkkkbboobbkkkbk",
      "kbbttttttttttbbk",
      "kbttttttttttttbk",
      "kbttttttttttttbk",
      ".kbttttttttttbk.",
      "..kkkkkkkkkkkk..",
      "...o..o..o..o...",
      "................",
    ],
  },
  {
    id: "fish",
    name: "물고기",
    aliases: ["fish", "생선", "금붕어", "바다", "고래"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#4d96ff",
      l: "#9ccaff",
    },
    rows: [
      "................",
      "................",
      "................",
      "................",
      ".....kkkkk......",
      "...kkbbblbkk..kk",
      "..kbbbbblbbbkkbk",
      ".kbwkbbblbbbbbbk",
      ".kbkkbbblbbbbbbk",
      ".kbbbbbblbbbbbbk",
      "..kbbbbblbbbkkbk",
      "...kkbbblbkk..kk",
      ".....kkkkk......",
      "................",
      "................",
      "................",
    ],
  },
  {
    id: "octopus",
    name: "문어",
    aliases: ["octopus", "오징어", "낙지"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#b388eb",
      r: "#ff9eb1",
    },
    rows: [
      "................",
      "....kkkkkkkk....",
      "..kkppppppppkk..",
      ".kppppppppppppk.",
      ".kppppppppppppk.",
      "kppppppppppppppk",
      "kppkppppppppkppk",
      "kppkppppppppkppk",
      "krpppppppppppprk",
      "kppppppkkppppppk",
      "kppppppppppppppk",
      "kpkpkpkppkpkpkpk",
      "kpkpkpkppkpkpkpk",
      "k.k.k.kkkk.k.k.k",
      "................",
      "................",
    ],
  },
  {
    id: "butterfly",
    name: "나비",
    aliases: ["butterfly", "나방"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#ff8fb1",
      l: "#b388eb",
      y: "#ffd93d",
    },
    rows: [
      "................",
      ".....k....k.....",
      ".kkk..k..k..kkk.",
      "kpppk..kk..kpppk",
      "kpyppk.kk.kppypk",
      "kpppppkkkkpppppk",
      "kppppppkkppppppk",
      ".kpppppkkpppppk.",
      "..kkkkkkkkkkkk..",
      ".kllllkkkkllllk.",
      "kllyllkkkkllyllk",
      "klllllkkkklllllk",
      ".kllllkkkkllllk.",
      "..kkkk.kk.kkkk..",
      "................",
      "................",
    ],
  },
  {
    id: "ladybug",
    name: "무당벌레",
    aliases: ["ladybug", "벌레", "곤충"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff4d5e",
    },
    rows: [
      "................",
      ".....k....k.....",
      ".....kkkkkk.....",
      "....kwkkkkwk....",
      "..krrrkkkkrrrk..",
      ".krrrrrkkrrrrrk.",
      ".krkkrrkkrrkkrk.",
      "krrkkrrkkrrkkrrk",
      "krrrrrrkkrrrrrrk",
      "krrrkkrkkrkkrrrk",
      "krrrkkrkkrkkrrrk",
      ".krrrrrkkrrrrrk.",
      "..krrrrkkrrrrk..",
      "...kkkkkkkkkk...",
      "................",
      "................",
    ],
  },
  {
    id: "dinosaur",
    name: "공룡",
    aliases: ["dinosaur", "티라노", "dino", "용"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      g: "#6bcb77",
      l: "#c8f0b0",
    },
    rows: [
      "................",
      ".......kkkkkk...",
      "......kggggggk..",
      "......kggkggggk.",
      "......kgggggggk.",
      "......kggggkkkk.",
      ".k....kggggk....",
      ".kk..kgggggkk...",
      ".kgkkgglllgkgk..",
      "..kgggglllgkk...",
      "..kggggllggk....",
      "...kgggggggk....",
      "....kggkkggk....",
      "....kgk..kgk....",
      "....kk...kk.....",
      "................",
    ],
  },
  {
    id: "turtle",
    name: "거북이",
    aliases: ["turtle", "거북"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      g: "#8fd694",
      d: "#3f8f4f",
      l: "#6bcb77",
    },
    rows: [
      "................",
      "......kkkk......",
      ".....kggggk.....",
      ".....kkggkk.....",
      "..k..kkkkkk..k..",
      ".kgkkddddddkkgk.",
      ".kgkdllddlldkgk.",
      "...kddddddddk...",
      "...kdllddlldk...",
      "...kdllddlldk...",
      ".kgkddddddddkgk.",
      ".kgkkkkkkkkkkgk.",
      "..k....kk....k..",
      "................",
      "................",
      "................",
    ],
  },
  {
    id: "burger",
    name: "햄버거",
    aliases: ["burger", "hamburger", "버거", "패스트푸드"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#e2a86a",
      g: "#6bcb77",
      y: "#ffd93d",
      d: "#6b3e1f",
    },
    rows: [
      "................",
      "................",
      "................",
      "....kkkkkkkk....",
      "..kkbbbbbbbbkk..",
      ".kbbwbbbbbbwbbk.",
      "kbbbbbbbbbbbbbbk",
      "kkkkkkkkkkkkkkkk",
      "kggggggggggggggk",
      "kyyyyyyyyyyyyyyk",
      "kddddddddddddddk",
      "kddddddddddddddk",
      "kkkkkkkkkkkkkkkk",
      "kbbbbbbbbbbbbbbk",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  },
  {
    id: "pizza",
    name: "피자",
    aliases: ["pizza", "치즈"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      c: "#e2a86a",
      y: "#ffd93d",
      r: "#ff4d5e",
    },
    rows: [
      "................",
      "................",
      "kkkkkkkkkkkkkkkk",
      "kcccccccccccccck",
      "kyyyyyyyyyyyyyyk",
      ".kyrryyyyyyrryk.",
      ".kyrryyyyyyrryk.",
      "..kyyyrrrryyyk..",
      "..kyyyrrrryyyk..",
      "...kyyyyyyyyk...",
      "...kyyyyyyyyk...",
      "....kyyyyyyk....",
      "....kyyyyyyk....",
      ".....kyyyyk.....",
      "......kkkk......",
      "................",
    ],
  },
  {
    id: "cherry",
    name: "체리",
    aliases: ["cherry", "앵두"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff4d5e",
      g: "#58b368",
    },
    rows: [
      "................",
      ".......gg.......",
      "......g..g......",
      ".....g....g.....",
      "....g......g....",
      "...g........g...",
      "..kkk......kkk..",
      ".krrrk....krrrk.",
      "krwrrrk..krrrwrk",
      "krrrrrk..krrrrrk",
      "krrrrrk..krrrrrk",
      ".krrrk....krrrk.",
      "..kkk......kkk..",
      "................",
      "................",
      "................",
    ],
  },
  {
    id: "grape",
    name: "포도",
    aliases: ["grape", "청포도"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#8e5bd6",
      l: "#c3a2f0",
      b: "#8a5a2b",
      g: "#58b368",
    },
    rows: [
      ".....ggbbgg.....",
      "......gbbg......",
      "..kkkkkkkkkkkk..",
      ".kplpplpplpplpk.",
      ".kppppppppppppk.",
      ".kplpplpplpplpk.",
      "..kppppppppppk..",
      "..kplppllpplpk..",
      "...kppppppppk...",
      "...kplpppplpk...",
      "....kppppppk....",
      ".....kpllpk.....",
      "......kkkk......",
      "................",
      "................",
      "................",
    ],
  },
  {
    id: "coffee",
    name: "커피",
    aliases: ["coffee", "카페", "라떼", "아메리카노", "음료"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#c98a4b",
    },
    rows: [
      "................",
      "..kkkkkkkkkkkk..",
      ".kwwwwwwwwwwwwk.",
      ".kkkkkkkkkkkkkk.",
      "..kwwwwwwwwwwk..",
      "..kwwwwwwwwwwk..",
      "..kbbbbbbbbbbk..",
      "..kbbbbbbbbbbk..",
      "...kbbbbbbbbk...",
      "...kwwwwwwwwk...",
      "...kwwwwwwwwk...",
      "....kwwwwwwk....",
      "....kkkkkkkk....",
      "................",
      "................",
      "................",
    ],
  },
  {
    id: "cookie",
    name: "쿠키",
    aliases: ["cookie", "과자", "비스킷"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      c: "#d9a066",
      d: "#6b3e1f",
    },
    rows: [
      "................",
      "................",
      "....kkkkkkkk....",
      "..kkcccccccckk..",
      ".kccdccccccdcck.",
      ".kcccccddccccck.",
      "kcccccccccccccck",
      "kcdccccccccccdck",
      "kccccdccccdcccck",
      "kcccccccccccccck",
      "kcccdccccccdccck",
      ".kcccccccccccck.",
      ".kccdccccccdcck.",
      "..kkcccccccckk..",
      "....kkkkkkkk....",
      "................",
    ],
  },
  {
    id: "candy",
    name: "사탕",
    aliases: ["candy", "캔디", "막대사탕"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#ff8fb1",
      y: "#ffd93d",
    },
    rows: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "kk...kkkkkk...kk",
      "kpk.kyyppyyk.kpk",
      "kppkpyyppyypkppk",
      "kppkppyyyyppkppk",
      "kpk.kpyyyypk.kpk",
      "kk...kkkkkk...kk",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    id: "pudding",
    name: "푸딩",
    aliases: ["pudding", "푸린", "젤리", "디저트"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffe08a",
      d: "#9c6334",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      "................",
      "................",
      "....kkkkkkkk....",
      "...kddddddddk...",
      "..kddddddddddk..",
      "..kyyyyyyyyyyk..",
      ".kyyyyyyyyyyyyk.",
      ".kyyykyyyykyyyk.",
      ".kpyyyyyyyyyypk.",
      "kyyyyyykkyyyyyyk",
      "kyyyyyyyyyyyyyyk",
      "kkkkkkkkkkkkkkkk",
      ".kwwwwwwwwwwwwk.",
      "kkkkkkkkkkkkkkkk",
      "................",
    ],
  },
  {
    id: "riceball",
    name: "주먹밥",
    aliases: ["onigiri", "삼각김밥", "김밥", "밥"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      n: "#2f4f3a",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      "................",
      "......kkkk......",
      ".....kwwwwk.....",
      "....kwwwwwwk....",
      "....kwwwwwwk....",
      "...kwkwwwwkwk...",
      "...kwwwwwwwwk...",
      "..kpwwwwwwwwpk..",
      "..kwwnnnnnnwwk..",
      ".kwwwnnnnnnwwwk.",
      ".kwwwnnnnnnwwwk.",
      ".kkkkkkkkkkkkkk.",
      "................",
      "................",
      "................",
    ],
  },
  {
    id: "car",
    name: "자동차",
    aliases: ["car", "차", "붕붕", "버스", "bus"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a6e",
      l: "#bde4ff",
      y: "#ffd93d",
      g: "#8a8a8a",
    },
    rows: [
      "................",
      "................",
      "................",
      "................",
      "....kkkkkkkk....",
      "...krrrrrrrrk...",
      "..krlllkklllrk..",
      ".krrrrrrrrrrrrk.",
      "krrrrrrrrrrrrrrk",
      "kyrrrrrrrrrrrryk",
      "krkkkrrrrrrkkkrk",
      ".kkgkkkkkkkkgkk.",
      "..kkk......kkk..",
      "................",
      "................",
      "................",
    ],
  },
  {
    id: "airplane",
    name: "비행기",
    aliases: ["airplane", "plane", "여행"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#7ec8e3",
      l: "#4d96ff",
    },
    rows: [
      ".......kk.......",
      "......kwwk......",
      "......kwwk......",
      "......kllk......",
      "......kwwk......",
      "...kkkkwwkkkk...",
      ".kkbbbbwwbbbbkk.",
      "kbbbbbbwwbbbbbbk",
      "kkkkkkkwwkkkkkkk",
      "......kwwk......",
      "......kwwk......",
      "....kkkwwkkk....",
      "...kbbbwwbbbk...",
      "...kkkkkkkkkk...",
      "................",
      "................",
    ],
  },
  {
    id: "umbrella",
    name: "우산",
    aliases: ["umbrella", "비", "장마", "rain"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a6e",
      y: "#ffd93d",
    },
    rows: [
      "................",
      "................",
      "....kkkkkkkk....",
      "..kkrryyyyrrkk..",
      ".krrryyyyyyrrrk.",
      "krrrryyyyyyrrrrk",
      "krrrryyyyyyrrrrk",
      "kkkkkkkkkkkkkkkk",
      ".......kk.......",
      ".......kk.......",
      ".......kk.......",
      ".......kk.......",
      ".......kk.......",
      ".......kk.......",
      "................",
      "................",
    ],
  },
  {
    id: "music",
    name: "음표",
    aliases: ["music", "노래", "음악", "note"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#8e5bd6",
    },
    rows: [
      "................",
      "....kkkkkkkkk...",
      "....kppppppkk...",
      "....kkkkkkkkk...",
      "....k.......k...",
      "....k.......k...",
      "....k.......k...",
      "....k.......k...",
      "..kkk.....kkk...",
      ".kpppk...kpppk..",
      ".kpppk...kpppk..",
      "..kkk.....kkk...",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    id: "ball",
    name: "공",
    aliases: ["ball", "농구공", "농구", "축구공", "축구", "운동"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      o: "#f28c38",
    },
    rows: [
      "................",
      "................",
      "....kkkkkkkk....",
      "..kkoookkoookk..",
      ".kooookookooook.",
      ".kooookookooook.",
      "kkooookookooookk",
      "kokkkkkkkkkkkkok",
      "kookoookkoookook",
      "koooookookoooook",
      "koooookookoooook",
      ".kooookookooook.",
      ".kooookookooook.",
      "..kkoookkoookk..",
      "....kkkkkkkk....",
      "................",
    ],
  },
  {
    id: "diamond",
    name: "보석",
    aliases: ["diamond", "다이아몬드", "다이아", "반지"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      l: "#bde4ff",
      b: "#4d96ff",
    },
    rows: [
      "................",
      "................",
      "................",
      "..kkkkkkkkkkkk..",
      ".kllwllbbllwllk.",
      "kkkkkkkkkkkkkkkk",
      ".kbbbllllllbbbk.",
      "..kbbbllllbbbk..",
      "...kbbllllbbk...",
      "....kbbllbbk....",
      ".....kbllbk.....",
      "......kbbk......",
      ".......kk.......",
      "................",
      "................",
      "................",
    ],
  },
  {
    id: "ribbon",
    name: "리본",
    aliases: ["ribbon", "bow", "나비넥타이"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      p: "#ff8fb1",
    },
    rows: [
      "................",
      "................",
      "................",
      "................",
      "kk............kk",
      "kpkk........kkpk",
      "kpppk.kkkk.kpppk",
      "kppppkppppkppppk",
      "kppppkppppkppppk",
      "kpppk.kkkk.kpppk",
      "kkk..kpkkpk..kkk",
      ".....kpkkpk.....",
      "....kpk..kpk....",
      "....kk....kk....",
      "................",
      "................",
    ],
  },
  {
    id: "smile",
    name: "스마일",
    aliases: ["smile", "웃음", "행복", "이모지", "기쁨"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
      p: "#ff9eb1",
    },
    rows: [
      "................",
      "................",
      "....kkkkkkkk....",
      "..kkyyyyyyyykk..",
      ".kyyyyyyyyyyyyk.",
      ".kyyyyyyyyyyyyk.",
      "kyyykyyyyyykyyyk",
      "kyyykyyyyyykyyyk",
      "kpyyyyyyyyyyyypk",
      "kyykyyyyyyyykyyk",
      "kyyykkkkkkkkyyyk",
      ".kyyyyyyyyyyyyk.",
      ".kyyyyyyyyyyyyk.",
      "..kkyyyyyyyykk..",
      "....kkkkkkkk....",
      "................",
    ],
  },
  {
    id: "cactus",
    name: "선인장",
    aliases: ["cactus", "다육이", "화분", "식물"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      g: "#58b368",
      o: "#d9774b",
      p: "#ff8fb1",
    },
    rows: [
      ".......pp.......",
      "......kkkk......",
      ".....kggggk.....",
      ".....kggggk.....",
      ".kk..kggggk..kk.",
      "kggk.kggggk.kggk",
      "kggk.kggggk.kggk",
      "kggkkkggggkkkggk",
      ".kggggggggggggk.",
      "..kkkkggggkkkk..",
      ".....kggggk.....",
      ".....kggggk.....",
      "..kkkkkkkkkkkk..",
      "..kooooooooook..",
      "...kooooooook...",
      "...kkkkkkkkkk...",
    ],
  },
  {
    id: "clover",
    name: "클로버",
    aliases: ["clover", "네잎클로버", "행운", "잎"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      g: "#58b368",
      l: "#8fd694",
    },
    rows: [
      "................",
      "...kkk....kkk...",
      "..kgggk..kgggk..",
      ".kgglggkkgglggk.",
      ".kgggggkkgggggk.",
      ".kgggggkkgggggk.",
      "..kgggkkkkgggk..",
      "...kkkkggkkkk...",
      "..kgggkkkkgggk..",
      ".kgggggkkgggggk.",
      ".kgglggkkgglggk.",
      ".kgggggkkgggggk.",
      "..kgggk..kgggk..",
      "...kkk....kkk...",
      "................",
      "................",
    ],
  },
  {
    id: "lightning",
    name: "번개",
    aliases: ["lightning", "번쩍", "전기", "천둥"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      y: "#ffd93d",
    },
    rows: [
      "................",
      ".......kkkkk....",
      "......kyyyyk....",
      ".....kyyyyk.....",
      "....kyyyyk......",
      "...kyyyyk.......",
      "..kyyyyykkkkk...",
      "..kyyyyyyyyyk...",
      "..kkkkkyyyyk....",
      "......kyyyk.....",
      ".....kyyyk......",
      ".....kyyk.......",
      "....kyyk........",
      "....kyk.........",
      "....kk..........",
      "................",
    ],
  },
  {
    id: "snowflake",
    name: "눈송이",
    aliases: ["snowflake", "눈꽃", "크리스탈"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      b: "#7ec8e3",
    },
    rows: [
      "................",
      ".......bb.......",
      ".....b.bb.b.....",
      "......bbbb......",
      "..b....bb....b..",
      "...b...bb...b...",
      "....b..bb..b....",
      ".bbbbbbbbbbbbbb.",
      ".bbbbbbbbbbbbbb.",
      "....b..bb..b....",
      "...b...bb...b...",
      "..b....bb....b..",
      "......bbbb......",
      ".....b.bb.b.....",
      ".......bb.......",
      "................",
    ],
  },
  {
    id: "fire",
    name: "불",
    aliases: ["fire", "불꽃", "열정", "hot"],
    palette: {
      k: "#2b2b2b",
      w: "#ffffff",
      r: "#ff5a3c",
      o: "#ff9f1c",
      y: "#ffd93d",
    },
    rows: [
      "................",
      ".......kk.......",
      "......krrk......",
      "......krrk......",
      ".....krrrrk.....",
      "..k..krrrrk..k..",
      ".krk.kroork.krk.",
      ".krrkkroorkkrrk.",
      "krrrroyyyyorrrrk",
      "krrrooyyyyoorrrk",
      "krrooyyyyyyoorrk",
      "krrooyyyyyyoorrk",
      ".krrooyyyyoorrk.",
      "..krroooooorrk..",
      "...kkkkkkkkkk...",
      "................",
    ],
  },
];
